### ISSUE TITLE
UI corrupted

### ISSUE THREAD

**Issue by rangitgaddam** [appreciated/vaadin-app-layout#10]
After adding your library my whole app is corrupted and my components look very ugly just attaching the one screen shot of my login page.

![screenshot from 2017-09-27 20-16-50](https://user-images.githubusercontent.com/8541793/30920998-fd404fd2-a3c2-11e7-8a33-07fc7141478d.png)

![screenshot from 2017-09-27 20-27-20](https://user-images.githubusercontent.com/8541793/30920999-fd43603c-a3c2-11e7-8b23-7e3571d8b078.png)

**Comment by appreciated** [comment]
Ahh yeah I stumbled over this one a few day ago, The Material Design is currently incompatible with this addon. Needs some investigation from my part, with Valo it works flawlessly btw. I will take a look in this today.

**Comment by appreciated** [comment]
Fix is online!
