### ISSUE TITLE
How to refresh a view?

### ISSUE THREAD

**Issue by RadoJoker** [appreciated/vaadin-app-layout#100]
Given the menue with 2 elements (Connect/Disconnect and ShowData) the first one just a button connecting/disconnecting the backend to a third platform while the ShowData opens a view containing a table. In case the backend is connected the table is filled with data while in case it's not connected a simple label with "No available data" is shown.  Happens sometimes to have the view with the "No available data" shown and then the user presses on "Connect/Disconnect" to activate the connection. How it's possible to refresh the view containing the table with the data only? If I use Page.getCurrent().reload(); the whole application is refreshed.

Thank you
Radostin

**Comment by appreciated** [comment]
Checkout [Server Push](https://vaadin.com/docs/framework/advanced/advanced-push.html) for this
