### ISSUE TITLE
Broken menu with push enabled and async=true

### ISSUE THREAD

**Issue by kamuffe** [appreciated/vaadin-app-layout#102]
Hi.

Vaadin 8.1.6
vaadin-app-layout 0.9.19

Please see attached screenshots. When enabling async transport with push the menu is broken. If I reload the page with F5 it's working. Clearing cache again and reload is broken again.

at the UI:
@Push( transport = Transport.LONG_POLLING )

at the servlet:
@WebServlet( name = "MyApp", displayName = "MyApp", urlPatterns = {
		// used to handle static resources
		"/VAADIN/*",
		// the general application
		"/*"
}, loadOnStartup = 1, initParams = {
		@WebInitParam( name = "productionMode", value = "true" ),
		@WebInitParam( name = "closeIdleSessions", value = "true" ),
		@WebInitParam( name = "heartbeatInterval", value = "120" )
}, asyncSupported = true

If I disable async and push the issue is gone. But I really want to use async push in the future

<img width="1384" alt="bildschirmfoto 2018-02-22 um 13 17 21" src="https://user-images.githubusercontent.com/5285367/36542734-fa8f5808-17e1-11e8-80b9-efa109b18306.png">

<img width="1384" alt="bildschirmfoto 2018-02-22 um 13 25 38" src="https://user-images.githubusercontent.com/5285367/36539046-bd10b35c-17d5-11e8-8283-72dffe5d3366.png">
<img width="1386" alt="bildschirmfoto 2018-02-22 um 13 29 42" src="https://user-images.githubusercontent.com/5285367/36539047-bd2aa622-17d5-11e8-9bec-b92fb97ca7ee.png">

 )

**Comment by appreciated** [comment]
Seems like the Servlet you are using is wrongly configured and the JavaScript dependencies cannot be retrieved. May I see the content of the Network Tab?

**Comment by DinuMihnea** [comment]
Hi 
I have some issue in my project and sometimes in [vaadin-app-layout-demo](https://app-layout-demo.herokuapp.com/) is present:
![demo-error](https://user-images.githubusercontent.com/20513656/37338456-2da87bd8-26c0-11e8-9c6f-7128469980c7.png)

**Comment by kamuffe** [comment]
Hi.

Sorry for the late answer and thanks a lot for four investigation.

Please finde the attached screenshots with the logoutput from network tab. Let me know if you need something else.

<img width="1779" alt="bildschirmfoto 2018-03-15 um 15 42 40" src="https://user-images.githubusercontent.com/5285367/37470560-0f25bd66-2868-11e8-803e-ec1a7ae80491.png">
<img width="1785" alt="bildschirmfoto 2018-03-15 um 15 42 53" src="https://user-images.githubusercontent.com/5285367/37470561-0f592110-2868-11e8-9251-3ddee39bbb64.png">
<img width="1784" alt="bildschirmfoto 2018-03-15 um 15 43 05" src="https://user-images.githubusercontent.com/5285367/37470562-0f7b448e-2868-11e8-8a15-934dd3387394.png">
<img width="1778" alt="bildschirmfoto 2018-03-15 um 15 43 16" src="https://user-images.githubusercontent.com/5285367/37470563-0f9b5828-2868-11e8-904c-574f62cfef35.png">
<img width="1781" alt="bildschirmfoto 2018-03-15 um 15 43 29" src="https://user-images.githubusercontent.com/5285367/37470564-0fbb4318-2868-11e8-8567-a087c5db1100.png">

**Comment by kamuffe** [comment]
Forgot to mention that this issue only appears in Chrome, not in Firefox.

**Comment by appreciated** [comment]
Should be resolved with with `0.9.21` please reopen if not.
