### ISSUE TITLE
Is there a way to have a button visible in the menu but disable it?

### ISSUE THREAD

**Issue by RadoJoker** [appreciated/vaadin-app-layout#105]
What's the way to have a button in menu but disabled?

Best regards

**Comment by appreciated** [comment]
Checkout issue #104. If it doesn't answer your question define what you mean by a button exactly (f.e. the  Menu Button?). It would be really helpful if you add some screenshots.

**Comment by RadoJoker** [comment]
A button in the menu is created this way:
builder.add("Menu button XXX", VaadinIcons.FACTORY, new XXXView());

At this point there is a new entry in the menu "Menu button XXX" and when it's clicked it opens the XXXView. Is it possible to have this disabled somehow?

**Comment by RadoJoker** [comment]
Bingo! it's something like:
                menu.getMenuElementHolder().getComponent(i).setEnabled(false);

Thank you
