### ISSUE TITLE
Possible  to use in sub layout or in the views

### ISSUE THREAD

**Issue by rangitgaddam** [appreciated/vaadin-app-layout#11]
Woaah nice it is working for the Material Addon also now i have one more question is it possible to add this component inside the views for example how do i use this inside grid cells where i need to open the app Layout  within the grid cell instead of opening this on top of whole view page at left side of the page

**Comment by appreciated** [comment]
Sorry but I'm not sure If I understand your question correctly, would you mind using sth. like paint? To explain it to me does not need to look good. I just need to know what (and where) do you want the current behavoir to be different?

**Comment by appreciated** [comment]
With this method you can manipulate the Navigator View Holder
```
withNavigatorProducer(componentHolder -> {
                    VerticalLayout leftContent = new VerticalLayout(new Button("My Button"));
                    VerticalLayout rightNavigatorContent = new VerticalLayout();
                    HorizontalLayout holder = new HorizontalLayout();
                    holder.setSizeFull();
                    componentHolder.addComponent(holder);
                    return new Navigator(this,rightNavigatorContent);
                })
```

**Comment by appreciated** [comment]
And ofcourse you can try to wrap the layout inside of other Component
```
  HorizontalLayout layout = new HorizontalLayout(new Button(), drawer);
        layout.setSizeFull();
        setContent(layout);
```

But this requires some additional css manipulation since the Menu is `position:fixed` to the left
