### ISSUE TITLE
Use App Layout with Touchkit components

### ISSUE THREAD

**Issue by crhisnoriega** [appreciated/vaadin-app-layout#110]
Hi, I wanto to use DatePicker inside App Layout, it is possivel?.

Thanks.

**Comment by appreciated** [comment]
Never tried it so I cannot tell. This addon was never optimized it for the use with Touchkit but it might still work. 

What exactly do you mean by this?
> use DatePicker inside App Layout

* a DatePicker in the Sliding Menu of the App Layout?
* a DatePicker in the App Bar of the App Layout?
* a DatePicker inside a View that is presented inside the App Layout?

**Comment by crhisnoriega** [comment]
Hi!, for now, use the DataPicker inside a View... but another options aren't discarded.

Thanks.

**Comment by appreciated** [comment]
Would you mind putting a demo together? I have rather less experiance with Touchkit. I think there will only need to be some CSS necessary to fix eventual issues.

**Comment by appreciated** [comment]
closing due to no response reopen if relevant again
