### ISSUE TITLE
vaadin spring-boot bower components problem

### ISSUE THREAD

**Issue by rodrifmed** [appreciated/vaadin-app-layout#111]
Hi,

I was using the app-layout fine with jetty and guice, but I needed to change the application to start to use vaadin spring-boot, and now the app-layout addon is not more working.

What is happening is similar to this picture that remarkNS posted in [https://github.com/appreciated/vaadin-app-layout/issues/4](https://github.com/appreciated/vaadin-app-layout/issues/4). 
I saw in the sources of the project in the chrome inspect and the folder bower_components is not there.

Should I change my pom to be similar to app-layout-demo? with the profile web-components?

**Comment by deyaeddin** [comment]
Hi @rodrifmed 
Yes, you should have the profile web-components in your project,  it's the part where we package all the polymer-welcomeness dependencies. As you see we are using the plugin eirslett .

Or you can take the plugins to your main build in maven, but that would be an overload (on each time you build your project).

**Comment by rodrifmed** [comment]
Thanks @deyaeddin , I will try here, but I'm not understanding why I should put this plugins in maven, because when I was usign guice and jetty I didn't need to do this, I only put the app-layout dependency and it was working fine.

**Comment by deyaeddin** [comment]
Most probably because of Spring Boot uses an alternative way to map servletContext path.

**Comment by rodrifmed** [comment]
Still not working
![inspect](https://user-images.githubusercontent.com/2883969/38825586-7c7b7bc4-4183-11e8-90f0-5fe4c07b374c.png)

**Comment by rodrifmed** [comment]
SOLVED!

The problem was with this dependency, somehow because this dependency the bower_components was not loading in the server

```
<dependency>
	<groupId>com.vaadin</groupId>
	<artifactId>vaadin-board-precompiled</artifactId>
	<version>1.0.0</version>
</dependency>

```
So I didn't need to copy the build-tools folder

**Comment by deyaeddin** [comment]
Great.
I think you should use <scope>provided</scope>

**Comment by newUserRepo** [comment]
Hello,

I have the same error with Springboot, is it necessary to add the dependency of vaadin board, so that it works? :
