### ISSUE TITLE
Align logo to center

### ISSUE THREAD

**Issue by henriquemeira** [appreciated/vaadin-app-layout#113]
How to align logo to center?

Based on sample code, the MenuHeader is the element where is the logo image and text.
...
.add(new MenuHeader("Version 0.9.23", new ThemeResource("logo.png")), HEADER)
..

Can I set alignment as center to it?

**Comment by deyaeddin** [comment]
You can add this to your theme:
`  .app-layout-menu-header-element{
    text-align: center;
  }
  .app-layout-menu-header-title{
    text-align: center;
    font-size: $v-font-size--h2;
  }`

**Comment by henriquemeira** [comment]
Works fine.

Thanks a lot.
