### ISSUE TITLE
Missing path parameter for menu

### ISSUE THREAD

**Issue by kamuffe** [appreciated/vaadin-app-layout#114]
I tried to migrate to 0.9.22 but there are several issues with that version.

1)
path argument missing for add method. I cannot give the layout the path for the navigator as it was possible with prior versions or is still possible with submenus. Our urls are not localized. A path string maps to Spring view. Please add path parameter to add methods again.

2) NPE
An NPE occurs in com.github.appreciated.app.layout.annotations.AnnotationHelper.getAnnotationOptionally(Class<? extends View>, Class<A>) if I have views with no MenuCaption annotation. I gave the localized caption to the add method (mentioned above) and not via the annotation. so I don't want to mark all my view with this annotation.

Therefore I have to init the Layout as follows:

```
appLayoutMenubar = AppLayout.getCDIBuilder( Behaviour.LEFT_RESPONSIVE )
		.withViewProvider( null )
		.withNavigationElementInfoProducer( null ).withCaptionInterceptor( null )
		.withTitle( title )
...
		.withNavigator( navigatorProducer )
```

This is boilerplate code and should be avoided if the arguments are optional.

Why I have to pass a SpringViewProvider when I pass a NavigatorProducer which does all what I want?
NavigationElementInfoProducer seems a bit over-engineered because all infos for a navigation element are given by the add method.

**Comment by kamuffe** [comment]
I Fixed the first issue by giving an InfoProvider. But then The caption is not correct because I won't use the annotations. I give the localized caption to the add method. Solved this by adding a check if caption is already set, don't reset it by the InfoProvider in com.github.appreciated.app.layout.builder.elements.NavigatorNavigationElement.refreshInfo().

**Comment by appreciated** [comment]
> path argument missing for add method. I cannot give the layout the path for the navigator as it was possible with prior versions or is still possible with submenus. Our urls are not localized. A path string maps to Spring view. Please add path parameter to add methods again.

Hmm seems like I cut out a feature due to refactoring. I wasn't aware that SpringNavigator allows you to add new views in the Fly to the Navigator. Sorry for that 😞. 

For the 2nd issue, please open another one and tell me why you didn't use the `withCaptionInterceptor` to replace your I18N key with the localized value? The InfoProvider is only meant to pull the information from the Annotations. 

> Why I have to pass a SpringViewProvider when I pass a NavigatorProducer which does all what I want?

You should be able to do exactly that:

```
    @Autowired
    SpringViewProvider viewProvider;
    
    @Autowired
    SpringNavigator navigator;

    public void init(VaadinRequest request) {
        setContent(AppLayout.getCDIBuilder(Behaviour.LEFT_RESPONSIVE_HYBRID)
                .withNavigator(components -> {
                    navigator.init(this,components);
                    navigator.addProvider(viewProvider);
                    return navigator;
                })
```

**Comment by appreciated** [comment]
@kamuffe did Version 0.9.23 fix the issue?
