### ISSUE TITLE
Configure cache

### ISSUE THREAD

**Issue by bladem** [appreciated/vaadin-app-layout#116]
There are the possibility to configure a cache to store in memory the view clicked?

thank you so much.

**Comment by appreciated** [comment]
The addon doesn't have a feature to do this automatically so you will have to do it yourself. Simply use    [`Navigator::addViewChangeListener`](https://vaadin.com/api/8.0.0/com/vaadin/navigator/Navigator.html#addViewChangeListener-com.vaadin.navigator.ViewChangeListener-) and cache it.
