### ISSUE TITLE
Notification Style corrupt

### ISSUE THREAD

**Issue by kamuffe** [appreciated/vaadin-app-layout#119]
The styles of notifications are corrupt with version 0.9.23. Please find screenshot

**Comment by kamuffe** [comment]
<img width="333" alt="applayoutnotificationstyles" src="https://user-images.githubusercontent.com/5285367/40110523-74c8954e-5900-11e8-8a80-f60d0e92e193.png">

**Comment by appreciated** [comment]
Hmm this is weird I can't remember doing any changes in the styles, mabe the newer Vaadin version? I will need to investigate this.

**Comment by kamuffe** [comment]
We can have I screensharing session if this is usefull for you.

**Comment by appreciated** [comment]
Cannot reproduce with current version, can you confirm for 1.0.0?

**Comment by kamuffe** [comment]
This issue still persist with app-layout 1.0.0

**Comment by appreciated** [comment]
So can when could we setup a screensharing session?

**Comment by kamuffe** [comment]
Could you give me your slack name again? then we could do it via slack?

**Comment by appreciated** [comment]
> Could you give me your slack name again? then we could do it via slack?
https://join.slack.com/t/vaadin-app-layout/shared_invite/enQtMjczMTM5NjU0Mjk0LTljM2Y5YTFjMWY0ZDhmOWU3Njc4Yjk5NTI4ZTQ3MjY5YWU2ZGI4NjI1ZWMyOWIzYjBhM2VjMDI1ZjdkYTM5MjU
