### ISSUE TITLE
Use CDIViews

### ISSUE THREAD

**Issue by joa44741** [appreciated/vaadin-app-layout#12]
Hey, I like your layout very much.
But I'm not able to use CDIViews for navigation.
Is it possible to use CDIViews?

**Comment by appreciated** [comment]
Checkout [Commit 83b649be89dd1d95cc1847fb86b6c0e669e7bf17](https://github.com/appreciated/vaadin-app-layout/commit/83b649be89dd1d95cc1847fb86b6c0e669e7bf17)

**Comment by appreciated** [comment]
I have made added changes to the current api, please check if it works now, If it doesn't reopen this issue please
