### ISSUE TITLE
Programatically toggle

### ISSUE THREAD

**Issue by kamuffe** [appreciated/vaadin-app-layout#122]
Hi.

Is it possible to toggle the app-layout menu programatically?

Usecase:
Menu should be closed all time. User have to open it manually on mobile devices to navigate and afterwards it should be closed again to save space on mobile devices.

This should be configurable feature because on desktops the left menu can be displayed all the time.

Thanks a lot in advance :)

**Comment by appreciated** [comment]
Yes there is! Check #120 😉
