### ISSUE TITLE
Exception: Cannot add a null view provider on spring-cdi example

### ISSUE THREAD

**Issue by JDo-Jimenez** [appreciated/vaadin-app-layout#125]
Hi, congratulations for the addon, it looks very nice.
Here my issue, I'm trying to isolate the example /app-layout-examples/annotation-based/spring-cdi/ in a single project but when  I run the project on server (Tomcat v9.0) I get the exception attached below. I'm trying to figured it out for two days but no success. Does anyone  knows what is wrong? I've attached  Exception log, MyUI.java (same as the spring-cdi example, and also ExampleView.java, Main.java, View1.java, ...) and pom.xml.
Thanks very much.

Exception:
> Jun 19, 2018 1:13:59 PM com.vaadin.server.DefaultErrorHandler doDefault
> SEVERE: 
> java.lang.IllegalArgumentException: Cannot add a null view provider
> 	at com.vaadin.navigator.Navigator.addProvider(Navigator.java:1133)
> 	at com.github.appreciated.app.layout.builder.AppLayoutConfiguration.build(AppLayoutConfiguration.java:131)
> 	at com.github.appreciated.app.layout.builder.AbstractAppLayoutBuilderBase.build(AbstractAppLayoutBuilderBase.java:293)
> 	at com.example.MenuAppLayout_test.MyUI.init(MyUI.java:78)
> 	at com.vaadin.ui.UI.doInit(UI.java:771)
> 	at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:218)
> 	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:76)
> 	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
> 	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1601)
> 	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:412)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1385)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:748)

pom.xml
`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>MenuAppLayout_test</artifactId>
	<packaging>war</packaging>
	<version>1.0-SNAPSHOT</version>
	<name>MenuAppLayout_test</name>

	<prerequisites>
		<maven>3</maven>
	</prerequisites>

	<properties>
		<vaadin.version>8.4.3</vaadin.version>
		<vaadin.plugin.version>8.4.3</vaadin.plugin.version>
		<jetty.plugin.version>9.3.9.v20160517</jetty.plugin.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		
		<vaadin.widgetset.mode>local</vaadin.widgetset.mode>
	</properties>
	
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.8.RELEASE</version>
        <relativePath/> 
	</parent>

	<repositories>
		<repository>
			<id>vaadin-addons</id>
			<url>http://maven.vaadin.com/vaadin-addons</url>
		</repository>
	</repositories>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-bom</artifactId>
				<version>${vaadin.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.0.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-server</artifactId>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-push</artifactId>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-client-compiled</artifactId>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-themes</artifactId>
		</dependency>
		
		<dependency>
		   <groupId>com.github.appreciated</groupId>
		   <artifactId>app-layout-addon</artifactId>
		   <version>0.9.23</version>
		</dependency>	
		
		<dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
</dependency>
		
	</dependencies>

	<build>
	
	    <resources>
            <resource>
                <directory>src/main/webapp</directory>
            </resource>
        </resources>
	
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.2.0</version>
				<configuration>
					<failOnMissingWebXml>false</failOnMissingWebXml>
					
					<packagingExcludes>WEB-INF/classes/VAADIN/widgetsets/WEB-INF/**</packagingExcludes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-maven-plugin</artifactId>
				<version>${vaadin.plugin.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>update-theme</goal>
							<goal>update-widgetset</goal>
							<goal>compile</goal>
							
							<goal>compile-theme</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			
			<plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.0.0</version>
				
				<configuration>
					<filesets>
						<fileset>
							<directory>src/main/webapp/VAADIN/themes</directory>
							<includes>
								<include>**/styles.css</include>
								<include>**/styles.scss.cache</include>
							</includes>
						</fileset>
					</filesets>
				</configuration>
			</plugin>
			
			<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.0.1</version>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

			
			<plugin>
				<groupId>org.eclipse.jetty</groupId>
				<artifactId>jetty-maven-plugin</artifactId>
				<version>${jetty.plugin.version}</version>
				<configuration>
					<scanIntervalSeconds>2</scanIntervalSeconds>
				</configuration>
			</plugin>			
		</plugins>
	</build>

	<profiles>
		<profile>
			
			<id>vaadin-prerelease</id>
			<activation>
				<activeByDefault>false</activeByDefault>
			</activation>

			<repositories>
				<repository>
					<id>vaadin-prereleases</id>
					<url>http://maven.vaadin.com/vaadin-prereleases</url>
				</repository>
				<repository>
					<id>vaadin-snapshots</id>
					<url>https://oss.sonatype.org/content/repositories/vaadin-snapshots/</url>
					<releases>
						<enabled>false</enabled>
					</releases>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
				</repository>
			</repositories>
			<pluginRepositories>
				<pluginRepository>
					<id>vaadin-prereleases</id>
					<url>http://maven.vaadin.com/vaadin-prereleases</url>
				</pluginRepository>
				<pluginRepository>
					<id>vaadin-snapshots</id>
					<url>https://oss.sonatype.org/content/repositories/vaadin-snapshots/</url>
					<releases>
						<enabled>false</enabled>
					</releases>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
				</pluginRepository>
			</pluginRepositories>
		</profile>
	</profiles>

</project>
`

 MyUI:
`@Push(transport = Transport.LONG_POLLING)
@PushStateNavigation
@SpringUI
@Viewport("width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no")
@Theme("demo")
@Title("App Layout Demo")
public class MyUI extends UI {

    DefaultNotificationHolder notifications = new DefaultNotificationHolder();
    DefaultBadgeHolder badge = new DefaultBadgeHolder();

    @Autowired
    SpringViewProvider viewProvider;

    public void init(VaadinRequest request) {
        setContent(AppLayout.getCDIBuilder(Behaviour.LEFT_RESPONSIVE_HYBRID)
                .withViewProvider(() -> viewProvider)
                .withTitle("App Layout Spring CDI Example")
                .addToAppBar(new AppBarNotificationButton(notifications, true))
                .withDesign(AppLayoutDesign.MATERIAL)
                .add(new MenuHeader("Version 0.9.23", new ThemeResource("logo.png")), HEADER)
                .add(badge, View1.class)
                .add(CDISubmenuBuilder.get("My Submenu", VaadinIcons.PLUS)
                        .add(View2.class)
                        .add(View3.class)
                        .add(View4.class)
                        .build())
                .add(View5.class)
                .add(View6.class)
                .build());
    }
    @WebServlet(value = "/*", asyncSupported = true)
    @VaadinServletConfiguration(productionMode = false, ui = MyUI.class)
    public static class Servlet extends VaadinServlet {
    }
}`

**Comment by appreciated** [comment]
Yeah this is a known issue in 0.9.23. Just use 0.9.22. Until I release 1.0.0.

**Comment by appreciated** [comment]
@JDo-Jimenez Does this issue only occure on Tomcat?

Since when doing as you did:
```
@Autowired
SpringViewProvider viewProvider;
```
`viewProvider` should be initalized already when building the menu.

**Comment by JDo-Jimenez** [comment]
I tried also with apache-tomee-webprofile-7.0.2 and I've got same result. Anyways I have to use Vaadin CDI Addon instead of Vaadin Spring. 
 I made some changes to run with Vaadin CDI Addon but I've got a new issue (if you want me to create a new github issue just let me know), I can see the left menu on the browser but it doesn't change the views when I click on the menu elements, it always keep view1. 
I've created my own NavigationElementInfoProvider (DefaultCDINavigationElementInfoProducer) as you say in the comments , but I wasn't sure how to do so, I've just created this class:

```
public class DefaultCDINavigationElementInfoProducer extends BasicViewInfoProducer{

    public DefaultCDINavigationElementInfoProducer() {
        withViewNameProvider(info -> Optional.ofNullable(""));
    }
}
```
Could you please give me some clue about the creation of NavigationElementInfoProvider. Thanks you very much.
Here my new UI code:

```
@Push(transport = Transport.LONG_POLLING)
@PushStateNavigation
@CDIUI("")
@Viewport("width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no")
@Theme("demo")
@Title("App Layout Demo")
public class MyUI extends UI {

    DefaultNotificationHolder notifications = new DefaultNotificationHolder();
    DefaultBadgeHolder badge = new DefaultBadgeHolder();

    @Inject
    CDIViewProvider viewProvider;
    
    public void init(VaadinRequest request) {
        setContent(AppLayout.getCDIBuilder(Behaviour.LEFT_RESPONSIVE_HYBRID)
                .withViewProvider(() -> viewProvider)
                .withNavigationElementInfoProducer(new DefaultCDINavigationElementInfoProducer())
                .addToAppBar(new AppBarNotificationButton(notifications, true))
                .withDesign(AppLayoutDesign.MATERIAL)
                .add(new MenuHeader("Version 0.9.23", new ThemeResource("logo.png")), HEADER)
                .add(badge, View1.class)
                .add(CDISubmenuBuilder.get("My Submenu", VaadinIcons.PLUS)
                        .add(View2.class)
                        .add(View3.class)
                        .add(View4.class)
                        .build())
                .add(View5.class)
                .add(View6.class)
                .build());
    }
}
```

**Comment by JDo-Jimenez** [comment]
I'm not using Spring, I'm using Vaadin CDI Addon. I was asking how to implement my own NavigationElementInfoProvider for Vaadin CDI Addon, finally I figured this out  researching your DefaultSpringNavigationElementInfoProducer implementation, I'll post my NavigationElementInfoProvider for Vaadin CDI because maybe it could help someone in the future.
Thanks.
Regards.

```
public class DefaultCDINavigationElementInfoProducer extends BasicViewInfoProducer{

    public DefaultCDINavigationElementInfoProducer() {
        withViewNameProvider(info -> getCDIViewName(info));
    }
    private Optional<String> getCDIViewName(Class<? extends View> aClass) {
        Annotation a = Arrays.stream(aClass.getAnnotations())
                .filter(annotation -> annotation.annotationType().getName().equals("com.vaadin.cdi.CDIView"))
                .findFirst()
                .get();
        String result = null;
        try {
            Method m = a.getClass().getMethod("value");
            result = (String) m.invoke(a);
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        }
        return Optional.ofNullable(result);
    }
}
```

**Comment by appreciated** [comment]
Your implementation of BasicViewInfoProducer for VaadinCDI will be added as `DefaultVaadinCdiNavigationElementInfoProducer`. Thanks for your work!
