### ISSUE TITLE
Questions about view loads and responsive view content

### ISSUE THREAD

**Issue by jable8** [appreciated/vaadin-app-layout#126]
Hello, thanks for your work. I'm pretty new in vaadin and I have some questions. 
How is the loading process of a view? I mean, when a view is changed, all the screen is loaded (menu + view) or just the view?
I know you can create a responsive menu whit this addon but, Would be possible to create a responsive view content?
Thank you very much. 
Kind regards.

**Comment by appreciated** [comment]
> How is the loading process of a view? I mean, when a view is changed, all the screen is loaded (menu + view) or just the view?

Just the View. 

> I know you can create a responsive menu whit this addon but, Would be possible to create a responsive view content?

Classic single responsibility principle, the view itself needs to care for its content to be ordered correctly. And the content again for its content. Checkout [responsive-layout](https://vaadin.com/directory/component/responsive-layout) or the [CssLayout](https://vaadin.com/docs/v8/framework/layout/layout-csslayout.html).
