### ISSUE TITLE
Side menu ie11 problems 

### ISSUE THREAD

**Issue by bekirmavus** [appreciated/vaadin-app-layout#128]
versiyon 1.0.0
vaadin versiyon 8.4.3

ie version
![ie version](https://user-images.githubusercontent.com/6548558/42016041-96adcad4-7ab2-11e8-91ee-9afedbebd7a6.png)

Behaviour.LEFT_OVERLAY
![bug3](https://user-images.githubusercontent.com/6548558/42015991-61b8fede-7ab2-11e8-9c85-23e25ffdc214.gif)

Behaviour.LEFT_RESPONSIVE
![bug2](https://user-images.githubusercontent.com/6548558/42016011-7427a61a-7ab2-11e8-8bf3-fe92fa34ac20.gif)

**Comment by appreciated** [comment]
Same with this issue: 
> Can you please describe what isn't working?

**Comment by bekirmavus** [comment]
at Behaviour.LEFT_OVERLAY after click the menu item, side menu get sticky and moves by mouse movement

 at Behaviour.LEFT_RESPONSIVE after click the menu item, side menu fade outs. when we click menu button, at first click view resize and fill the screen, at second click side menu opens.

by the way, this is a realy good theme thank you for that

**Comment by appreciated** [comment]
So I fixed now some issues under IE 11, but I wasn't able to reproduce the following issue:
> at Behaviour.LEFT_RESPONSIVE after click the menu item, side menu fade outs. when we click menu button, at first click view resize and fill the screen, at second click side menu opens.

**Comment by bekirmavus** [comment]
we found that this is not a bug. it is a problem about our application

> at Behaviour.LEFT_RESPONSIVE after click the menu item, side menu fade outs. when we click menu button, at first click view resize and fill the screen, at second click side menu opens.
