### ISSUE TITLE
Can't use the add-on in OSGi

### ISSUE THREAD

**Issue by alexweirig** [appreciated/vaadin-app-layout#13]
Hello,

I'd like to use the add-on in an OSGi Vaadin application but there are 2 issues:
1) the jar file is not a valid OSGi bundle since MANIFEST.MF doesn't contain any Import-Package and Export-Package statements
2) once I transformed the jar into a bundle using the bundle fails because of 
http://localhost:8181/vaadin-8.1.5/VAADIN/bower_components/webcomponentsjs/webcomponents-lite.js could not be loaded.

So there bower_components seem to be missing ... not sure where they should be coming from?

Alex

**Comment by appreciated** [comment]
Hi,
To answer your question, as mentioned in the [Build and Running](https://github.com/appreciated/vaadin-app-layout#building-and-running-demo) it is necessary to install bower components before using this addon. I have not pushed them to the repo because these components are "only a dependency".  
I haven't got much experience with OSGi so you have to tell me if the Bug is resolved with the changes you made to the manifest file.

**Comment by appreciated** [comment]
Since I would like to release the update tonight since I'm tomorrow gone for a week it would be nice if we could get it working pretty soon 😓

**Comment by alexweirig** [comment]
Hi Jonathan, 

Thanks for the answer. 

I don’t know this bower stuff, but from what I see this seems to be Javascript/CSS stuff, so in order for this to work, one would have to create an OSGi bundle with these files and register this bundle with the http service in the OSGi runtime. 

I’m also gone next week for a conference so probably I won’t be able to work on this. 

I guess you can still release the new version with the correct MANIFEST.MF file. The bower stuff is the off-topic... 

--- 

Schéin Gréiss, 
Mit freundlichen Grüßen, 
Meilleures salutations, 
Kind regards, 
Alex Weirig 
Responsable Technique 

Ville de Luxembourg - Centre Technolink 
2, rue Charles de Tornaco 
L - 2623 LUXEMBOURG 
alex.weirig@technolink.lu 

Tel: +352 4796 - 6127 
Fax: +352 42 88 81 
www.technolink.lu

**Comment by appreciated** [comment]
Since I upload the jar/bundle with the dependencies it should fine or?

**Comment by appreciated** [comment]
I have made changes to the Manifest file, please check if it works, If it doesn't reopen this issue

**Comment by alexweirig** [comment]
Hi,

I just downloaded you latest version and got it to work (somehow) ...
The problem is indeed the static content that has to be somehow served. I have copied the content into my UI bundle (next to the theme) and then created a servlet to serve the content

```
@Component(service = Servlet.class)
public static class TechnolinkAdministrationBowerServlet extends HttpServlet {
		private static final long serialVersionUID = 1L;
		
		@Reference private HttpService httpService;
		
		@Activate
		public void activate() throws Exception {
			if (httpService != null) {
				httpService.registerResources("/vaadin-8.1.5/VAADIN", "/VAADIN", null);
			}
		}
}
```
and now it works.

I wonder if I shouldn't create a separate bundle for these files rather than putting everything into the main UI bundle.

Regards,

Alex

**Comment by appreciated** [comment]
Since I have no experience with OSGi I can't tell if this is the correct way to do so. But still I wonder why you are using a simple HTTPServlet instead of a VaadinServlet which serve the needed file on its own.

**Comment by alexweirig** [comment]
I think the Vaadin servlet is linked to a UI and we already have the standard VaadinServlet for the UI and the associated theme and widgetset. 

That’s why I plan to create a dedicated bundle. 

I also noticed that the MANIFEST.MF in the latest release still doesn’t have the import and export packages, it looks like the pom.xml doesn’t contain the my changes... I noticed this because I get NoSuchMethod exceptions on certain statements from your sample code.... I need to figure out what is going on. 

--- 

Schéin Gréiss, 
Mit freundlichen Grüßen, 
Meilleures salutations, 
Kind regards, 
Alex Weirig 
Responsable Technique 

Ville de Luxembourg - Centre Technolink 
2, rue Charles de Tornaco 
L - 2623 LUXEMBOURG 
alex.weirig@technolink.lu 

Tel: +352 4796 - 6127 
Fax: +352 42 88 81 
www.technolink.lu

**Comment by appreciated** [comment]
Yes true I removed the POM part but therefore updated the [Manifest file](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/assembly/MANIFEST.MF).

**Comment by alexweirig** [comment]
Not sure, these lines don’t seem to show up in the final MANIFEST. maven sometimes overwrites the file with the one it produces in the jar building process. I think having read there is an option to tell maven to include a provided file and not the one it generates. 

--- 

Schéin Gréiss, 
Mit freundlichen Grüßen, 
Meilleures salutations, 
Kind regards, 
Alex Weirig 
Responsable Technique 

Ville de Luxembourg - Centre Technolink 
2, rue Charles de Tornaco 
L - 2623 LUXEMBOURG 
alex.weirig@technolink.lu 

Tel: +352 4796 - 6127 
Fax: +352 42 88 81 
www.technolink.lu

**Comment by appreciated** [comment]
The manifest file in the downloaded Version look now like this
```
Manifest-Version: 1.0
Vaadin-Package-Version: 1
Vaadin-Addon: app-layout-addon-0.9.4.jar
Vaadin-License-Title: Apache License 2.0
Implementation-Vendor: appreciated
Implementation-Title: App Layout Add-on
Implementation-Version: 0.9.4
Export-Package: com.github.appreciated.app.layout.*
Import-Package: *
```

Please check if the issues with OSGi are now fixed

**Comment by alexweirig** [comment]
Hi,

sorry for the long delay, I could only work on this today.

As far as I could see, this working fine now.

Thank you very much.

**Comment by alexweirig** [comment]
Hello,

how do you build the addon in order to have the correct MANIFEST.MF being added to the jar.

I've created a fork to fix an issue with an NPE in OSGi and when I build the code (mvn clean install) I don't get the OSGi MANIFEST.MF on the basic maven MANIFEST.MF.

Thanks

**Comment by appreciated** [comment]
> how do you build the addon in order to have the correct MANIFEST.MF being added to the jar.
The `maven-assembly-plugin` builds the addon on every `install` goal. I only upload the resulting zip file to the Vaadin Directory the zip.

**Comment by alexweirig** [comment]
That's strange ... this is what I get when I do an mvn clean install on master....

Manifest-Version: 1.0
Vaadin-License-Title: Apache License 2.0
Vaadin-Stylesheets: VAADIN/addons/app-layout/app-layout.scss
Implementation-Title: App Layout Add-on
Implementation-Version: 0.9.5
Archiver-Version: Plexus Archiver
Built-By: aweirig
Implementation-Vendor-Id: com.github.appreciated
Class-Path: vaadin-server-8.1.5.jar vaadin-sass-compiler-0.9.13.jar sa
 c-1.3.jar flute-1.3.0.gg2.jar vaadin-shared-8.1.5.jar jsoup-1.8.3.jar
  gentyref-1.2.0.vaadin1.jar vaadin-client-compiled-8.1.5.jar vaadin-p
 ush-8.1.5.jar atmosphere-runtime-2.4.11.vaadin2.jar vaadin-slf4j-jdk1
 4-1.6.1.jar vaadin-themes-8.1.5.jar prettytime-4.0.1.Final.jar
Implementation-Vendor: appreciated
Vaadin-Package-Version: 1
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_131

so all the Import-Package and Export-Package from the assembly/MANIFEST.MF are missing?

**Comment by appreciated** [comment]
Have you taken the generated manifest from the zip?

**Comment by appreciated** [comment]
Have you checked the changelog in Vaadin 8.1.6? 
> OSGi bundle manifests of Vaadin Framework JARs no longer export /VAADIN, and there are new mechanisms for publishing static resources for OSGi

There seem to be interesting machanics for you.

**Comment by alexweirig** [comment]
Hi,
thanks for the update.

I think that note has been there since 8.1.0? I will check what’s new in 8.1.6 as I have an open ticket regarding OSGi DS support in Vaadin UI classes.

**Comment by alexweirig** [comment]
Hi,

I just wanted to let you know that I'm now able to use the add-on in my OSGi application.

Unfortunately, when I click on an navigation item in the list, I don't see the view component being displayed in the screen part.

No stacktraces, no errors.

This is how I create the drawer:
```
	private void createDrawer(final Behaviour behaviour) {
		removeAllComponents();
		
		AppLayoutBuilder appLayoutBuilder = AppLayoutBuilder.get()
				.withBehaviour(behaviour)
				.withTitle("Technolink Administration")
				.addToAppBar(getVariantCombo(behaviour))
				.addToAppBar(new NotificationAppBarButton(notifications))
				.withViewNameInterceptor(new DefaultViewNameInterceptor())
				.withDesign(AppBarDesign.MATERIAL)
	            .add(new MenuHeader("Technolink", "Version 0.0.1", new ThemeResource("logo.png")), AppLayoutBuilder.Position.HEADER)
	            ;
		
		modules.forEach(module -> appLayoutBuilder.add(module.getTitle(), module.getIcon(), module.getViewClassName()));
		//modules.forEach(module -> System.out.println("module = " + module.getTitle()));

		appLayoutBuilder.withDefaultNavigationView(modules.get(0).getViewClassName());

		drawer = appLayoutBuilder.build();

		addComponent(drawer);
	}
```


![screen shot 2017-10-27 at 12 19 29](https://user-images.githubusercontent.com/3875989/32099603-2f42d760-bb11-11e7-8a47-2236eb8b162d.png)
![screen shot 2017-10-27 at 12 19 32](https://user-images.githubusercontent.com/3875989/32099604-2f59f62a-bb11-11e7-90a9-9f478afbb119.png)

Here's the content of the Welcome module:
```
@Component(
		immediate = true
		, service = ApplicationModule.class
)
public class WelcomeModule extends VerticalLayout implements ApplicationModule {
	private static final long serialVersionUID = 1L;

	@Override
	public String getTitle() {
		return "Welcome";
	}
 
	@Override
	public Resource getIcon() {
		return VaadinIcons.HOME;
	}

	public Class<? extends View> getViewClassName() {
		return WelcomeModule.class;
	}
	
	@Activate
	private void init() {
		System.out.println("In WelcomeModule init");
		setMargin(false);
		setSizeFull();
		
		HorizontalLayout searchLayout = new HorizontalLayout();
		searchLayout.setWidth("100%");
		
		TextField searchField = new TextField();
		
		Button search = new Button();
		search.setCaption("Search");
		search.addStyleName(TechnolinkTheme.BUTTON_ICON_ONLY);
		search.setIcon(VaadinIcons.SEARCH);
		
		searchLayout.addComponents(searchField, search);
		
		addComponents(searchLayout);
	}
	
}
```

Do you have any idea what can cause this problem?

Thanks in advance

**Comment by appreciated** [comment]
This is only a bug in the demo not a problem within the Addon itself. 
Switching out the whole layout at runtime requires some additional error handling and view restoring ... which I was too lazy to dig in since the demo was only meant to show off the different [behaviors](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/java/com/github/appreciated/app/layout/behaviour/Behaviour.java#L6). 
I probably should still the issue since obviously irritates some users 😉. 
To get rid of this bug simply use the code example from the [Directory](https://vaadin.com/directory/component/app-layout-add-on) beforehand I recommend to decide which behavior you want to use.

**Comment by alexweirig** [comment]
I found the problem.

I had created the layout for the different views when the OSGi runtime activates my bundle when I create the layout for the views in the constructor of the view it works.

I guess somehow the navigation to the views creates a new instance...

Now it's working
