### ISSUE TITLE
Two menus in same application

### ISSUE THREAD

**Issue by rodrifmed** [appreciated/vaadin-app-layout#133]
Is possible to use app-layout addon like jira layout, with two menus ?

**Comment by rodrifmed** [comment]
but this will not override the first menu?

**Comment by appreciated** [comment]
> but this will not override the first menu?
How could it if you provide it in your very own view?

**Comment by rodrifmed** [comment]
I tried here but is not working properly, maybe because I'm using spring.

**Comment by appreciated** [comment]
That's probably because you tried to warp an app-layout inside an app-layout, which I did not mean.
> simply provide the second **menu** in your own view.
Your very own menu (menu ~= VerticalLayout with Buttons) inside your view. Not an app-layout.
