### ISSUE TITLE
Missing Internet Explorer support

### ISSUE THREAD

**Issue by appreciated** [appreciated/vaadin-app-layout#134]
Currently the Vaadin 10+ version does not support the Internet Explorer since the transpilation of the PolymerTemplates does not seem to work.

**Comment by cedricaebi** [comment]
how does it behave then in IE11? Is it just a white page or does the menu look weird?

**Comment by appreciated** [comment]
This
> or does the menu look weird

**Comment by cedricaebi** [comment]
ok so I have the same problem. I'm using Vaadin 13. The menu under IE11 uses the material theme despite explicitly saying it should use the Lumo theme, and has no margin for the items no appbar etc. 

I sadly have to support IE11 and would be glad for it to get ported :)

**Comment by appreciated** [comment]
Hmm that behavior sounds wierd but since ie 11 currently isn't supported these things may happen. Since I have currently many other things that have a higher priority to me, I cannot give you any timeframe for this feature.

**Comment by cedricaebi** [comment]
Does it work for Edge? Because the sidemenu with LEFT_RESPONSIVE looks and works fine. But the content of the view is just a white page

**Comment by appreciated** [comment]
>Does it work for Edge? Because the sidemenu with LEFT_RESPONSIVE looks and works fine. But the content of the view is just a white page
Yes Edge is supported, and I currently have no idea why this happens, will release a hotfix asap.

**Comment by appreciated** [comment]
@bishwajitcse the issue you describe was fixed by #236

**Comment by bishwajitcse** [comment]
> @bishwajitcse the issue you describe was fixed by #236
Ok. Thank. I am checking again. :)
