### ISSUE TITLE
Is vaadin-app-layout 1.0.2 ready for Vaadin 10?

### ISSUE THREAD

**Issue by henriquemeira** [appreciated/vaadin-app-layout#136]
I'm starting a new project with Vaadin 10 and would to know if I must to use the 1.0.2 or 2.0.0 version.

I'm ask it because, for example the AppLayoutRouterLayout.class is a class that exists only in 2.0.0.

**Comment by deyaeddin** [comment]
Version 2.x.x  is for Vaadin 10.xx 
Version 1.x.x is for Vaadin 8.x.x 

So, you should use version 2.0.0 for your project.

Good luck with your project

**Comment by henriquemeira** [comment]
Thank you.
Great jobs!
