### ISSUE TITLE
Stop Using overridable methods in constructor

### ISSUE THREAD

**Issue by appreciated** [appreciated/vaadin-app-layout#138]
[It is prohibited](https://stackoverflow.com/questions/3404301/whats-wrong-with-overridable-method-calls-in-constructors)

**Comment by svenruppert** [comment]
refactoring in progress..

**Comment by DonAscon** [comment]
Isnt there already a fix merged from #144 ?

**Comment by appreciated** [comment]
@DonAscon Partly since there still is refactoring to be done to support the CDI Framworks
