### ISSUE TITLE
App Layout with Vaadin Board Addon issue

### ISSUE THREAD

**Issue by lipisak** [appreciated/vaadin-app-layout#139]
I have combined App Layout with Vaadin boards. After successful widgetset compilation the main part of UI is missing. Only menu is Visible (incomplete) and no detail part.

I am currently using LEFT_RESPONSIVE_SMALL_NO_APP_BAR behavior.

I can send you "very basic" code which shows this issue. But I guess simple AppLayout (1.0.2) with Vaadin Board addon will do the same. Can you check this please?

**Comment by appreciated** [comment]
This sounds wierd. Would you mind joining me on slack so we can investigate it together?

**Comment by lipisak** [comment]
I can send you a basic maven project, which confirms this. it's simple vaadin app with layout and boards plugin. is it acceptable for you?

**Comment by appreciated** [comment]
Thank you. The Problem is that I don't have a Vaadin Board License to check it out. I contacted Vaadin about this. Let's see what they'll say.

**Comment by lipisak** [comment]
Thank you for your answer. That would help us a lot. As it is kind a crucial for our project to have Board and your layout is essential part of it too. Isn't there any kind of "Testing period licence"?

**Comment by appreciated** [comment]
Just to let you know I might be getting a license today. 
> Isn't there any kind of "Testing period licence"? 
Yes there are but mine are already expired. 
Surly this could be done but I think this is not legal to do so. 
I prefer doing it with the direct support of Vaadin I hope you can understand this.

**Comment by appreciated** [comment]
We got two issues. 

1. Resulting theme is way too small. 
2. [The HTML Imports Annotations do not seem to work in your example](https://github.com/appreciated/vaadin-app-layout/blob/dev-8.x/app-layout-addon/src/main/java/com/github/appreciated/app/layout/behaviour/left/LeftResponsiveSmallNoAppBar.java). Which is why the app-layout Webcomponent looks as it does currently. I need to further investigate this.

**Comment by appreciated** [comment]
This is super wierd, you might be onto something big here. 
You can even put the HTML imports into the UI class and they will be ignored. 
This might be a [Vaadin Spring](https://github.com/vaadin/spring/) issue.

**Comment by appreciated** [comment]
There seems to be issue either a Vaadin Spring or with your project setup.
The follwoing is not supposed to happen:
![issue](https://user-images.githubusercontent.com/1729845/45481230-51f15200-b74b-11e8-805d-22cbceb497ba.PNG)
 Since I'm not a Vaadin Spring expert you better ask somebody with more experiance.

**Comment by lipisak** [comment]
Hello,
If I remove the board add-on everything works well.

I wasn't event aware of requirement for HtmlImport annotation as we don't use it in project directly.

I'm also not sure what to do.

**Comment by appreciated** [comment]
Hi, 
You could try to setup a minimal example the Shows the issue with Spring + `@HTMLImport` Annotations + Vaadin Board in combination and open an issue in the related repository.
The Annotations are part of the Vaadin Framework and are supposed to work always so nothing to worry about.

**Comment by lipisak** [comment]
Hi,
Right now I'm doing some more investigation. Without the board plugin HtmlImports are called as they are supposed to. I'll keep you posted.

J.

**Comment by lipisak** [comment]
HtmlImport are stopped due error in frontend javascript: webcomponents-lite.js

Console output:
`SEVERE: TypeError: Attempted to assign to readonly property.
java.lang.JsException: TypeError: Attempted to assign to readonly property.
	at Unknown.flatten(http://localhost:8090/VAADIN/frontend/es6/webcomponentsjs/webcomponents-lite.js)
	at Unknown.i(http://localhost:8090/VAADIN/frontend/es6/webcomponentsjs/webcomponents-lite.js)
	at Unknown.anonymous(http://localhost:8090/VAADIN/frontend/es6/webcomponentsjs/webcomponents-lite.js)
	at Unknown.onload(http://localhost:8090/VAADIN/frontend/es6/webcomponentsjs/webcomponents-lite.js)`

If you notice the @JavaScript annotations are performed as they supposed to be. but error comes from this script. since then the script invocation is stopped and HtmlImports which should follow are stopped as the rest of client rendering.

Only two plugins uses webcomponents-helper dependency: App-layout and Vaadin boards. So it has to be related somehow here.

Could you check this out?

**Comment by lipisak** [comment]
Here is also JavaScript console screenshot as there is also html-imports.js error.

![snimek obrazovky 2018-09-19 v 10 32 23](https://user-images.githubusercontent.com/2478417/45741279-750e7c80-bbf7-11e8-9b4e-656ac119a7ef.png)

**Comment by appreciated** [comment]
> Only two plugins uses webcomponents-helper dependency: App-layout and Vaadin boards. So it has to be related somehow here. 
I could try to instead of importing `webcomponents-lite.js` directly to import a custom JS, that imports the file only eventually. Although im pretty sure that importing the same file wouldn't be an issue. Maybe the problem is that the addons use two different versions?  
First of all thank you very much for your time on investigating it. Amazing that you managed to sort this out.

**Comment by lipisak** [comment]
Those addons uses the same version of webcomponents-helper. That's what I'm sure about. 

Could you please check on this? 

Thank you

**Comment by appreciated** [comment]
Unfortunatly no, I'm currently super busy with university 😞. 
I would proceed if removing the web webcomponent.js `@HTMLImport` would fix the issue and go from there. Also I wouldn't hesitate to contact somebody of the Vaadin team (a developer of the Vaadin Board preferably) to help with this.
