### ISSUE TITLE
Add method for setting locale 

### ISSUE THREAD

**Issue by arivanajoki** [appreciated/vaadin-app-layout#140]
Add method for setting locale for AppLayoutComponent and propagate locale to PrettyTime for localised  timestamps (in notifications).

**Comment by appreciated** [comment]
I will definitely add this. It's just a  matter of time. Currently I'm very limited in that aspect :pensive:. If you need this quickly you are welcome to make a pull request.

**Comment by appreciated** [comment]
Now it is possible to overwrite the default behaviour as follows.
```
DefaultNotificationHolder notifications = new DefaultNotificationHolder();
notifications.setDateTimeFormatter(notification -> {notification -> new PrettyTime().
            format(Date.from(notification.getTime().atZone(ZoneId.systemDefault()).
                    toInstant()));});
```
