### ISSUE TITLE
Style Ignore

### ISSUE THREAD

**Issue by cachorios** [appreciated/vaadin-app-layout#147]
I can not apply my own style, when I'm using AppLayou, I ignore it.
```
@Route(value="parametros", layout = MainView.class)
@HtmlImport("frontend://src/views/crud/list-preview.html")
```

if it works when I remove the layout
```
@Route(value="parametros")
@HtmlImport("frontend://src/views/crud/list-preview.html")
```

How can i fix this?

//--

No puedo aplicar un estilo propio, cuando estoy usando AppLayou, lo iginora, 
```
@Route(value="parametros", layout = MainView.class)
@HtmlImport("frontend://src/views/crud/list-preview.html")
```

si funciona cuando quito el layout
```
@Route(value="parametros")
@HtmlImport("frontend://src/views/crud/list-preview.html")
```

como puedo solucionar esto?

**Comment by deyaeddin** [comment]
Hi @cachorios 
I think you need to add @HtmlImport("frontend://src/views/crud/list-preview.html") to your MainView

Also, don't forget about the Shadow-DOM styling [theming](https://vaadin.com/docs/v10/bakeryflow/theming.html) 

Maybe you can share your code so I can be more helpful!!

**Comment by appreciated** [comment]
@cachorios checkout my answer in #163
