### ISSUE TITLE
Inheritance of Lumo Properties

### ISSUE THREAD

**Issue by Juchar** [appreciated/vaadin-app-layout#149]
For Vaadin 10 it would be great if the properties of the lumo theme are inherited.
That way it would be possible to e.g. change the `--lumo-primary-color` and have a matching app layout.

# Colors
Automatically adapt the background color of the app bar, the font and icon colors, badge color as well as the selected color to use the lumo colors.

# Badges
Maybe it would also make sense to use the [Lumo Badge Style](https://cdn.vaadin.com/vaadin-lumo-styles/1.2.0/demo/badges.html) for the badges to match the rest of the UI. _Maybe we could pass an enum value for determining if we want to use the primary, small or pill style?_

# Box Shadow
The [Lumo Box Shadow](https://cdn.vaadin.com/vaadin-lumo-styles/1.2.0/demo/styles.html#box-shadow) could be used for the box shadow of the menu.

# Sizing and Spacing
Additionally the [Lumo Sizing and Spacing](https://cdn.vaadin.com/vaadin-lumo-styles/1.2.0/demo/sizing-and-spacing.html) could be taken into account for the height and spacing of the menu items.

# Trials
I tried to customize the background color but it did not work:
```html
<custom-style>
  <style>
    html {
      --lumo-base-color: #FFF;
      --lumo-primary-color-10pct: hsla(174, 41%, 51%, 0.1);
      --lumo-primary-color-50pct: hsla(174, 41%, 51%, 0.5);
      --lumo-primary-color: hsl(174, 41%, 51%);
      --lumo-primary-contrast-color: #FFF;
      --app-layout-bar-background-color: hsl(174, 41%, 51%);
    }
  </style>
</custom-style>
```

Any hints?

**Comment by deyaeddin** [comment]
Thanks @Juchar for the note:
you can create shared-styles.html as explained in documentation [here](https://vaadin.com/docs/v10/charts/java-api/css-styling.html)

Then add something like this in your custom-style element:

```
<custom-style>
<style>
     * {
       --lumo-primary-color: hsl(358, 61%, 17%);
       --lumo-primary-color-50pct: hsla(358, 61%, 17%, 0.5);
       --lumo-primary-color-10pct: hsla(358, 61%, 17%, 0.1);
       --lumo-primary-text-color: hsla(0, 100%, 19%, 0.9);
       --lumo-secondary-text-color: hsla(0, 100%, 19%, 0.7);
       --lumo-body-text-color: hsla(225, 9%, 9%, 0.9);
       --lumo-font-family: "Open Sans", sans-serif;
       --primary-color: var(--lumo-primary-color);
       --app-layout-focus-color: var(--lumo-primary-text-color);
       --app-layout-bar-background-color: var(--lumo-primary-color);
       --app-menu-background-color: var(--lumo-primary-contrast-color);
       --app-menu-selected-bg-color: var(--lumo-contrast-10pct);
       --app-menu-color: #727272;
    }

  </style>
</custom-style>
```

**Comment by appreciated** [comment]
- [x] Colors  
- [x] Badges  
- [x] Box Shadow  
- [ ] Sizing and Spacing  
 - Themes checked  
   - [x] Lumo Light  
   - [x] Lumo Dark
