### ISSUE TITLE
URL enhancement

### ISSUE THREAD

**Issue by luisrafaelinf** [appreciated/vaadin-app-layout#15]
when I have a menu description with accented characters the URL shows the accents and in other cases places symbols to replace it, just as it keeps spaces

![1](https://user-images.githubusercontent.com/19829574/31031173-f4bd5ad0-a525-11e7-8f19-e0a3ed67a8f9.PNG)
![2](https://user-images.githubusercontent.com/19829574/31031178-f783f8a0-a525-11e7-8d28-3198dfcb9121.PNG)

it is advisable to avoid that type of characters in the presentation of the URL, thus remaining in the description of the menu
![3](https://user-images.githubusercontent.com/19829574/31031347-4252a6f6-a526-11e7-8d3a-203eddc43df0.PNG)

Here is an example of how to treat them:

 public void addViewToNavigator(Navigator navigator)  {
        
        String newName = StringUtils.stripAccents(WordUtils.capitalizeFully(name).replaceAll(" ", ""));

        if (view != null) {
            navigator.addView(newName , view);
        } else if (className != null) {
            navigator.addView(newName , className);
        }
    }

 public void setNavigationClickListener(NavigatorNavigationElement element)  {

        NavigationBadgeButton button = (NavigationBadgeButton) element.getComponent();
        String newName = StringUtils.stripAccents(WordUtils.capitalizeFully(element.getName()).replaceAll(" ", ""));

        button.getButton().addClickListener(clickEvent -> {
            UI.getCurrent().getNavigator().navigateTo(newName);
            AbstractNavigationDrawer.closeDrawerIfNotPersistent();
        });
 }

this are the imports:

import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.text.WordUtils;

**Comment by appreciated** [comment]
Since I'm gone for a week tomorrow this will have to wait until I'm back

**Comment by appreciated** [comment]
How to use it:
```
       AppLayout drawer = AppLayoutBuilder.get()
                ...
                .withViewNameInterceptor(new DefaultViewNameInterceptor())
                ...
                .build();
```
