### ISSUE TITLE
CDIBuilder

### ISSUE THREAD

**Issue by mirkoliver** [appreciated/vaadin-app-layout#150]
In the Vaadin 8 variant I could work with Dependency Injection:

`AppLayout.getCDIBuilder(behaviour).withViewProvider(() -> viewProvider)`

How to do this in the Vaadin 10 variant?

**Comment by appreciated** [comment]
Vaadin Spring support is currently not given. Mostly due to a lack of time from my side.

**Comment by appreciated** [comment]
@mirkoliver I think there is no longer a ViewProvider.
