### ISSUE TITLE
Problems with running the example via Tomcat

### ISSUE THREAD

**Issue by mirkoliver** [appreciated/vaadin-app-layout#154]
I've run your app-layout-annotation-example (for Vaadin 10) via jetty:run (as goal in the Eclipse Maven build) - like you've described it. Everything is fine in the resulting page (http://localhost:8080).

But when I run the same project via Eclipse's "Run on Server" (Tomact 8) the outcome is an incomplete page - not all page elements are displayed, the page is shattered. So it seems, that some elements are missing. I've looked into the Chrome Console and there it says that a lot of bower_components failed to load.

I've then tried another thing - have installed the app-layout-annotation-example-2.0.1-SNAPSHOT.war from the project's target folder in an external Tomcat 8. But it shows the same negative results.

Any advice?

**Comment by appreciated** [comment]
Hmm this is a question for one of the Vaadin team I have no clue how this could happen. Maybe open an issue at [flow](https://github.com/vaadin/flow)?

**Comment by mirkoliver** [comment]
No - in the Eclipse case they are not packed. They lack. This might be the clue!

I've used your example because I had the same effect before in another project (my own) - there I have added `app-layout-2.1.1.jar` and `app-layout-addon-2.0.1-SNAPSHOT.jar` in my path. `app-layout-addon-2.0.1-SNAPSHOT.jar` contains the resources you've mentioned. But nevertheless the elements are missing on the page. Is there something I did not understand regarding your AddOn? Do I have to precompile something to get these resources from the jar into META-INF??

**Comment by appreciated** [comment]
Maybe you need to tell the Eclipse plugin explicitly where to find the additional resources.

**Comment by mirkoliver** [comment]
I've already tried - and as I've stated above: they are packed into `app-layout-addon-2.0.1-SNAPSHOT` what is then put into the lib folder of the war file.

But to deploy this special example project via Eclipse to Tomcat is also not the main question I have. I want to use your AddOn in my own projects. As I've above stated, I've thought, that I just have to put the jars on the classpath and then it is working. But it seems, that not all resources in the jar files are found (`app-layout-addon-2.0.1-SNAPSHOT.jar` contains the resources that you've mentioned).

**Comment by deyaeddin** [comment]
@mirkoliver can you try the solution on #157

**Comment by mirkoliver** [comment]
Hi @deyaeddin , my project doesn't use SpringBoot or Spring. So this can not be the point.

**Comment by dmoksi** [comment]
Any news regarding this problem ? I have the same issue deploying to Wildfly 12. My application name is AppLayoutTest and it is deployed to localhost:8080/AppLayoutTest. But application is searching for resources starting from root (/). So instead of searching for **localhost:8080/AppLayoutTest/frontend/bower_components/app-layout/app-header-layout/app-header-layout.html** it is searching for **localhost:8080/frontend/bower_components/app-layout/app-header-layout/app-header-layout.html**. My temporary workaround is deploying application to root and then everything works. What controls the path for resources, is there a setting I can change ?

**Comment by appreciated** [comment]
Reopen if issue persists
