### ISSUE TITLE
Clicking on the menu items does not trigger the enter() method of the View

### ISSUE THREAD

**Issue by gnumarco** [appreciated/vaadin-app-layout#156]
Hi. Maybe I am missing something, but when adding components that implement View to the menu, the constructor is executed. That's normal. Now I need to initialize things (heavy call to a DB) only when the view is actually displayed, not to slow down the loading of the whole app. For this, I thought that the best way way to perform this inside the enter() method of the Component implementing View, but it seems that when the menu entry is clicked (that is to say, you navigate to this view), the enter() method isn't triggered.
Did I do something wrong?

**Comment by appreciated** [comment]
Hi @gnumarco I do not recommend binding heavy lifiting tasks directly to the UI Thread. 
Instead use a loading indicator and update the UI with a server-sided push via [`UI.access`](https://vaadin.com/api/framework/8.5.2/com/vaadin/ui/UI.html#access-java.lang.Runnable-).

[Push Example with separate Thread from Vaadin](https://vaadin.com/docs/v8/framework/advanced/advanced-push.html):
```
public class PushyUI extends UI {
    Chart chart = new Chart(ChartType.AREASPLINE);
    DataSeries series = new DataSeries();

    @Override
    protected void init(VaadinRequest request) {
        chart.setSizeFull();
        setContent(chart);

        // Prepare the data display
        Configuration conf = chart.getConfiguration();
        conf.setTitle("Hot New Data");
        conf.setSeries(series);

        // Start the data feed thread
        new FeederThread().start();
    }

    class FeederThread extends Thread {
        int count = 0;

        @Override
        public void run() {
            try {
                // Update the data for a while
                while (count < 100) {
                    Thread.sleep(1000);

                    access(new Runnable() {
                        @Override
                        public void run() {
                            double y = Math.random();
                            series.add(
                                new DataSeriesItem(count++, y),
                                true, count > 10);
                        }
                    });
                }

                // Inform that we have stopped running
                access(new Runnable() {
                    @Override
                    public void run() {
                        setContent(new Label("Done!"));
                    }
                });
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}
```

**Comment by gnumarco** [comment]
You are perfectly right, I will proceed as you say.
