### ISSUE TITLE
Missing example for top layout

### ISSUE THREAD

**Issue by yampeku** [appreciated/vaadin-app-layout#158]
While the Vaadin 10 example for Left layout seems to work perfectly fine, reproducing the top layout as seen on the demo page seems difficult. Some classes seem to be used in other way (e.g. there is no "TopSubMenuBuilder") so an example of how the demo top layout is meant to be built would be nice.

**Comment by appreciated** [comment]
> reproducing the top layout as seen on the demo page seems difficult. 
This is indeed not possible currently, since the api would have needed an additional feature (adding elements to the menu and to the top menu seperatly) for this which I hadn't have the time to develop.

**Comment by appreciated** [comment]
@yampeku there is now a TopMenuBuilder
