### ISSUE TITLE
AppLayoutRouterLayout.getCurrent() returns always null

### ISSUE THREAD

**Issue by slatequarry** [appreciated/vaadin-app-layout#159]
The static method AppLayoutRouterLayout.getCurrent() returns always null !

**Comment by svenruppert** [comment]
well, not able to find where it is set ;-) but I am working on this

**Comment by appreciated** [comment]
> 
> 
> well, not able to find where it is set ;-) but I am working on this

It isn't that is the problem 😅

**Comment by svenruppert** [comment]
Bug fixed, will be delivered with next version
