### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by LeshaRB** [appreciated/vaadin-app-layout#163]
Can you add some examples how change styles?

For example
```
menu-header-wrapper {
        align-items: center;
}
```

I try @StyleSheet, @HtmlImport and other way. But can not apply it

**Comment by appreciated** [comment]
As you probably know it is not possible to style elements that are inside the shadow dom. I will need to introduce a css variable to allow this.

**Comment by ChristianStrotz** [comment]
I got the same problems. Tried to change styles but it doesn't work.

Also my custom styles of the view (elements inside the view) are ignored since the view is now contained in the shadow dom of the app-layout.

But it is possible to style vaadin components (e.g. TextField, ComboBox) with the usage of dom-module:

`<dom-module id="text-field-styles" theme-for="vaadin-text-field vaadin-text-area vaadin-combo-box">
	<template>
		<style>
			:host([readonly]) [part="input-field"], :host([readonly]) [part="value"] {
				padding: 0 0;
			}
			
			:host([readonly]) [part="input-field"]::after {
				border: none !important;
			}
			
			:host([readonly]) [part="toggle-button"]::before {
    			visibility: hidden;
			}
		</style>
	</template>
</dom-module>`

This works fine with vaadin components but it didn't work with the app-layout styles.

**Comment by ardarda** [comment]
@LeshaRB A similiar issue we had on app-layout customization which is app-toolbar background color needs to get update. Although being not so sure about if I did the right thing or if I had any alternatives, I go with js injection after the document gets loaded:

After AppLayoutBuilder.build() method gets run, 
css var: --app-layout-bar-background-color needs to get changed

Injected js:

    // top tool bar background color css variable customization point
    UI.getCurrent().getPage().executeJavaScript("window.onload = function() {\n" +
            "  setTimeout(function() {\n" +
            "    var html = document.getElementsByTagName('html')[0];\n" +
            "    html.style.cssText = \"--app-layout-bar-background-color: #004a96\";\n" +
            "  }, 0);\n" +
            "};");

**Comment by appreciated** [comment]
Theming works fine for me as long as I use CSS Variables.

To set the css variables you need a file as this one:
https://github.com/appreciated/vaadin-app-layout/blob/feature-inherit-lumo-styles/app-layout-examples/app-layout-theme-example/src/main/resources/META-INF/resources/frontend/theming/custom.html
And import it via @HTMLImport.

You can find the current css variables available here:
https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/resources/sass/app-layout/app-layout/app-layout.scss#L62-L116

You can find the future css variables here:
https://github.com/appreciated/vaadin-app-layout/blob/feature-inherit-lumo-styles/app-layout-addon/src/main/resources/META-INF/resources/frontend/com/github/appreciated/app-layout/app-layout.css

**Comment by appreciated** [comment]
@LeshaRB for Vaadin Components you can always use the Vaadin API:
```
MenuHeaderComponent header = new MenuHeaderComponent("App-Layout",
        "Version 2.0.1",
        "/frontend/images/logo.png"
);
header.getElement().getStyle().set("align-items","center");
```
