### ISSUE TITLE
Disable menu

### ISSUE THREAD

**Issue by LeshaRB** [appreciated/vaadin-app-layout#164]
How I can disable left menu?

For example LoginView or ErrorView

**Comment by svenruppert** [comment]
Ping me for a demo

**Comment by LeshaRB** [comment]
@svenruppert Ping you for a demo =)

LoginView
I want view parent = AppLayout with title and image but without left menu

**Comment by appreciated** [comment]
> I want view parent = AppLayout with title and image but without left menu
@LeshaRB This is actually a very reasonable feature request and is currently not really possible. I consider providing it for the next version
