### ISSUE TITLE
NotificationHolder

### ISSUE THREAD

**Issue by alabotski** [appreciated/vaadin-app-layout#165]
Some questions

1 What is different between DefaultNotificationHolder and DefaultBadgeHolder?

2 How properly use DefaultNotificationHolder from View?

For example 

https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/test/java/com/github/appreciated/MainView.java
DefaultNotificationHolder notificationHolder

So I want add notifications from View2 for example.

**Comment by LeshaRB** [comment]
Nobody knows? (

**Comment by appreciated** [comment]
@LeshaRB Sorry for keep you waiting, but I wanted to give a proper example, and I'm currently rather busy with other things.  
> 1 What is different between DefaultNotificationHolder and DefaultBadgeHolder?

The difference is that the NotificationHolder can hold Notifications (f.e. Title + Description) and will keep track on how many are unread, order them by priority and time they were inserted (imaging a kind of news ticker) and display the unread count in a "badge". 
The BadgeHolder will only hold a plain number and bind it to a "badge". 

> 2 How properly use DefaultNotificationHolder from View? 

I will put a proper example example together, but this will require some time. I must admit that the access from the Views is rather problematic and currently probably rather dirty. Maybe @svenruppert has an clever idea how to make them easily accessible for the Views.

**Comment by LeshaRB** [comment]
Thank you

Will be wait @svenruppert advice

**Comment by svenruppert** [comment]
@LeshaRB , let´s wait a little bit, please..  I just started some internal refactorings. After this, we should have a detailed look at this.

**Comment by appreciated** [comment]
Postponed to 2.02.

**Comment by appreciated** [comment]
Answer to 2:
Badges:
Use the following class [`AppLayoutBadges`](https://github.com/appreciated/vaadin-app-layout/blob/c4188ae9e05f55e9b19a726048206ddae4100c03/app-layout-addon/src/main/java/com/github/appreciated/app/layout/entity/AppLayoutBadges.java) to set the BadgeHolder in your `AppLayoutRouterLayout` and access it from anywhere as long as your are running the command from an UI thread. 
Notifications:
Use the following class [`AppLayoutNotification`](https://github.com/appreciated/vaadin-app-layout/blob/c4188ae9e05f55e9b19a726048206ddae4100c03/app-layout-addon/src/main/java/com/github/appreciated/app/layout/notification/AppLayoutNotification.java) to set the NotificationHolder in your `AppLayoutRouterLayout` and access it from anywhere as long as your are running `getNotificationHolder()` from an UI thread.
