### ISSUE TITLE
Menu header and footer section at fixed top/bottom position

### ISSUE THREAD

**Issue by MarkSSW** [appreciated/vaadin-app-layout#167]
Hello,

first of all, thanks for providing this great addon!

Question: Is it possible to customize the menu so that the header and footer sections of the menu are fixed at top and bottom respectively, so that only the section between them expands when the browser window height changes? 

Thanks for your help,
Mark

**Comment by appreciated** [comment]
Are we talking about the Vaadin 8 or the Vaadin Flow Version? They are pretty different in that perspective.

**Comment by appreciated** [comment]
@MarkSSW Yes this is possible, but you will need to implement a interface to allow the contained Elements to still be highlighted and use some css `flexbox` magic.

**Comment by appreciated** [comment]
@MarkSSW checkout the changes in #167 as soon as Version 2.0.1 is released
