### ISSUE TITLE
Crazy behavior of menu...

### ISSUE THREAD

**Issue by benwul** [appreciated/vaadin-app-layout#169]
First I have to say: Good job! Really nice addon.

Versions: Vaadin 8.6 (same behavior with 8.2->8.6)
Java: Openjdk 10 (same behavior with 1.8)
Applayout: 1.0.2

```
@SpringUI(path = UIAnwender.PATH)
@Title(UIAnwender.TITEL)
@Viewport("width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no")
@Theme("valo")

public class UIAnwender extends UI {
	public final static String PATH = "/anwender";
	public final static String TITEL = "Anwender";

	@Autowired
	private SpringViewProvider provider;
	DefaultBadgeHolder badge = new DefaultBadgeHolder();
	DefaultNotificationHolder notifications = new DefaultNotificationHolder();
        @Override
	protected void init(VaadinRequest request) {
		AppLayoutComponent menu = 
        AppLayout.getCDIBuilder(Behaviour.LEFT_RESPONSIVE_HYBRID)
				.withViewProvider(() -> provider)
			        .withNavigationElementInfoProducer(new 
                                 DefaultSpringNavigationElementInfoProducer())
				.withDesign(AppLayoutDesign.MATERIAL)
				.add(badge, OffeneLogs.class)
				.add(ExtraServices.class)
				.add(MeineLogsRechnungen.class)
				.add(SubmenuBuilder.get(Menupunkte.STAMMDATEN.getString(), VaadinIcons.PLUS)
				.add(MeineDaten.class)
				.add(Lizenzen.class)
						.build())
				.add(Logout.class).build();
		Panel root = new Panel();
		root.setContent(menu);
		setContent(root);
	}
}
```

Behavior of the menu when its Behaviour.LEFT_RESPONSIVE_HYBRID)
![menu sub](https://user-images.githubusercontent.com/44745637/48024330-acea6880-e140-11e8-9791-d9d0965d38ee.PNG)

Behavior of the menu when its Behaviour.TOP_LARGE)
![menu sub top](https://user-images.githubusercontent.com/44745637/48024355-bffd3880-e140-11e8-8855-a40dcf672754.PNG)

The Views are scrollable if they to large, but the menu is not...
I think i'm too stupido....

**Comment by appreciated** [comment]
It seems as if the styles of the menu are missing. [Did you follow the steps in the tutorial?](https://github.com/appreciated/vaadin-app-layout/wiki/Vaadin-8-%7C-Installation)

**Comment by benwul** [comment]
You're right. It was my mistake with my themes...
