### ISSUE TITLE
LeftMenu caption

### ISSUE THREAD

**Issue by LeshaRB** [appreciated/vaadin-app-layout#171]
SetCaption stopped working if called the second time

```
    @Override
    public void localeChange(LocaleChangeEvent event) {
        log.info("112233");
        menuUserList.setCaption(getTranslation(MENUITEM_USER));
    }
```

**Comment by watho** [comment]
Just added a  PR #170  for a similar problem. Try `setText()`

**Comment by LeshaRB** [comment]
Why you delete ?? from LeftNavigationComponent
```

    public void setCaption(String caption) {
        this.caption = caption;
    }
```

**Comment by watho** [comment]
The method did not do anything to the underlying element. That's the cause of your bug.  `getText()` is the right method, but maybe a better fix would be

```
public void setCaption(String caption) {
  this.setText(caption);
  this.caption = caption;
    }
```
to not break the api.

**Comment by LeshaRB** [comment]
I understand =)
But it will be good to change name in real time 
For example **localeChange**


Sorry for english

**Comment by watho** [comment]
Have you tried getText() instead. It should work. Can't try it myself today.

**Comment by LeshaRB** [comment]
Now I have the same problem with **LeftSubMenuBuilder** 


```
LeftSubMenuBuilder        menusubMoney = LeftSubMenuBuilder
                .get(getTranslation(MENUITEM_MONEY), VaadinIcon.PLUS.create())
                .add(menuPaymentList)
                .add(menuWithdrawList)
                .add(menuPurchaseConfig);
```
And 

```
    @Override
    public void localeChange(LocaleChangeEvent event) {
         menusubMoney.setText(getTranslation(MENUITEM_PURCHASE));
    }
```

**Comment by appreciated** [comment]
@LeshaRB #177 should fix your issues.
