### ISSUE TITLE
Reimplement Submenus

### ISSUE THREAD

**Issue by appreciated** [appreciated/vaadin-app-layout#175]
Currently the solution for submenus is especially in "small" menus rather not good (when scrolling is needed).
A better solution could be to offer a custom implementation that matches the Menu of the Google Cloud  Console. This could be easily implemented by using  webcomponents and would be UX wise a better match for desktop clients. 

Before implementing a good fit for mobile devices is required (since most of the webusers are indeed mobile) and needs to be checked. 

### Example
![submenus](https://user-images.githubusercontent.com/1729845/48806694-77867300-ed1b-11e8-950f-7f6fe1f77bcb.PNG)

**Comment by Springrbua** [comment]
I actually like the look of the current implementation and would preffer it over the one in the screenshot.
The `Navigation drawer`, as the name implies, is usually used for navigation and in most webpages it is either a flat list or a tree with only a few levels of depth.
I can't remember a single webpage which displayes a menu as in your screenshot in a sidenav.
A few references:
- Google Drive
![image](https://user-images.githubusercontent.com/18258317/54212963-e9114980-44e3-11e9-9152-aa10516cc1ef.png)

- Angular Material
![image](https://user-images.githubusercontent.com/18258317/54212616-8029d180-44e3-11e9-91c4-a794710ace5c.png)

- Material Design Webpage
![image](https://user-images.githubusercontent.com/18258317/54212522-5ffa1280-44e3-11e9-96ca-d8c4e82b3146.png)

So I would still keep the current version and add this as an optional feature.

For the implementation for mobile devices, you might take a look at the `ContextMenu` in Vaadin.
I personally like it'S implementation for mobile devices and it might be a good solution for this case too.
