### ISSUE TITLE
Selection

### ISSUE THREAD

**Issue by alabotski** [appreciated/vaadin-app-layout#186]
Not always playable

Sometimes when switching to a View that is not in the menu list. 
Stand out last LeftNavigationComponent

**Comment by appreciated** [comment]
Please make the issue description more understandable.

**Comment by LeshaRB** [comment]
Crete new view
`@Route(value = "view10", layout = MainLayout.class)
public class View10 extends AbstractView  implements HasUrlParameter<String> {
    @Override
    String getViewName() {
        return getClass().getName();
    }

    @Override
    public void setParameter(BeforeEvent beforeEvent, String s) {

    }
}`

Modify View2
`@Route(value = "view2", layout = MainLayout.class)
public class View2 extends AbstractView {

    public View2() {
        add(new Button("SubContent", buttonClickEvent -> UI.getCurrent().navigate(SubContent.class)));

        Button button = new Button("Test");
        button.addClickListener(
            (ComponentEventListener<ClickEvent<Button>>) event -> UI.getCurrent().navigate(View10.class, "test"));
        add(button);
    }

    @Override
    String getViewName() {
        return getClass().getName();
    }
}`


Now open link
http://localhost:8080/view2

You can see menuitem "Charts" highlighted
<img width="605" alt="image" src="https://user-images.githubusercontent.com/439337/50338334-11149080-0525-11e9-9399-e1c139fae3b2.png">

Now click button "test" As you can see there are two menuitems highlighted
<img width="564" alt="image" src="https://user-images.githubusercontent.com/439337/50338403-4620e300-0525-11e9-9baf-0b6683af9d40.png">

**Comment by appreciated** [comment]
@LeshaRB From my knowledge this is an issue of the [app-menu](https://www.webcomponents.org/element/oyeharry/app-menu) webcomponent (or better said it does not support multi-nested menus). 
This will also be fixed by #175.

**Comment by appreciated** [comment]
Closing in favor of #175
