### ISSUE TITLE
Click doesn't work on iPad - version 1.0.2

### ISSUE THREAD

**Issue by lipisak** [appreciated/vaadin-app-layout#187]
Hello, I'm testing our application on iPad, but the elements in left menu doesn't seem to be working. Clicking doesn't respond at all. Only description shows.
This is happening with Vaadin v 8.6.1 and App layout v 1.0.2.
We use LEFT_RESPONSIVE_SMALL_NO_APP_BAR setting and we are adding elements via addClickable method in builder.

**Comment by appreciated** [comment]
@lipisak cannot reproduce with 1.0.2. Are you using [Tooltips](https://vaadin.com/docs/v8/framework/articles/UseTooltipsToClarifyFunctions.html) for any chance?

**Comment by lipisak** [comment]
@appreciated yes We are using it. Right now I turned them off on touch devices, as they are useless anyway. Since then it works, so I'm closing this issue.

**Comment by appreciated** [comment]
Maybe open an issue on the Vaadin?

**Comment by lipisak** [comment]
Actually it works eg. for buttons but there has to be "double tap". First shows tooltip, second fires click event. In app layout menu it doesn't work at all for click event. It only shows tooltip. But it can be vaadin issue anyway. I will try to find it in vaadin github issues. Thx.

**Comment by appreciated** [comment]
> Actually it works eg. for buttons but there has to be "double tap"
🤦‍♂️
