### ISSUE TITLE
Allow double side bar Navigation

### ISSUE THREAD

**Issue by appreciated** [appreciated/vaadin-app-layout#190]
As to be seen in Bitbucket

![alt text](https://www.atlassian.com/dam/jcr:2e8d96aa-6d0e-4670-9d58-50c0251c4bea/git_commits_source.2017-12-12-00-31-54.gif "Logo Title Text 1")

**Comment by appreciated** [comment]
@svenruppert Do you have any idea how we could properly extend the API to make this possible?

**Comment by Springrbua** [comment]
@appreciated this double side bar seems to contain so e kind of "quick actions", so we might call it something like "QuickActionBar".
The drawer then might have multiple states:
- open: Quick action bar and standard drawer are open
- compact: only QuickActionBar is opened
- closed: Drawer is completely closed

But I don't have no idea for the mobile version, since 2 sidebars on mobile devices are just too much in my opinion.

**Comment by appreciated** [comment]
The "Quick Actions" has in my opinion the same purpose as the App Bar. Simply the orientation is vertical instead of horizontal and it is on the left side instead on the top. 
On mobile devices it should behave the same as the other `LEFT` Behavior since it makes the most times sense. For the other cases is the top and in furture also the bottom behavior.

**Comment by Springrbua** [comment]
@appreciated So the second sidebar, in your opinion, would replace the top app bar?
I would rather see it as an addition, especially for desktop users.
In my use case, the app bar displays the title, the navigation and an "account-manu" (with logout etc.).
However, the user can also have customizable "quick-actions", which I would like to display in this second sidebar.

**Comment by appreciated** [comment]
> especially for desktop users.
Have you tried, the menu of Bitbucket? I find it pretty convenient especially for Desktop Users. 
> So the second sidebar, in your opinion, would replace the top app bar? 
The outer left yes. If you checkout the icons it also has pretty much the same purpose as the Top App bar. 
This requires API Changes of the builder. I'd rather allow to wrap the AppLayout in another `AppBarRouterLayout` which only contains an app bar. So the main API stays untouched.

**Comment by Springrbua** [comment]
@appreciated yea I just had a look at the Bitbucket menu and I really like it.
But I still like to have an AppBar at the top and use other actions on that second side bar.
On the mobile version I have seen, that they have an empty AppBar with just the menu button.
I guess it would make sense to place the Profile menu and maybe a title in that empty space.

**Comment by appreciated** [comment]
closed by a59cdfbf99ba0d39b2607c286254e8b5cedd869b
