### ISSUE TITLE
UI Style not rendering as expected.

### ISSUE THREAD

**Issue by jharahuld** [appreciated/vaadin-app-layout#191]
Downloaded from github and imported in eclipse, clean install maven, tried to run app-layout-example-plain and app-layout-example-plain-annotation in tomcat 8 but not getting ui as shown in online demo, any one please help me out.
![screenshot from 2018-11-17 11-56-34](https://user-images.githubusercontent.com/4396651/49848301-8cc25f00-fdfa-11e8-85e5-2aee3ce1e974.png)

**Comment by watho** [comment]
I think it's a duplicate of #166 and #154

**Comment by appreciated** [comment]
@watho yes indeed. Closing in favor of #154.
