### ISSUE TITLE
Submenu styles

### ISSUE THREAD

**Issue by LeshaRB** [appreciated/vaadin-app-layout#192]
<img width="311" alt="image" src="https://user-images.githubusercontent.com/439337/49881006-60303680-fe3e-11e8-9074-1fcc766ffd91.png">

**Comment by appreciated** [comment]
@LeshaRB need more information on Browser, Browser Version, OS, any styles applied? Which Version did you build?

**Comment by LeshaRB** [comment]
Hello 

I download last your app
And run test

**Comment by LeshaRB** [comment]
Os Mac
Firefox 65

**Comment by LeshaRB** [comment]
Thank you
