### ISSUE TITLE
change color of the app-toolbar

### ISSUE THREAD

**Issue by Sergio70** [appreciated/vaadin-app-layout#193]
Hi, Is it possible to change the color of the app-toolbar? 

I would like to change the color of the app-toolbar, I and tried to change it by setting "example: @StyleSheet (" styles.scss ")" with the modified style of this used in this addon, but I have no result (in production mode does not work).

Will anyone have any way to do this?

**Comment by appreciated** [comment]
Surely this is possible, which Version are we talking about 1.* or 2.*?

**Comment by Sergio70** [comment]
In versión 2.0.0 for vaadin flow

**Comment by appreciated** [comment]
Checkout my answer in issue #163

**Comment by Sergio70** [comment]
Excellent, although in production mode it still does not work, in production mode it takes the default color,
and are you planning to publish version V2.0.1?

**Comment by appreciated** [comment]
@Sergio70 can you check in the network tab if the `custom.html` was loaded in production mode?

**Comment by Sergio70** [comment]
![image](https://user-images.githubusercontent.com/20112231/50120834-77936900-021c-11e9-879f-170f60d8d76b.png)

Apparently, it's not loading the custom.html file, I do not know why: /

**Comment by appreciated** [comment]
can you try to load it the following way instead of a `@HtmlImport`:
```
public class MainLayout extends AppLayoutRouterLayout {
  @Override
  public AppLayout createAppLayoutInstance() {
    getUI().ifPresent(ui -> ui.getPage().addHtmlImport("frontend://...html"));
    ...
  }
}
```
and check if that changes anything for you?

**Comment by Sergio70** [comment]
can you try to load it the following way instead of a @HtmlImport:

public class MainLayout extends AppLayoutRouterLayout {
  @Override
  public AppLayout createAppLayoutInstance() {
    getUI().ifPresent(ui -> ui.getPage().addHtmlImport("frontend://...html"));
    ...
  }
}

I tried it but it also does not work in production mode, in the development of everything perfectly, do you have this kind of problems in its application in production mode? or how do you create war? I follow the steps established by vaadin:
https://vaadin.com/docs/v10/flow/production/tutorial-production-mode-basic.html

**Comment by Sergio70** [comment]
It has also added important! in the css

**Comment by appreciated** [comment]
@Sergio70 May I still see the content of your `custom.html` file?

**Comment by Sergio70** [comment]
@appreciated yes this is:

<custom-style> 
<style>

.card-profile{
    height: 150px !important;
    width: 150px !important;
    -moz-border-radius: 50% !important;
    -webkit-border-radius: 50% !important;
    -webkit-transition: .5s ease-in-out !important;
    border: 4px solid #e2e2e2 !important;
}

.paper-card{
    width: 96% !important;
    position: relative;
    background-color: white !important;
    border-radius: 2px;
    font-family: var(--paper-font-common-base_-_font-family);
    -webkit-font-smoothing: var(--paper-font-common-base_-_-webkit-font-smoothing);
    box-shadow: 0 2px 2px 0 rgba(0,0,0,.14), 0 1px 5px 0 rgba(0,0,0,.12), 0 3px 1px -2px rgba(0,0,0,.2);
    margin: 2% 2% 2% 2%;
    }

html, body {
	margin: 0;
	font-family: 'Roboto', 'Noto', sans-serif;
	-webkit-font-smoothing: antialiased;
	background: #f1f1f1;
	max-height: 368px;
}

.base {
	background-color: var(- -lumo-base-color);
	color: red;
}

 :root {
  --app-layout-bar-background-color: red;
} 

</style>
</custom-style>

end file.

 --app-layout-bar-background-color: red  <------ this change the color app-toolbar, in development this works,

**Comment by appreciated** [comment]
Instead of 
```
:root {
  --app-layout-bar-background-color: red;
} 
```

Try 
```
html {
  --app-layout-bar-background-color: red !important; // The !important might be irrelevant
} 
```

**Comment by Sergio70** [comment]
Sorry, the! Important if I established it in the previous tests. But anyway, with the changes you gave me in the .html, it does not work :/.

ok, I will continue testing if I can make this work, I wonder if this is affected by spring or resource mapping by vaadin.

**Comment by appreciated** [comment]
Which Version are you using?
