### ISSUE TITLE
Clicking on a LeftClickableComponent should not highlight it

### ISSUE THREAD

**Issue by watho** [appreciated/vaadin-app-layout#194]
**Describe the bug**
After clicking on a LeftClickingComponent the menu entry is highlighted as if it were a currently visible view.

**To Reproduce**
1. Change your plain example to have a action without rebuilding the menu. e.g.
 ```
.addToSection(new LeftClickableComponent("Test" ,
                               VaadinIcon.HAMMER.create() ,
                               clickEvent -> Notification.show("Test")
```
2. Click on these item
3. the item is selected despite the home view is still shown and should be selected

**Expected behavior**
Always highlight the menuitem for the currently shown view

** Additional Information (please complete the following information):**
 - OS: Linux
 - Browser: Chromium 71
 - Version: latest master ab0965ba3a3900f6aa1ce2fc3c0a9949c40ee285 

**Screenshots**

![screenshot_20181217_111240](https://user-images.githubusercontent.com/6670370/50080697-f8d30780-01ec-11e9-99bc-f47a5d540014.png)

**Comment by appreciated** [comment]
Closing an favor of #175
