### ISSUE TITLE
Incorrect RouterLayout implementation preventing styling

### ISSUE THREAD

**Issue by ggecy** [appreciated/vaadin-app-layout#195]
**Describe the bug**
This issue applies to all app layouts extending from `com.github.appreciated.app.layout.behaviour.AbstractLeftAppLayoutBase`. In this class there is 
```
@Id("content") 
private Div content;
```
injected from PolymerTemplate, e.g. from `left-hybrid.html`. This is then used in `AbstractLeftAppLayoutBase.setAppLayoutContent()` method to display the route content.

However **this causes the Route to be injected inside the shadow DOM which prevents all global styles from working on anything displayed inside app layout**.

Instead the view should be inserted to `<slot></slot>` so it remains outside of `app-layout-left-hybrid` shadow dom. E.g. in `left-hybrid.html` there should be:
```
<div class="app-bar-application-content" size="100" id="content">
    <slot></slot>
</div>
```
and `AbstractLeftAppLayoutBase.setAppLayoutContent() ` should look like this:
```
@Override
    public void setAppLayoutContent(HasElement content) {
        if (content != null) {
            this.getElement().appendChild(content.getElement());
            setUpBackNavigation(content);
        }
    }
```

**To Reproduce**
1. In your application using vaadin app-layout addon include a global styles file with <custom-style> inside and define any class in there.
2. Create a `@Route` that will display in `AppLayoutRouterLayout` according to examples.
3. Try to insert any element with that class inside the route component.
4. Element will not see the class and styling will not work.

**Expected behavior**
When adding a class from global styles to element in some `@Route` component the global styles should be visible and applied. This works when the route is inserted using `<slot></slot>` instead of inserting it directly inside the shadow dom of app layout.

**Screenshots**

File with global styles in `<custom-style>` element:
![custom styles file](https://user-images.githubusercontent.com/924873/50219304-16d86d80-038f-11e9-9536-7afd1fd76274.png)

When route component is inserted inside shadow dom:
![route insde of shadow dom](https://user-images.githubusercontent.com/924873/50219316-1e981200-038f-11e9-8892-27bc47bb050f.png)

Global styles are not working inside of app layout shadow dom:
![class is not working in shadow dom](https://user-images.githubusercontent.com/924873/50219322-23f55c80-038f-11e9-8c4b-42fbf58b5c99.png)

Now route component is inserted using `<slot></slot>`:
![route outside of shadow dom](https://user-images.githubusercontent.com/924873/50219326-28ba1080-038f-11e9-8dc4-b00c1bd18a16.png)

Global styles are working since the element is outside of shadow dom:
![class is working outside of shadow dom](https://user-images.githubusercontent.com/924873/50219335-2c4d9780-038f-11e9-9ee7-646b3915616a.png)

** Additional Information (please complete the following information):**
 - OS: any
 - Browser: chrome
 - Version: tested on 2.0.0 and 2.0.1-SNAPSHOT

**Comment by appreciated** [comment]
@ggecy First of all thank you very much for the research you obviously put into this issue! This issue does not only apply to the Content which is added by the `@Route` Annotations, but also to any Component that is added to the Menu of the AppBar.  I will fix this as soon as possible.

**Comment by ggecy** [comment]
Thanks. I guess you will have to use multiple named slots to fix those as well as in https://vaadin.com/docs/v12/flow/polymer-templates/tutorial-template-components-in-slot.html

**Comment by appreciated** [comment]
@ggecy Thats right, fix will be done in a few minutes, running ui tests now

**Comment by ggecy** [comment]
Thanks, it's working well now :)
