### ISSUE TITLE
Release 2.0.1 references app-layout-root 2.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by ChristianStrotz** [appreciated/vaadin-app-layout#198]
Release 2.0.1 has parent

`<parent>
        <groupId>com.github.appreciated</groupId>
        <artifactId>app-layout-root</artifactId>
        <version>2.0.1-SNAPSHOT</version>
    </parent>`

This Snapshot Version cannot be resolved.

**Comment by appreciated** [comment]
Did you run a `mvn imstall` goal on the parent? If you don't the parent cannot be resolved.

**Comment by appreciated** [comment]
Also please follow the issue template.

**Comment by appreciated** [comment]
Closing in favor of #198
