### ISSUE TITLE
Navigator help

### ISSUE THREAD

**Issue by migonzap** [appreciated/vaadin-app-layout#2]
Hi. First of all great job!
Is there any way to set the navigator variable of the NavigationDrawerBuilder?
I have some views that I don't want to add to the NavigationDrawerBuilder as NavigationElements but I need them to be added to the navigator (e.g. products/my-product view).

Thanks!
Matías

**Comment by appreciated** [comment]
Hello! Unfortunatly currently not 😢. 
But I can add one, I guess it would also be sufficient, if you can get the Navigator right? Still I will add both possiblities.

**Comment by migonzap** [comment]
Getting the Navigator will be sufficient.
Thanks!!  👍  :)

**Comment by appreciated** [comment]
This was a kind of tricky one but I'm now satisfied with the solution. 
Before release I need to do some testing with the new functionality and fix another bug.

**Comment by appreciated** [comment]
Since I don't know your Java abilities you can use the new API as follows:

````
NavigationDrawerBuilder.get()
   ....
   // here you can provide your own Navigator using the component holder of the chosen variant
  .withNavigatorProducer(components -> new Navigator(UI.getCurrent(),components)) 
    // here you can use the initialized Navigator
  .withNavigatorConsumer(navigator -> { /*...*/ })
  ....
  .build()
````

**Comment by migonzap** [comment]
Great, thanks!! 😄

**Comment by appreciated** [comment]
Published!
