### ISSUE TITLE
Default Notification Item description text missing max length

### ISSUE THREAD

**Issue by fo0** [appreciated/vaadin-app-layout#20]
On the Default Notification Item could be a max length (with "..." at the end) and / or a word wrap option, that the full text can be displayed.

![image](https://user-images.githubusercontent.com/11175093/31745598-b5f6d0a4-b463-11e7-85cb-ed00c1aab6c0.png)

used method:

		notificationBar.addNotification(new DefaultNotification(caption, description));

**Comment by appreciated** [comment]
fixed in 9bd18e5
