### ISSUE TITLE
Badge in menu item

### ISSUE THREAD

**Issue by vrepetenko** [appreciated/vaadin-app-layout#200]
**Describe the bug**
Badge is not visible in menu item

**To Reproduce**
```
        LeftClickableComponent clickableMenuItem = new LeftClickableComponent("Item with badge", VaadinIcon.COG.create(),
                clickEvent -> onMenuItemClick());
        clickableMenuItem.setBadgeCaption("10");
```

**Expected behavior**
Badge with 10 caption is visible in clickableMenuItem

**Screenshots**

** Additional Information (please complete the following information):**
 - OS: macOS
 - Browse:r Safari
 - Version: 2.0.2

**Comment by appreciated** [comment]
You need to make the badge visible then it works 
`((MenuBadgeComponent)clickableMenuItem.getBadge()).setVisible(true);`
