### ISSUE TITLE
AppLayoutBuilder Default View

### ISSUE THREAD

**Issue by allenvpn312** [appreciated/vaadin-app-layout#206]
Is there a way to add a default view when initializing the AppLayout using the createAppLayoutInstance()?

Thank you

**Comment by appreciated** [comment]
[The default View is the View that contains the Annotation `@Route` with an empty value. ](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-examples/app-layout-plain-example/src/main/java/com/github/appreciated/example/plain/View1.java#L7)

**Comment by allenvpn312** [comment]
Sorry, I guess I was not clear on my question.  I am able to create the appbar and appmenu sucessfully.  However, let's say I want the body content to default to something, maybe charts and dashboards.  Is there a way to do that rather than having the user click on a LeftNavigationComponent?
