### ISSUE TITLE
App Layout Design

### ISSUE THREAD

**Issue by AyadSunrise** [appreciated/vaadin-app-layout#211]
I have upgraded to Vaadin 10 and app layout 2.0.5 
i don't know which alternative should be use for ( .withDesign(AppLayoutDesign.MATERIAL) )
or how can i change the color off app bar ?

**Comment by appreciated** [comment]
Use the the [Material Theme](https://vaadin.com/themes) that comes with Vaadin. 
For theme check out this issue.
