### ISSUE TITLE
Material Theme?

### ISSUE THREAD

**Issue by jflamy** [appreciated/vaadin-app-layout#212]
There doesn't seem to be an easy way to get the Material theme instead of Lumo; since Paper components are common, and based on Material, it would be nice to be able to select.

**Describe the solution you'd like**
An easy way to switch between Lumo and Material

**Comment by appreciated** [comment]
I just tried using the the material theme that was kind of awful 😬, I added it now but it requires Vaadin 12+.
[Please checkout the example if it is sufficient.](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-examples/app-layout-material-theme-example/src/main/java/com/github/appreciated/example/theme/MainAppLayout.java)

**Comment by appreciated** [comment]
Reopen if solution is not sufficent
