### ISSUE TITLE
JavaScript errors on direct navigation to a page (with minimal setup to reproduce)

### ISSUE THREAD

**Issue by jflamy** [appreciated/vaadin-app-layout#213]
*Minimal setup to recreate a strange interaction between app-layout and crudui
The issue is related to direct navigation to a page using the URL.    Cannot diagnose further. See steps below

Steps to reproduce
•Clone `https://github.com/jflamy/bug_crud.git`
•Run `mvn exec:java` (or start org.ledocte.owlcms.Main from IDE)
•Click on the "Test" button -- observe there is no error message
•Refresh the page (navigating directly to the URL)
•Observe that there is an error message (cannot read property 'map' of null)

Further notes: Does not occur when navigating programmaticallly, or when using a normal grid.

**Comment by appreciated** [comment]
Thanks for providing a minimal example of the bug 👍. Just looking into it.

**Comment by appreciated** [comment]
This issue occurs here:
[grid-connector.js](https://github.com/vaadin/vaadin-grid-flow/blob/master/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L556)
```
    const updateGridItemsInDomBasedOnCache = function(items) {
      ...
      const itemKeys = items.map(item => item.key);
      const indexes = grid._physicalItems
      Here ->  .map((tr, index) => tr._item && tr._item.key && itemKeys.indexOf(tr._item.key) > -1 ? index : null)
          .filter(idx => idx !== null);
      ...
    };
```
Obviously `_physicalItems` is null at some point at runtime.

**Comment by appreciated** [comment]
If I add the following code during runtime via the browser debugger:
![issue-fix](https://user-images.githubusercontent.com/1729845/52534538-129f4f80-2d43-11e9-833a-0fba3ce61840.PNG)
The error does not occur any more. 
[Please file another issue at vaadin-grid-flow](https://github.com/vaadin/vaadin-grid-flow/blob/master/vaadin-grid-flow/)

**Comment by appreciated** [comment]
Closing since this is not an issue of this addon
