### ISSUE TITLE
Use app-layout without AppLayoutRouterLayout

### ISSUE THREAD

**Issue by Springrbua** [appreciated/vaadin-app-layout#216]
**Is your feature request related to a problem? Please describe.**
I tryed to use the `AppLayout` without using the `AppLayoutRouterLayout`, because I don't handle the page content using routes.
I used the `AppLayoutRouterLayout` as a template and my solution works well, until I need to switch the content.
The problem is, that the `setAppLayoutContent`-Method doesn't set, but [add the content](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/java/com/github/appreciated/app/layout/behaviour/AbstractLeftAppLayoutBase.java#L104).
Also, I can't access the `Div content` from outside, so I can't clear it, before adding the new content.
In the `AppLayoutRouterLayout` this is no problem, because the old content is removed in the `UIInternals#showRouteTarget`.

**Describe the solution you'd like**
In my opinion the `setAppLayoutContent`-Method should always clear the current content, since it is named `set`, not `add`.
Another possible solution would be to make the `Div content` accessible by a getter or add a `clearContent`-Method.

**Comment by appreciated** [comment]
How about providing a `CustomAppLayoutRouterLayout` that fixes your issues and providing it for the community?

**Comment by Springrbua** [comment]
@appreciated At the moment this does not seem to be possible, since the `setAppLayoutContent` in the current implementations of the `AppLayout` don't set the content, but add to the content.
The current implementation relies on Vaadins logic which removes the content of a `RouterLayout`, if the route is changed (see [UIInternals#showRouteTarget](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L658-L676)).
This is only possible, if your content is registered using a `@Route`-annotation with a given `layout` class.

So in my opinion, the `setAppLayoutContent` should call `content.removeAll()`, before calling `appendChild`.
If you think thats okay, I'll try to create a pull request.

**Comment by Springrbua** [comment]
My current workaround for this issue looks like this:
```
private AppLayout layout;

public void initAppLayout() {
    this.layout = AppLayoutBuilder.get(...);
}

public void setContent(HasElement content() {
    this.layout.getChildren()
        .filter(child -> "application-content".equals(child.getElement().getAttribute("slot")))
	.forEach(child -> child.getElement().removeAllChildren());
    this.layout.setAppLayoutCOntent(content);
}
```

**Comment by appreciated** [comment]
> So in my opinion, the `setAppLayoutContent` should call `content.removeAll()`, before calling `appendChild`.
> If you think thats okay, I'll try to create a pull request.

@Springrbua  I don't see any problems with that.
