### ISSUE TITLE
issue deploy in production mode 

### ISSUE THREAD

**Issue by Slugger2k** [appreciated/vaadin-app-layout#219]
The deploy in productionmode cause layouting issues.
The layout is completely destroyed.

maven profile: production-mode

**Comment by appreciated** [comment]
Please update the issue description to match the bug issue template.

**Comment by appreciated** [comment]
I was able to reproduce your issue on Version 2.0.7, using plain Jetty. 
Thanks for reporting, but please consider next time providing a proper issue description to give the maintainer more to work with.

**Comment by Slugger2k** [comment]
Ok sorry for that. 
Thank for fixing!
