### ISSUE TITLE
@Viewport annotation on AppLayoutRouterLayout

### ISSUE THREAD

**Issue by ggecy** [appreciated/vaadin-app-layout#220]
**Describe the current way to archive your requirement**
The `AppLayoutRouterLayout` currently has `@Viewport` annotation which makes it impossible to use it as nested layout since viewport annotation can be only on the parent layout. Currently I have to either copy the `AppLayoutRouterLayout` code to create an identical class without viewport or create two top level layouts which duplicates security handling code. My idea is using a parent layout which is a place for "full screen" views and handles a security as well and then the app layout references it as parent layout through `@ParentLayout(MainLayout.class)`, making use if its security handling.

**Describe the solution you'd like**
Remove the `@Viewport` from `AppLayoutRouterLayout` and create another abstract class extending from it which adds the `@Viewport` so user can choose which one to inherit from.

**Target Version**
Latest.

**Comment by appreciated** [comment]
This Layout was never meant to be used in an nested environment. If you want this feature part of this Addon you need to test and maintain it yourself. I will not add support for this personally.

**Comment by appreciated** [comment]
closed by #221
