### ISSUE TITLE
CSS Custom Properties do net get applied

### ISSUE THREAD

**Issue by Juchar** [appreciated/vaadin-app-layout#225]
**Describe the bug**
Specifying custom properties in the `shared-styles.html` and importing them on the `AppLayoutRouterLayout` using `@HtmlImport` does not apply the values.

It seems that the properties of the `shared-styles.html` are imported by the browser before those provided by the addon. By consequence the addon overrides them again.

**To Reproduce**
1. Check out the spring example
2. Add a `shared-styles.html` to the directory `resources/META-INF.resources/frontend/styles` with the following content:
```
<custom-style>
  <style>
    html {
      --app-layout-bar-background-base-color: var(--lumo-primary-color);
      --app-layout-bar-background-color: var(--lumo-primary-color);
      --app-layout-bar-font-color: var(--lumo-primary-contrast-color);
    }
  </style>
</custom-style>
```
3. Create a class `MyAppRouterLayout`:
```
@Push
@HtmlImport("frontend://styles/shared-styles.html")
public class MyAppRouterLayout extends AppLayoutRouterLayout {

  public MyAppRouterLayout() {
    DefaultNotificationHolder notifications = new DefaultNotificationHolder(newStatus -> {
    });
    for (int i = 1; i < 6; i++) {
      notifications.addNotification(new DefaultNotification("Test title" + i,
          "A rather long test description ..............." + i));
    }

    init(AppLayoutBuilder.get(Behaviour.LEFT_RESPONSIVE_HYBRID)
        .withTitle("App Layout")
        .withAppBar(AppBarBuilder.get()
            .add(new AppBarNotificationButton(VaadinIcon.BELL, notifications))
            .build())
        .withAppMenu(LeftAppMenuBuilder.get()
            .build())
        .build());
  }
}
```
4. Add the following route definition on the main view:
`@Route(value = "", layout = MyAppRouterLayout.class)`

5. Open the web application
6. See that the menu bar is not in the primary color.

**Expected behavior**
Custom CSS Properties get applied.

**Screenshots**
![image](https://user-images.githubusercontent.com/14292982/53571894-3e576d80-3b6a-11e9-9027-c97413307e55.png)
![image](https://user-images.githubusercontent.com/14292982/53571857-2d0e6100-3b6a-11e9-841a-9e9949a39ab1.png)
![image](https://user-images.githubusercontent.com/14292982/53571832-1cf68180-3b6a-11e9-9bc5-432596757c27.png)

**Additional Information:**
 - OS: Windows
 - Browser: Chrome 72
 - App-Layout - Version: 2.0.8

**Comment by Juchar** [comment]
Just tried with 2.0.7, seems to work (simply changed the version in the pom).
![image](https://user-images.githubusercontent.com/14292982/53572498-a9ee0a80-3b6b-11e9-9298-e24db97f5c5f.png)

**Comment by appreciated** [comment]
change `html` -> `.app-layout.lumo` and you should be good to go

**Comment by appreciated** [comment]
This change was necessary due to #219

**Comment by Juchar** [comment]
Perfect, both of them work. Thank you very much!
