### ISSUE TITLE
Profile Button Component

### ISSUE THREAD

**Issue by appreciated** [appreciated/vaadin-app-layout#226]
Many web applications these days offer a button in the app bar to with the user icon.

**Comment by Springrbua** [comment]
I am already using a "Profile Button" with a `ContextMenu` in the current version of this add-on, so implementig this is easily possible.
But the plugin could provide an API for that and adapt it to different behaviours.

**Comment by appreciated** [comment]
> I am already using a "Profile Button" with a ContextMenu in the current version of this add-on
I've already integrated the `paper-menu-button` for Vaadin which's popup behaviour I prefer over the `ContextMenu`. 

But using the `ContextMenu` will reduce the support (f.e. proper styling) and reduce the need in documentation, which is always a good thing. 
When using `ContextMenu` the NotificationButton will also get replaced.

**Comment by watho** [comment]
I'd like to see an implementation without context-menu on right button click. My experience is that people don't expect any special menu inside browsers and always need a reminder for that. Because of that we avoid implementing them. It usually also doesn't work well on mobile devices.

With your vaadin8-version i had integrated the PopupButton-addon https://vaadin.com/directory/component/popupbutton into the top bar. Something like that would be my preferred implementation.

**Comment by Springrbua** [comment]
@watho the vaadin ContextMenu can be openend on left-click as well.
What I like about it is it's appearance on mobile devices.

**Comment by watho** [comment]
Oh, thanks for the information. I have to admit i don't tried this yet.

**Comment by appreciated** [comment]
> What I like about it is it's appearance on mobile devices.

The `paper-menu-button` works very well on mobile devices too. But yes it isn't sliding in from the bottom 😉.

**Comment by Springrbua** [comment]
> The paper-menu-button works very well on mobile devices too

The `paper-menu-button` seems to be similar to the `Menu` in [Material Design Guidelines](https://material.io/design/components/menus.html#usage). I am using this kind of menu as Profile menu in a few `Angular`-based web-applications.

> When using ContextMenu the NotificationButton will also get replaced.
In my case, I did not need the notification icon, but I guess it shouldn't be a big problem to have notification + account button next to each other.

The current implementation of the `AppBar` let you set a `Component` for the right part of the `AppBar`, so you are pretty free to implement whatever you want (more or less).
So I am pretty sure, that creating a `ProfileButton` (with `paper-menu-button` or Vaadin `ContextMenu`) next to the `NotificationButton` should be pretty easy.

**Comment by appreciated** [comment]
Postponed to 3.0.0 since the ContextMenu is not part of Vaadin 10

**Comment by appreciated** [comment]
fixed by 0964f594bfaa829a61c02bd29bc7063f06bb9d31
