### ISSUE TITLE
ContextMenu in AppBar causes error

### ISSUE THREAD

**Issue by Springrbua** [appreciated/vaadin-app-layout#228]
**What is it you are trying to archive?**
I have a `Button` in the `AppBar` of the `AppLayout`. This `Button` is the target of a `ContextMenu`.
Now I noticed, that if the `ContextMenu` is open, the `Button` still gets the click-events and tryes to open the `ContextMenu`, which results in an error.
I wanted to reproduce this bug to create an Issue in the `ContexMenu` repository, but I was not able to reproduce the error without using the `AppLayout`.
When I am placing a `Button` inside a `VerticalLayout` (for example) and create the `ContextMenu`, the `Button` does not get the click events (or hover effects), as long as the `ContextMenu` is open.
If the `Button` is placed in the `AppBar` of the `AppLayout` instead, it will get click events and the hover affect is applied, like if it is above the `ContextMenuOverlay`.

Sample code:

```
public class MainView extends AppLayoutRouterLayout {
	public MainView() {
		Button btn = new Button(new Icon(VaadinIcon.VAADIN_H));
		ContextMenu menu = new ContextMenu(btn);
		menu.setOpenOnClick(true);
		menu.addItem("Test", event -> {});
		setLayout(AppLayoutBuilder.get(Behaviour.LEFT_RESPONSIVE)
			.withTitle("Test")
			.withAppBar(AppBarBuilder.get().add(btn).build())
			.build()
		);
	}
}
```

Steps to reproduce:

1. Run a project (Vaadin 13) with the code posted above.
2. Open the `ContextMenu` by clicking the `Button`
3. Click the `Button´ again, while the `ContextMenu` is open.

Working sample code:

```
public class MainView extends HorizontalLayout {
	public MainView() {
		Button btn = new Button(new Icon(VaadinIcon.VAADIN_H));
		ContextMenu menu = new ContextMenu(btn);
		menu.setOpenOnClick(true);

		menu.addItem("Item 1", event -> {});
		menu.addItem("Item 2", event -> {});
		add(btn);
	}
}
```

If you use this code, the `Button` does not have any hover effects and won't get the click event.

Note, that in Vaadin 12, there was no error, but still the `Button` got the hover effect like if it was above the `ContextMenuOverlay`.

Do you have any idea what may cause this?

**Comment by appreciated** [comment]
Woah that sounds wierd. This may be connected to some of the `iron-behavior` dependencies that are used by the `app-layout`, just a guess, currently I also clueless. 
Would you mind providing an example project?

**Comment by Springrbua** [comment]
You can simply download the [Project Base for Vaadin 13](https://vaadin.com/start/latest/project-base) and copy the code from above into the `MainView`.
Of course you must first add the add-on to the `pom.xml`.

**Comment by appreciated** [comment]
@Springrbua When using you example I get the following error:
![error](https://user-images.githubusercontent.com/1729845/54024943-5f871200-4199-11e9-89aa-0f9d73e22c46.PNG)

**Comment by Springrbua** [comment]
The `TypeError` is probably an issue of the `ContextMenu`, as in Vaadin 12, there was no error.
But the strange thing is, that the `Button` normally does not get the click event and so the bug does not occure. But when you are using it inside the `AppBar`, it gets the click events, as if it was above the `ContextMenuOverlay`.
You can verify that by opening the `ContexMenu` and hovering over the `Button`. You will see the normal hover effect.
Now if you use a `Button` and a `ContextMenu` outside the `AppBar`, the `Button` won't get the hover effect, if the `ContextMenu` is open.

Screenshots:
Normal behaviour, no hover-effect:
![image](https://user-images.githubusercontent.com/18258317/54030994-b1d22e00-41ad-11e9-95b5-125c0add2514.png)

Behaviour in `AppBar`, the `Button` is blue cause of the hover-effect:
![image](https://user-images.githubusercontent.com/18258317/54033180-e2b56180-41b3-11e9-8a5b-6c436e0faf90.png)


Note, that I changed the hover-effect, so that the difference between the screenshots is clear.

**Comment by appreciated** [comment]
The reason for this is that the hover is not triggered on the `normal` behavior. If the `:hover` state is toggled they both behave the same. 
I guess this has something to do with the `z-index` and/or the `position` of the `app-bar`.

**Comment by Springrbua** [comment]
I can't find the element you are talking about.
There are only 3 "top-level" elements:
- The actualy content (`vaadin-vertical-layout`)
- The `vaadin-context-menu` which has `height: 0px`
- The `vaadin-context-menu-overlay`, which does not fully cover the `Button`
![image](https://user-images.githubusercontent.com/18258317/54038795-ae48a200-41c1-11e9-977b-04b07928c16f.png)

My guess is also, that it has something to do with the `z-index` or the `position` of the `app-bar` or even the whole `app-layout`.
It's not a big issue in this case, except for the error, which is probably a bug of the `ContextMenu`.
But if the `ContextMenu` behaves somehow different when used inside the `app-layout`, other components might cause some issues too.
Thats why I wanted to investigate this behaviour.

**Comment by appreciated** [comment]
When opening an context menu, the body style `pointer-events: none` does somehow not apply to the elements in the app-bar.

**Comment by appreciated** [comment]
I think this can corrected pretty easily by overwriting it in every menu with:

```
:host ::slotted(*) {
  pointer-events: inherit;
}
```

**Comment by Springrbua** [comment]
@appreciated thanks for investigating!
