### ISSUE TITLE
Add additional behaviour

### ISSUE THREAD

**Issue by Juchar** [appreciated/vaadin-app-layout#229]
**Describe the current way to archive your requirement**
Did not find a way.

**Describe the solution you'd like**
I want to be able to have a behaviour that is a mix of `LEFT` and `LEFT_HYBRID_SMALL`.
It should just behave like the `LEFT_HYBRID_SMALL`, but if I click on the hamburger instead of pushing the content aside, it would be nice if the menu is slide-open as an overlay just the way it is for `LEFT`.

**Additional context**
None

**Target Version**
As soon as possible of course :stuck_out_tongue: . Just kidding. You sure you want to keep this section?

**Comment by appreciated** [comment]
> As soon as possible of course 😛
😁 
How about making a pull request? The feature list is currently pretty long. Vaadin 13 just released, #175 and #205 have a higher priority. Also there are other features, which I liked to see in this project (#227, #134, #190) meaning this will not be added soon. 

Adding another behaviour is actually not too complicated but requires a lot of testing and css optimization.

**Comment by Juchar** [comment]
Thank you for the quick response!
I unfortunately do not have the time myself right now. But if I find spot, I will definitely try it.

**Comment by appreciated** [comment]
Closing for same reason as #263
