### ISSUE TITLE
Vaadin Production Mode corrupts Menu Layout with Behaviour.LEFT_HYBRID_SMALL

### ISSUE THREAD

**Issue by Juchar** [appreciated/vaadin-app-layout#230]
**Describe the bug**
The label of the menu items is partly visible if using the behaviour `LEFT_HYBRID_SMALL` and executing the application in production mode.

**To Reproduce**
1. Create an application using `AppLayoutRouter` using one of the vaadin starter packs.
2. Use the behaviour `LEFT_HYBRID_SMALL`:
```
@Push
public class MyAppLayoutRouterLayout extends AppLayoutRouterLayout {

  public MyAppLayoutRouterLayout() {
    init(AppLayoutBuilder
        .get(Behaviour.LEFT_HYBRID_SMALL)
        .withTitle("App Layout")
        .withAppBar(AppBarBuilder.get().build())
        .withAppMenu(LeftAppMenuBuilder.get()
            .add(new LeftNavigationComponent("Home", VaadinIcon.HOME.create(), MainView.class))
            .add(new LeftNavigationComponent("Home", VaadinIcon.HOME.create(), MainView.class))
            .add(new LeftNavigationComponent("Home", VaadinIcon.HOME.create(), MainView.class))
            .add(new LeftNavigationComponent("Home", VaadinIcon.HOME.create(), MainView.class))
            .build())
        .build());
  }
}
```
3. Compile the application with the maven profile `production-mode` enabled.
4. Start the application with the property `-Dvaadin.productionMode=true`
5. Navigate to the view.
6. See error on the menu bar.

**Expected behavior**
The labels should not be visible at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/14292982/54028332-f3121000-41a4-11e9-8548-6cab6f6c4927.png)

**Additional Information (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version:  Vaadin: `13.0.0`, Addon: `2.0.8`

**Attention: This does not happen without production mode.**

**Comment by appreciated** [comment]
reopen if it won't be fixed by #175
