### ISSUE TITLE
Clicking a menu button does not switch the view

### ISSUE THREAD

**Issue by Juchar** [appreciated/vaadin-app-layout#233]
**Describe the bug**
Clicking a menu button outside of a small area inside the icon does not trigger a view switch if using behaviour `LEFT_HYBRID_SMALL`. **Nevertheless the clicked item gets marked as selected visually.**

**To Reproduce**
1. Create an App Layout with some views and the mentioned behaviour.
2. Click not in the exact center of the icon.
3. See above mentioned bug

**Expected behavior**
Clicking outside of the icon (if the hover animation is triggered) I would expect the view swicth to happen.
The hover animation indicates to the user that it can be clicked.

**Screenshots**
![localhost_8080 (1)](https://user-images.githubusercontent.com/14292982/54258755-e7876600-4563-11e9-8bf0-ebc1c12f44b9.gif)

**Additional Information (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Vaadin: `13.0.0`, App Layout: `2.0.8`

**Comment by appreciated** [comment]
Will be closed by #175

**Comment by appreciated** [comment]
Closing in favor of #175
