### ISSUE TITLE
Some Behaviors do not present content in Edge Browser

### ISSUE THREAD

**Issue by appreciated** [appreciated/vaadin-app-layout#236]
**Describe the bug**
The following behaviors:
* LEFT_RESPONSIVE
* LEFT_RESPONSIVE_HYBRID
* LEFT_RESPONSIVE_HYBRID_NO_APP_BAR
* LEFT_RESPONSIVE_OVERLAY_NO_APP_BAR

do not present their content in the content area. Instead the area is left just blank. 

** Additional Information (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: Master

Originally reported by @cedricaebi in #134.

**Comment by appreciated** [comment]
@cedricaebi this happened due to the `<slot>` tag unnecessarily being wrapped twice in some cases. Interestingly this only caused issue on Edge. 

Before fix:
````
<div class="application-content" size="100" part="application-content" id="content">
  <slot>
    <slot name="application-content"></slot>
  </slot>
</div>
```

After fix:
````
<div class="application-content" size="100" part="application-content" id="content">
  <slot name="application-content"></slot>
</div>
```

**Comment by cedricaebi** [comment]
@appreciated  Thanks for the extremely fast fix!
