### ISSUE TITLE
Change Breakpoint for Responsive Layouts

### ISSUE THREAD

**Issue by Springrbua** [appreciated/vaadin-app-layout#237]
**Problem**
I am using the [Breakpoints from Material Design Guidelines](https://material.io/design/layout/responsive-layout-grid.html#breakpoints) to change layouts based on the available width.
Those Breakpoints define XS as `< 600px`, while the `app-drawer-layout` defines his `responsiveWidth` as `640px`.

**Possible solution**
All the `LeftResponsive*`-Layouts should have an API to set the `responsiveWidth`.
The `responsiveWidth` is a property of the `app-drawer-layout` and defaults to `640px`.
Also the `style` of all the `left-responsive*.html`-Files has to be updated, as it contains a media-query with those 640px.
Also the `left-responsive*.css`-Files may need to be updated, as they contain media queries as well.
But it might be a good idea to remove them and add the content to the `*.html`-File instead, as only `@HtmlImport`s seems to be used for vaadins theme-logic.

**Comment by Springrbua** [comment]
I implemented this feature for `app-layout-left-responsive`.
@appreciated Can you take a look at the commit in my fork and tell me if the modifications are okay for you?
I will then update the other behaviours to use this new feature.

**Comment by appreciated** [comment]
Look very promising! The changes are fine as long as Internet Explorer can be supported!

**Comment by Springrbua** [comment]
@appreciated can you explain the limitations of Internet Explorer, which I could face here?

**Comment by appreciated** [comment]
We'll as you probably already know IE only supports Webcomponents via Polyfills. But there are still some webcomponents which do not even support IE 11. So when adding new webcomponents it is necessary to test the support and their integration with IE thoroughly.

**Comment by Springrbua** [comment]
Thanks for the info.
I don't think the logic I added causes IE 11 issues, as the only new webcomponent I am using is `iron-media-query`, which is already in use by `app-drawer-layout`.
