### ISSUE TITLE
Size of app-drawer larger than application-content in app-drawer-layout

### ISSUE THREAD

**Issue by marsenman** [appreciated/vaadin-app-layout#240]
Describe the bug:
I have a view with four rows of vaadin board and each contains a subview. Two of the views include charts which are filled and drawn when setParameter of HasUrlParameter interface is called.

Afterwards there are two visible scrollbars. One for the application-content and one for the larger sized app-drawer with overlapping white space.

![image](https://user-images.githubusercontent.com/47820887/54908067-5612df00-4ee7-11e9-8eb3-2dee00418a78.png)

![image](https://user-images.githubusercontent.com/47820887/54908111-6b880900-4ee7-11e9-944a-bb66fd521af6.png)

The outer scrollbar disappears when I hide the contents of my chart subviews.

![image](https://user-images.githubusercontent.com/47820887/54908136-7cd11580-4ee7-11e9-8e4c-7c3676880aaa.png)

One thing I did found out: Removing the fullbleed attribute in debug is setting the application-content to full size.
<app-drawer-layout id="drawerLayout" **fullbleed**>

Additional Information (please complete the following information):
OS: Windows
Browser: Chrome
Version: Vaadin: 13.0.1, App Layout: 2.0.8

**Comment by appreciated** [comment]
@marsenman did you set the content to full height?

**Comment by marsenman** [comment]
The form and underlying board are set to height 100%.

**Comment by cedricaebi** [comment]
Adding: what i noticed is that the prompt to install the PWA is below the visible area of the app content-area

**Comment by marsenman** [comment]
I've removed the PWA stuff but this white area still remains.

**Comment by appreciated** [comment]
I will need an example project to be able to reproduce this issue

**Comment by marsenman** [comment]
I have changed the bakery example and added your app-layout-addon. You can see the effect on the dashboard page when the smaller hybrid menu is visible.

[bakery_with_app_layout.zip](https://github.com/appreciated/vaadin-app-layout/files/3022010/bakery_with_app_layout.zip)

Thx for investigating!

**Comment by appreciated** [comment]
@marsenman thanks for your time, 2.1.0 will fix this issue!
