### ISSUE TITLE
Submenu font color is darker

### ISSUE THREAD

**Issue by lucastanzani** [appreciated/vaadin-app-layout#242]
**Describe the bug**
I suppose it's a minor bug, but still i think it's good to report it.
The submenu font color is darker (it seems it doesn't get stiled with the --secondary-text-color var)

**To Reproduce**
Create a submenu and run with -Dvaadin.productionMode.

**Expected behavior**
It should look like other menu entries, as it is in development mode.

**Screenshots**
<img width="258" alt="Schermata 2019-03-27 alle 14 11 09" src="https://user-images.githubusercontent.com/26148265/55078465-86e74580-509a-11e9-913e-42b62854d55d.png">

** Additional Information (please complete the following information):**
 - OS: MacOs Mojave
 - Browser Chrome 73

Thank you!

**Comment by appreciated** [comment]
will be fixed by #175

**Comment by appreciated** [comment]
Closing in favor of #175
