### ISSUE TITLE
Bad path to custom-style.html in app-layout-styles.html

### ISSUE THREAD

**Issue by pvnhome** [appreciated/vaadin-app-layout#246]
We have bad path "../../../../../../bower_components/polymer/lib/elements/custom-style.html" in app-layout-styles.html

This were introduced here https://github.com/appreciated/vaadin-app-layout/commit/97bbf1be10111655fc01e0e4d4d6ae9a0cf0fb24#diff-e992188001a87d644c1bea8fac639b92

Path must be "../../../../../bower_components/polymer/lib/elements/custom-style.html"

**Comment by appreciated** [comment]
@pvnhome Thank you for reporting 🙏. 
Note: The master branch is currently not meant for production use.
