### ISSUE TITLE
Pagetabs navigation

### ISSUE THREAD

**Issue by rucko24** [appreciated/vaadin-app-layout#247]
Hello, what a great add-on I really like, I almost always use it,
How could it be programmed so that the navigation menu uses PageTabs,, and each item in the menu corresponds to its Tab.

https://vaadin.com/directory/component/paged-tabs

![tabsVaadin](https://user-images.githubusercontent.com/17187599/55672456-a00ea400-589b-11e9-94d7-c6434b21ba9d.gif)

**Comment by appreciated** [comment]
@rucko24 have you tried the TOP Behaviors? It should be exactly what you are looking for.

**Comment by appreciated** [comment]
Reopen if relevant again.
