### ISSUE TITLE
Toggle drawer 

### ISSUE THREAD

**Issue by JohnnyBeGood70** [appreciated/vaadin-app-layout#248]
Hi,

thanks a lot for this great add on! I use it with vaadin 10.

I couldn't find the right layout behaviour for myself. I would like to use a behaviour without app bar. But in an intermediate layout (mobile landscape mode) the left menu has only icons. If there is app bar, there is a button on the left to expand the drawer to see the menu titles too, but in no app bar mode there is no such option. I don't want app bar in landscape mode because it covers too much useful display area.

Is there a way for example to add a button to the menu to toggle the expand of the drawer? Or just to keep this button from the app bar?

Thanks

**Comment by appreciated** [comment]
>  I don't want app bar in landscape mode because it covers too much useful display area.
Sounds like you should create a special behaviour that covers your requirements. 

>Is there a way for example to add a button to the menu to toggle the expand of the drawer? Or just to keep this button from the app bar?
checkout if issue #30 can help.
