### ISSUE TITLE
Is there a way to remove item attached to app menu header when drawer is small?

### ISSUE THREAD

**Issue by turgos** [appreciated/vaadin-app-layout#251]
As shown below snipped, we attach a logo to HEADER Section, and we don't want to display that logo when drawer is small (Display only when drawer is normal size).

```
AppLayout layout = AppLayoutBuilder
            .get(variant)
            .withTitle("Project")
            .withAppBar(appBar)
            .withDesign(AppLayoutDesign.MATERIAL)
            .withAppMenu(LeftAppMenuBuilder
                    .get()
                    .addToSection(Logo, HEADER)
                    .add(new LeftNavigationComponent("Menu1", VaadinIcon.COGS.create(), View.class))
                    .add(new LeftNavigationComponent("Menu2", VaadinIcon.AUTOMATION.create(), View2.class))
...
```

Thank you in advance.

**Comment by appreciated** [comment]
Which behavior are you using?

**Comment by turgos** [comment]
variant = Behaviour.LEFT_HYBRID;

**Comment by appreciated** [comment]
Some css as `app-layout-left-hybrid[narrow] { ... }` should do the job.

**Comment by turgos** [comment]
I couldn't make it work. Is it possible for you to give an example?
Logo element is defined like below. Where should I that css and how?

<link rel="import" href="../polymer/polymer-element.html">

<dom-module id="logo-element">
  <template>
    <style>
      :host {
        display: block;
      }
      #logo-container {
        margin: 16px;
      }
      #logo {
        width: 150px;
        height: 75px;
      }
      
      
    </style>
    <div id="logo-container">
      <img id="logo" slot="right" src="images/logo.png">
    </div>
  </template>

  <script>
    /**
     * `logo-element`
     * responsive logo
     *
     * @customElement
     * @polymer
     * @demo demo/index.html
     */
    class LogoElement extends Polymer.Element {
      static get is() { return 'logo-element'; }
      static get properties() {
        return {
          prop1: {
            type: String,
            value: 'logo-element'
          }
        };
      }
    }

    window.customElements.define(LogoElement.is, LogoElement);
  </script>
</dom-module>

**Comment by appreciated** [comment]
> Where should I that css and how?

In the style section?

```
<dom-module id="logo-element">
  <template>
    <style>
    <!-- Here -->
    </style>
    ...
</dom-module>
```
