### ISSUE TITLE
Menu item is not highlighted when using @RouteAlias

### ISSUE THREAD

**Issue by Juchar** [appreciated/vaadin-app-layout#253]
**Describe the bug**
If using a `@RouteAlias` the menu item related to the view does not get highlighted.

From my **very short** analysis the root cause might be inside `com.github.appreciated.app.layout.router.navigation.UpNavigationHelper#shouldHighlight` at
`HashMap<Class<? extends Component>, String> routes = getUpNavigationHelper().registeredRoutes;`.

It seems that the routes do not contain the aliases. Maybe you could use `RouteConfiguration.forRegistry(event.getSource().getRegistry()).getAvailableRoutes()` instead? Then you could pass the returned `RouteData` to `RouteSimilarity`. Nevertheless `RouteSimilarity` would need to handle the aliases returned by `RouteData.getRouteAliases()`.

**To Reproduce**
1. Add a view using an `@RouteAlias`
2. Navigate to the view using the alias in the url
3. Menu item is not highlighted.

**Expected behavior**
The menu item should be highlighted the same way it is using the normal route url.

**Additional Information (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Vaadin 13.0.3, Addon: 2.0.1.beta1

**Comment by appreciated** [comment]
Your fix is only a fix for the master branch. The master branch is currently only even with the V13+ Branch meaning that this can only be shipped with Version 3.0+.

**Comment by Juchar** [comment]
I have additionally made the made the changes for the V-10 branch.
