### ISSUE TITLE
Firefox 60 compatibility

### ISSUE THREAD

**Issue by Slugger2k** [appreciated/vaadin-app-layout#256]
Is Firefox 60 ESR working with the applayout?

I tried it with my own app and the demo app. The menu is shown but the views stay empty.

![Screenshot](https://i.ibb.co/rQGKmqW/Bildschirmfoto-vom-2019-04-12-15-44-35.png)

**Comment by appreciated** [comment]
Have not tested it :unamused:

**Comment by appreciated** [comment]
So just checked it, by downloading a portable version, everything will work with 2.1. But 60ESR might suffer from the same issue as Edge which is described in #236.
