### ISSUE TITLE
Padding in the AppBar

### ISSUE THREAD

**Issue by Springrbua** [appreciated/vaadin-app-layout#260]
**Describe the bug**
Since Version 3.0.0.beta1, the AppBar has no more padding.
This causes the title to be stuck on the left border.
The changes that cause this bug were probably introduced by 385b6a302b28989915bac0c66d56b037ad83853b, which changed `padding: 0 0 0 16px` to `padding: 0` for CSS-Selector `app-toolbar`.
Instead, the `#toggle` and the icon in the title got a `margin`.

**To Reproduce**
1. Open the demo
2. Use the developertools to remove the margin of the icon in the title

**Expected behavior**
The `app-toolbar` should use a padding of `16px` on both sides as specified in the [material design guidelines](https://material.io/design/components/app-bars-top.html#specs).
If a user does not like this behaviour, he could simply apply a negative margin or overwrite the style for the `app-toolbar`.

**Screenshots**
Before the changes:
![image](https://user-images.githubusercontent.com/18258317/56265842-017c1180-60eb-11e9-8948-0b31d9d9fc08.png)

After the changes:
![image](https://user-images.githubusercontent.com/18258317/56265860-0ccf3d00-60eb-11e9-8171-4b173ed180e0.png)

**Additional Information (please complete the following information):** 
 - Version 3.0.0.beta1 and newer

**Comment by Springrbua** [comment]
@appreciated fixing the issue shouldn't be that hard, but I guess there was a reason for removing it.
So I would like to hear your opinion on that, before trying to fix it.

**Comment by appreciated** [comment]
> I guess there was a reason for removing it.
I already responded to this.
> @Springrbua This is probably related to introduction of #190. I needed to replace the HorizontalLayout with FlexLayout to support changing the flex-direction please open another issue for this. FlexLayout does not have a setSpacing() method.

During the development of #190 I decided to remove the padding, since using a `SMALL_RESPONSIVE` / `HYBRID_RESPONSIVE` combined with an icon will cause the Icon to be aligned wierdly with the menu. Adding some spacing to the Label should be suffient.
