### ISSUE TITLE
Material Design 2 Style

### ISSUE THREAD

**Issue by Juchar** [appreciated/vaadin-app-layout#263]
**Describe the current way to archive your requirement**
I created some styles that I am using in my application to have a menu that looks like the "new" material design **2** layout as seen e.g. in Gmail. The current styles work with the layout `LEFT_RESPONSIVE_HYBRID`.

I do not know if you are interested in including this as a theme to the addon. I do not know where exactly to put it and how to include it, otherwise I would have created a pull request.

The usage is as follows (see the line where setting the theme):
```java
@HtmlImport("frontend://styles/shared-styles.html")
public class MyAppLayoutRouterLayout extends AppLayoutRouterLayout {

  public MyAppLayoutRouterLayout() {
    ScrollUtils.addClassOnScroll(getElement(), ".app-layout > [slot=\"application-content\"]",
        ".app-layout", "scrolled");
    
    AppLayout appLayout = AppLayoutBuilder
        .get(Behaviour.LEFT_RESPONSIVE_HYBRID)
        .withTitle("App Layout")
        .withAppBar(AppBarBuilder.get().build())
        .withAppMenu(LeftAppMenuBuilder.get()
            .add("Home", VaadinIcon.HOME.create(), MainView.class)
            .add("View 1", VaadinIcon.CHART.create(), View1.class)
            .add("View 2", VaadinIcon.WRENCH.create(), View2.class)
            .add(LeftSubMenuBuilder.get("Sub Menu", VaadinIcon.PLUS.create())
                .add(new LeftNavigationItem("Sub 1", VaadinIcon.PLAY.create(), View3.class))
                .add(new LeftNavigationItem("Sub 2", VaadinIcon.AIRPLANE.create(), View4.class))
                .add(LeftSubMenuBuilder.get("Sub Sub Menu", VaadinIcon.PLUS.create())
                    .add(new LeftNavigationItem("Sub Sub 1", VaadinIcon.CHART.create(), View5.class))
                    .add(new LeftNavigationItem("Sub Sub 2", VaadinIcon.LIGHTBULB.create(), View6.class))
                    .build())
                .build())
            .build())
        .build();

    appLayout.getElement().setAttribute("theme", "material-design-2");
    init(appLayout);
  }
}
```

I additionally created a small helper class that will append a `scrolled` class to the `app-layout` if the content is scrolled to be able to create a drop shadow only if the content is scrolled up:

```java
public final class ScrollUtils {

  private ScrollUtils() {
    // Prevent instantiation
  }

  public static void addClassOnScroll(Element parent, String querySelector,
      String targetQuerySelector, String className) {
    parent.executeJavaScript("var elem = document.querySelector($0);"
        + "var targetElem = document.querySelector($1);"
        + "elem.addEventListener('scroll', function(){"
        + "if(elem.scrollTop > 0) {"
        + "targetElem.classList.add($2);"
        + "} else {"
        + "targetElem.classList.remove($2);"
        + "}"
        + "})", querySelector, targetQuerySelector, className);
  }
}
```

**Additional context**
The result looks as follows:
![image](https://user-images.githubusercontent.com/14292982/56357823-1933c280-61dd-11e9-8933-7156b0d4622b.png)
![image](https://user-images.githubusercontent.com/14292982/56357845-2650b180-61dd-11e9-99fd-f3137a6967c8.png)
![image](https://user-images.githubusercontent.com/14292982/56357871-3d8f9f00-61dd-11e9-97aa-02187b6b4dfb.png)
![image](https://user-images.githubusercontent.com/14292982/56357915-58faaa00-61dd-11e9-8f1a-06d3f96c705e.png)

**Styles** (shared-styles.html)
```html
<link rel="import" href="../polymer/lib/elements/custom-style.html">
<link rel="import" href="../polymer/lib/elements/dom-module.html">

<custom-style>
  <style>
    .app-layout[theme~="material-design-2"] {
      --app-layout-bar-shadow: 0px 1px 0px 0px var(--lumo-contrast-10pct);
      --app-layout-drawer-shadow: none;
    }

    .app-layout[theme~="material-design-2"].scrolled {
      --app-layout-bar-shadow: var(--lumo-box-shadow-s);
    }

    .app-layout[theme~="material-design-2"][narrow] {
      --app-layout-drawer-shadow: var(--lumo-box-shadow-s);
    }

    .app-layout[theme~="material-design-2"] .app-menu-item {
      transition: padding .2s, background .5s;
      cursor: default !important;
    }

    .app-layout[theme~="material-design-2"][narrow] .app-menu-item,
    .app-layout[theme~="material-design-2"][wide] .app-menu-item {
      border-top-right-radius: calc(var(--app-layout-menu-button-height) / 2);
      border-bottom-right-radius: calc(var(--app-layout-menu-button-height) / 2);
    }

    .app-layout[theme~="material-design-2"][narrow] .app-menu-item + iron-icon,
    .app-layout[theme~="material-design-2"][wide] .app-menu-item + iron-icon {
      right: calc(var(--app-layout-menu-button-height) / 4) !important;
    }

    .app-layout[theme~="material-design-2"] .app-menu-item:hover,
    .app-layout[theme~="material-design-2"] .app-menu-item[highlight] {
      text-decoration: none !important;
    }

    .app-layout[theme~="material-design-2"] .app-menu-item label {
      cursor: default !important;
    }

    .app-layout[theme~="material-design-2"] [slot="collapsible"] .app-menu-item {
      border-radius: var(--app-layout-menu-button-border-radius);
    }

    .app-layout[theme~="material-design-2"] [slot="collapsible"] .app-menu-item + iron-icon {
      right: var(--app-layout-menu-toggle-button-padding) !important;
    }

    .app-layout[theme~="material-design-2"] [slot="collapsible"] {
      box-shadow: inset 0 var(--app-layout-space-s) 0 0 var(--lumo-base-color);
    }

    .app-layout[theme~="material-design-2"] [slot="collapsible"]:before {
      width: 100%;
      height: var(--app-layout-space-s);
      border-radius: 0;
      background-color: var(--lumo-base-color);
      content: '';
      margin-top: 0;
      margin-bottom: calc(var(--lumo-space-s) * -1);
    }
  </style>
</custom-style>

<dom-module id="app-layout-material-design-2" theme-for="app-layout-left-responsive-hybrid">
  <template>
    <style>
      :host([theme~="material-design-2"]) app-toolbar {
        transition: box-shadow 1s;
      }

      :host([theme~="material-design-2"]) ::slotted([slot=app-bar-content]) {
        padding-left: calc(var(--app-layout-space-s) * 2);
      }

      :host([theme~="material-design-2"]) ::slotted([slot=drawer-content]) {
        padding-top: var(--lumo-space-s);
      }

      :host([theme~="material-design-2"]) ::slotted([slot=application-content]) {
        box-sizing: border-box;
        overflow-y: auto;
      }

      :host([theme~="material-design-2"][wide]) ::slotted([slot=application-content]) {
        padding-left: var(--lumo-space-m);
      }
    </style>
  </template>
</dom-module>
```

**Comment by Springrbua** [comment]
@Juchar thanks for sharing this, it looks pretty cool!
This is the first time I hear about _Material Design 2_ and of course I had to read a little about it.
The Material Design Guidelines don't seem to include it (yet) and Google itself is not officially speaking of Material Design 2.
To me it seems like some kind of variation of the classic Material Design, similar to the [Material Design Stuides](https://material.io/design/material-studies/).
That said, I personally wouldn't include it in the repository but would preffer to add it to the wiki, as it shows how to create a custom `material` / `lumo` variation.
Thats just my personal opinion though.

**Comment by appreciated** [comment]
This addon currently does have any given way to add theme variations to it.  I guess this can be added as a theme variant. F.e. As the [Vaadin Button have also different themes](https://vaadin.com/components/vaadin-button/html-examples/button-theme-variants-demos). 
Note that there is a difference between the "application theme" and the "component theme". So after adding this as a theme there will be a default (none) theme and a new theme let's call it `round-menu-items` for the moment. 

Before this can be added it must be clear that not only the material theme will get this variant, but also lumo and every behaviour. This is a lot of work and requires a lot of testing, every behaviour in every browser. Also I'm not sure how this will be implemented. 

@Juchar still interested 😅?

**Comment by Springrbua** [comment]
> Before this can be added it must be clear that not only the material theme will get this variant, but also lumo and every behaviour.

Lumo does not necessarily need to get this variant. The variants for Vaadin Button are also different for `Lumo` and `Material`. `Material` has a `outlined` and a `contained`, `Lumo` has `small`, `large`, `tertiary` and so on.
So since this is a variant for `Material`, I would only include it for the `Material` theme.

**Comment by appreciated** [comment]
closed due to inactivity, reopen if still wanted
