### ISSUE TITLE
How to change applications icons and favicon?

### ISSUE THREAD

**Issue by kyberorg** [appreciated/vaadin-app-layout#271]
**What is it you are trying to archive?**
That application uses my icon pack instead of provided with this add-on. For example: at offline page, favicon.

**Comment by appreciated** [comment]
I guess as it's been described in the official documentation?
* [Application Icons](https://vaadin.com/docs/v13/flow/pwa/tutorial-pwa-icons.html)
* [Web App Manifest](https://vaadin.com/docs/v13/flow/pwa/tutorial-pwa-web-app-manifest.html)
