### ISSUE TITLE
Increasing the badge holder counter on menu item - during work

### ISSUE THREAD

**Issue by sasinskil** [appreciated/vaadin-app-layout#273]
I would like to raise a new topic, increasing the badge holder counter on menu item, without reloading the page, but during work.

for example:
I have an grid with items, and a connected "Default Badge Holder" on app menu that counts positions, when a new item is added, the updated digit is visible after reloading the page, not after operation, in real time - during work

**Comment by appreciated** [comment]
Have you tried updating it via:
```
UI.getCurrent().access(() -> {
            // increase badge
});
```

**Comment by appreciated** [comment]
Closed due to inactivity

**Comment by sasinskil** [comment]
I'm sorry for my absence, yes i have tried, unfortunately it doesn't work.

**Comment by sasinskil** [comment]
Is there any solution for changing count in real time, during work, not after reload page, when DefaultBadgeHolder counter is increasing or decreasing.

**Comment by appreciated** [comment]
Have you tried the mentioned solution of mine?

**Comment by sasinskil** [comment]
I tried, it doesn't work, Is there any solution for changing count in real time, during work, not after reload page, when DefaultBadgeHolder counter is increasing or decreasing.

**Comment by appreciated** [comment]
Can I see an example of your code with using my posted solution?

**Comment by sasinskil** [comment]
private void reloadNotifications() {

        caseCountHelper = serviceWithData from db
        badgeHolderList = new ArrayList<>();
        caseCounterList = integerListWithCount
        initDefaultBadgeHolders();
        caseCounterList = caseCountHelper.getCaseCounterList();

        for (DefaultBadgeHolder dBh : badgeHolderList) {
            dBh.clearCount();
        }

        notificationHolder.clearNotifications();


            try {
                getUI().ifPresent(ui -> ui.access(() -> {
                    addNotification(HIGH);

                    badgeHolderList.get(0).setCount(this.caseCounterList.get(0));
                    badgeHolderList.get(1).setCount(this.caseCounterList.get(1));
                    badgeHolderList.get(2).setCount(this.caseCounterList.get(2));
                    badgeHolderList.get(3).setCount(this.caseCounterList.get(3));
                    badgeHolderList.get(4).setCount(this.caseCounterList.get(4));
                }));
            } catch (Exception e) {
                e.printStackTrace();
            }

    }

**Comment by appreciated** [comment]
Have you checked  if `getUI().ifPresent()` is successful?

**Comment by appreciated** [comment]
Also, did you add the mentioned `@Push` Annotation? Does your servlet container has `Push` support?

**Comment by sasinskil** [comment]
Have you checked if getUI().ifPresent() is successful? - yes, "Also, did you add the mentioned @Push Annotation? Does your servlet container have Push support?" - how can i check this ?

**Comment by appreciated** [comment]
Did you add to your `AppLayoutRouterLayout` the `@Push` as follows?:
```
@Push
public class MyAppLayoutRouterLayout extends AppLayoutRouterLayout {
   ...
}
```

>  how can i check this ?
What Servlet container are you using?

**Comment by sasinskil** [comment]
Oh wait, getUI().isPresent() returl false, hmm why ? "What Servlet container are you using?" - Wildfly

**Comment by appreciated** [comment]
> Oh wait, getUI().isPresent() return false, hmm why ?

Well then you found your problem
I recommend try saving the UI instance in the constructure to an attribute, instead of retrieving it via `getUI()`. 

>  "What Servlet container are you using?" - 

Hopefully not a tooo old version.

**Comment by sasinskil** [comment]
latest Wildfly

**Comment by appreciated** [comment]
> I recommend try saving the UI instance in the constructure to an attribute, instead of retrieving it via getUI().

Note that this my cause issues in other usecases.

**Comment by sasinskil** [comment]
"I recommend try saving the UI instance in the constructure to an attribute, instead of retrieving it via getUI()." - what do you mean ? Can you be more specific?

**Comment by appreciated** [comment]
```
public class MyView extends VerticalLayout {
    private final UI ui; // use this instead of getUI()

    public MyView() {
        ui = UI.getCurrent();
    }
}
```

**Comment by sasinskil** [comment]
I understand, will try

**Comment by appreciated** [comment]
Also you can try this addon (async-manager)[https://vaadin.com/directory/component/async-manager]

**Comment by sasinskil** [comment]
public class MainAppLayout extends AppLayoutRouterLayout{
	 private final UI ui;

	public MainAppLayout() {
        ui = UI.getCurrent();
    }
}

ui always false

**Comment by appreciated** [comment]
Then try setting it `onAttach` as in the offical example.

**Comment by sasinskil** [comment]
it always doesn't  work, is there any solution, for example "OnChange listener" who will react when the number is changed and put in on the menu.

**Comment by appreciated** [comment]
So you managed to get the `UI` instance as shown in the offical example?

**Comment by sasinskil** [comment]
yes

**Comment by appreciated** [comment]
May I see your code again?

**Comment by sasinskil** [comment]
what exactly ?

**Comment by appreciated** [comment]
The part how you update the UI, basically everything that involves getting and using `UI` instances or using `UI::access`. 
Also I need to see how you start the task that updates the UI later on, I got the feeling you might do it by blocking the UI Thread.

**Comment by appreciated** [comment]
Here some working code using the async-manager addon
```
public class MainAppLayout extends AppLayoutRouterLayout {
    private DefaultNotificationHolder notifications = new DefaultNotificationHolder();
    private DefaultBadgeHolder badge = new DefaultBadgeHolder(5);

    public MainAppLayout() {
        notifications.addClickListener(notification -> {/* ... */});

        LeftNavigationItem menuEntry = new LeftNavigationItem("Menu", VaadinIcon.MENU.create(), View6.class);
        badge.bind(menuEntry.getBadge());

        init(AppLayoutBuilder
                ...
                .build());

        AsyncManager.register(this, asyncTask -> {
            for (int i = 0; i < 10; i++) {
                Thread.sleep(1000);
                int finalI = i;
                asyncTask.push(() -> {
                    notifications.addNotification(new DefaultNotification("Test" + finalI, "Test" + finalI));
                    badge.increase();
                });
            }
        });
    }
}
```

**Comment by sasinskil** [comment]
bean CaseCountHelper {- which count DefaultBadgeHolder:

public void countCases() {
  getDataFromDb;
reloadNotifications();
}

public void reloadNotifications() {

        for (DefaultBadgeHolder dBh : badgeHolderList) {
            dBh.clearCount();
        }

        try {
            this.badgeHolderList.get(0).setCount(this.caseCounterList.get(0));
            this.badgeHolderList.get(1).setCount(this.caseCounterList.get(1));
            this.badgeHolderList.get(2).setCount(this.caseCounterList.get(2));
            this.badgeHolderList.get(3).setCount(this.caseCounterList.get(3));
            this.badgeHolderList.get(4).setCount(this.caseCounterList.get(4));
        } catch (Exception e) {

            e.printStackTrace();
        }
    }
}

public class MainAppLayout extends AppLayoutRouterLayout  {

    private UI ui;

 @Override
    public AppLayout getAppLayout() {
 this.caseCountHelper.setService <- getData from db
        try {
            //Thread.sleep(1000);
            ui.access(() -> {
                this.caseCountHelper.countCases();
            });

        } catch (Exception e) {
            e.printStackTrace();
        }

}

 @Override
    protected void onAttach(AttachEvent attachEvent) {

        ui = attachEvent.getUI();
}

}

**Comment by appreciated** [comment]
Your Code blocks the UI unnecessary. Don't count you cases on the UI Thread, create another Thread for this.
```
ui.access(() -> {
                this.caseCountHelper.countCases();
});
```
`onAttach` will be called when the Component is attached to the UI, which is too late for you code to work. So `countCases` must be called after onAttach. You can ignore all of this if you use the AsyncManager addon please use it. 

Also update your App-Layout version it is pretty old.

**Comment by sasinskil** [comment]
Still doesn't work, i don't know did you understand my problem,your solution work when application is running, but once, case count on app menu item is visible but when i'm doing somethink during work, what is changing counter - didn't update him on main list in real time - i think just need a value change listener who will react when value is changed...am I wrong ?

**Comment by sasinskil** [comment]
Problem has been solved

**Comment by appreciated** [comment]
Can you maybe contribute the solution?

**Comment by jetdario** [comment]
> Problem has been solved

How did you solve the problem? Im also facing the same problem

**Comment by sasinskil** [comment]
Eventually, the solution didn't work. I'm sorry I didn't answer before.

>

**Comment by jetdario** [comment]
> Eventually, the solution didn't work. I'm sorry I didn't answer before.
> […](#)

problem solved. check this issue that I have created but was able to solved it as well together with some friends. #308
