### ISSUE TITLE
Production mode IE 11 js error.

### ISSUE THREAD

**Issue by ru5t** [appreciated/vaadin-app-layout#274]
**Describe the bug**
When packed for production (mvn clean package -Pproduction-mode
) and deployed to tomcat, on IE 11 facing JS error `
Assignment to read-only properties is not allowed in strict mode`. 

**To Reproduce**
1. Clean Vaadin [starter project](https://vaadin.com/start/latest/project-base)
2. Component dependency
```
<dependency>
				<groupId>com.github.appreciated</groupId>
				<artifactId>app-layout-addon</artifactId>
				<version>LATEST</version>
		</dependency>
```
3. Pack it `mvn clean package -Pproduction-mode` (you don't even have to use it to reproduce bug. Just add dependency.)
4. Deploy on tomcat
5. Navigate in IE

**Expected behavior**
No js errors and rendered layout.

** Additional Information :**
 - OS: Server: Arch Linux, Tomcat 9; Client:  Windows 7 Enterprise
 - Browser : IE 11
 - Version LATEST

**Comment by appreciated** [comment]
IE is currently not supported as stated in #134

**Comment by ru5t** [comment]
Who knew.. but it seems working w/o AppLayout. Anyways, thank you for such quick response!
