### ISSUE TITLE
DefaultBadgeHolder - > onChange Listener

### ISSUE THREAD

**Issue by sasinskil** [appreciated/vaadin-app-layout#275]
Is there any solution for changing count in real time, during work, not after reload page, when DefaultBadgeHolder counter is increasing or decreasing.

**Comment by appreciated** [comment]
Can you please not open duplicate issues? Please post comments on your other issue #273

**Comment by sasinskil** [comment]
I will

**Comment by jetdario** [comment]
> I will, wasn't sure that you would answer on closed issue

problem solved. check this issue that I have created but was able to solved it as well together with some friends. https://github.com/appreciated/vaadin-app-layout/issues/308
