### ISSUE TITLE
How to change app bar shadow depending on window scroll pos

### ISSUE THREAD

**Issue by markusjuhanio** [appreciated/vaadin-app-layout#278]
Hello!

I'm using LEFT behavior and custom.html file to edit the variables. 

How can I change the app-bar shadow to none when the scroll position is at the top of page and then change back to normal when it's scrolled down a bit? I think this should be done in JavaScript but for now I have very little experience of it.

Thanks for any help!

Markus

**Comment by appreciated** [comment]
@markusjuhanio could you show an complete (code) example, also images of what you want to archive and what the current state is?

**Comment by markusjuhanio** [comment]
> @markusjuhanio could you show an complete (code) example, also images of what you want to archive and what the current state is?

Thanks for quick answer.

I want to hide the app-bar shadow when top of page

`--app-layout-bar-shadow:  none`

 when the page is scrolled down, show shadow again

`--app-layout-bar-shadow: 0px 1px 10px 0px rgba(112, 112, 112,1);`

Something like

if (document.scrollTop == 0) {
        --app-layout-bar-shadow:  none;
    } else {
--app-layout-bar-shadow: 0px 1px 10px 0px rgba(112, 112, 112,1);
}


but I'm not sure where to execute that or how to access these values in javascript. Assuming you cannot detect page scroll position in Vaadin/Java?

**Comment by appreciated** [comment]
```
if (document.scrollTop == 0) {
--app-layout-bar-shadow: none;
} else {
--app-layout-bar-shadow: 0px 1px 10px 0px rgba(112, 112, 112,1);
}
```
Your code does not seem too bad. 

> but I'm not sure where to execute that or how to access these values in javascript. Assuming you cannot detect page scroll position in Vaadin/Java?

Checkout the Docs on how to add some JS to you Vaadin application. 

https://vaadin.com/docs/flow/importing-dependencies/tutorial-importing.html

I recommand toggling including a stylesheet with a css class with a different css-variable value and toggling the css class via JS

**Comment by markusjuhanio** [comment]
> I recommand including a Stylesheet with a css class with a different css-variable value and toggling the css class via JS.

I got now the javascript file imported and the classes to enable and disable shadow effect.

However I cannot detect scroll position. I tried this code and few others but I cannot get it to work.

`$(window).scroll(function() {
    var height = $(window).scrollTop();
    if(height  === 0) {
        alert("top");
    }});`

It is importing correctly, as single alert("text") works fine. Just cannot get that scroll position value

**Comment by appreciated** [comment]
Please read some documentation related to shadow DOM the rules have changed, but it still is possible to solve this straightforward.
