### ISSUE TITLE
Different routes with same last uri fragment leads to wrong menu item marked

### ISSUE THREAD

**Issue by stefanuebe** [appreciated/vaadin-app-layout#280]
I have two different routes ending with the same uri fragment
* "foo/dashboard"
* "bar/dashboard"

When moving to the first route, the app bar automatically selects the second item. 
Selecting the second item, marks the second item as expected.

**Comment by rickmanning1991** [comment]
Do these two routes uses the same view class?

**Comment by stefanuebe** [comment]
No, they are totally different (beside that they both are subclasses of Component of course). 

It might be related to the usage of "HasParameter", but not sure, didn't had time to check that.
