### ISSUE TITLE
PaperBadge

### ISSUE THREAD

**Issue by allenvpn312** [appreciated/vaadin-app-layout#284]
Can we use the  app layout paperbadge component generically?  If so, can you provide a simple example how to do that?  This is preferable rather than importing another badge component.

Thanks.

**Comment by appreciated** [comment]
> Can we use the app layout paperbadge component generically?
Yes you can use it, but at your own risk. Meaning I cannot guarantee that it won't be swapped out f.e. the next version. It will stay for now but maybe not so in the future.

>  This is preferable rather than importing another badge component.
If there was a similar well supported component in the directory I'd gladly swap.
