### ISSUE TITLE
[v4.0.0.beta1] Toggle button is missing menu icon

### ISSUE THREAD

**Issue by ajgassner** [appreciated/vaadin-app-layout#286]
First of all thank you for this great project!

The mobile drawer toggle button is missing the menu icon. I'm using Vaadin 14 with npm packaging. See screenshot attached.

v3.0.0.beta5:
`<paper-icon-button id="toggle" icon="menu" on-tap="onclick"></paper-icon-button>`

v4.0.0.beta1:
`<vaadin-button id="toggle" theme="tertiary"></vaadin-button>` 

Possible fix?
```
<vaadin-button id="toggle" theme="tertiary">
    <iron-icon icon="lumo:menu"></iron-icon>
</vaadin-button>
```

![image](https://user-images.githubusercontent.com/2866145/64006355-712af000-cb12-11e9-896f-844b044679a7.png)

**Comment by appreciated** [comment]
@ajgassner are you using the templates directly? The Icon is set via Java API.  Which behaviour is it you are using?

**Comment by ajgassner** [comment]
Ah ok, I use it via Java API. Left Responsive Hybrid Layout.

appreciated <notifications@github.com> schrieb am Fr., 30. Aug. 2019, 16:17:

**Comment by LuboZ** [comment]
Hello,
I have same problem. Using Java API, Left Responsive Hybrid Layout and missing toggle icon. Also I'm missing expand/collapse icons in menu.
![image](https://user-images.githubusercontent.com/33423536/64097881-ad09c380-cd65-11e9-8971-979757ce6381.png)

**Comment by appreciated** [comment]
@ajgassner Hmm I'm unable to reproduce your issue. Which browser are you using?

**Comment by ajgassner** [comment]
Chrome Version 76.0.3809.132 (Official Build) (64-bit)

```kotlin
// Kotlin code
class MainLayout : AppLayoutRouterLayout<AppLayout>() {

    init {
        init(AppLayoutBuilder
            .get(Behaviour.LEFT_RESPONSIVE_HYBRID)
            .withTitle(APP_NAME)
            .withIconComponent(Image("icons/icon.png", APP_NAME).apply { height = "32px" })
            .withSwipeOpen(true)
            .withAppMenu(
                LeftAppMenuBuilder.get()
                    .add(LeftNavigationItem(LokaleView::class.java))
                    .build()
            )
            .build())
    }
}
```

**Comment by ajgassner** [comment]
@appreciated I see you did changes to the code to address this issue. When do you plan to release 4.0.0.beta2 on Maven repo?

**Comment by appreciated** [comment]
4.0.0.beta2 is now available

**Comment by ajgassner** [comment]
Thank you @appreciated , I've just tested beta2, issue is fixed.
