### ISSUE TITLE
NPE AppLayoutBuilder.java:111 in spring boot example

### ISSUE THREAD

**Issue by jonmartinsolaas** [appreciated/vaadin-app-layout#288]
Hi, when running the jar (with java 12.0.1 on macOS) I get

`Caused by: java.lang.NullPointerException: null
        at com.github.appreciated.app.layout.component.builder.AppLayoutBuilder.setAppBarComponent(AppLayoutBuilder.java:111) ~[app-layout-addon-4.0.0-SNAPSHOT.jar!/:4.0.0-SNAPSHOT]
        at com.github.appreciated.app.layout.component.builder.AppLayoutBuilder.withAppBar(AppLayoutBuilder.java:106) ~[app-layout-addon-4.0.0-SNAPSHOT.jar!/:4.0.0-SNAPSHOT]
`

Same happens when creating project with Spring Initializr and adding 4.0.0.beta2 dependency, using the current example code provided on the demo site.

**Comment by appreciated** [comment]
Hmm this is wierd, I ran the UI tests before releasing there was no issue. No problems with 4.0.0.beta1?

**Comment by appreciated** [comment]
Also do you maybe have two versions in your dependencies? `4.0.0.beta2` is not the same as `4.0.0-SNAPSHOT`

**Comment by jonmartinsolaas** [comment]
Happens with beta1 and beta2 and current snapshot With jetty:run a demo app came up, but with various exceptions as well.

**Comment by jonmartinsolaas** [comment]
I got the error running from current master

**Comment by jonmartinsolaas** [comment]
Can you run the jar built from the spring example in master branch at your end?

**Comment by appreciated** [comment]
> Can you run the jar built from the spring example in master branch at your end?

To be honest I don't know since I  cannot try until sunday evening.
Try using the Spring Boot starter of vaadin.

**Comment by jonmartinsolaas** [comment]
Did that and pasted code from the online  demo site, still npe in the same
place. Will look more into it later today :)

lør. 7. sep. 2019, 13:17 skrev appreciated <notifications@github.com>:

**Comment by ajgassner** [comment]
For me everything is working now. I also encountered the issue, i had  to change the line

`public class Mainlayout extends AppLayoutRouterLayout  { ... }`

to

`public class Mainlayout extends AppLayoutRouterLayout<AppLayout>  { ... }`

when I was upgrading V3 to V4.

Init code:

```
init(
    AppLayoutBuilder
        .get(Behaviour.LEFT_RESPONSIVE_HYBRID)
        .withTitle("Demo")
        .withAppMenu(LeftAppMenuBuilder.get().build())
        .build()
)
```

**Comment by jonmartinsolaas** [comment]
Didn’t change anything for me, copied source from here: https://appreciated-collection.herokuapp.com/app-layout/ <https://appreciated-collection.herokuapp.com/app-layout/>

Also the jar file built from master in the spring example fails.

**Comment by appreciated** [comment]
> Didn’t change anything for me, copied source from here: https://appreciated-collection.herokuapp.com/app-layout/ <https://appreciated-collection.herokuapp.com/app-layout/>

As you can read above the source code is meant to be used in combination with version 3.* not 4.*. [Please used the updated code example instead](https://github.com/appreciated/vaadin-app-layout/tree/master/app-layout-examples/app-layout-spring-example)

**Comment by jonmartinsolaas** [comment]
Hi, example runs now, I usually `mvn clean install` before reading everything, kinda like throwing away the IKEA manual :0)

**Comment by jonmartinsolaas** [comment]
Hi again,

After adding
<dependency>
    <groupId>javax.inject</groupId>
    <artifactId>javax.inject</artifactId>
    <version>1</version>
</dependency>
the spring example jar ran without  java.lang.TypeNotPresentException: Type javax.inject.Inject not present

**Comment by appreciated** [comment]
First of all I'm pretty sure this error is not related with this addon. Either way @jonmartinsolaas are you using Java 11?

**Comment by jonmartinsolaas** [comment]
Not saying it is, just what makes it run. On 12.0.1.

**Comment by appreciated** [comment]
I see, thank you the information 👍 Added it to the project 3b4dbdabfe98cfb001ff81f2830c94ed2ffe58fc
