### ISSUE TITLE
LeftClickableItem icon

### ISSUE THREAD

**Issue by EvgeniyZherebin** [appreciated/vaadin-app-layout#291]
When you changing the icon, new ones are added to the old ones and caption text is disappear.

Vaadin 14.0.3, app-layout-addon 3.0.0.beta5

Kotlin code:
` themeSwitcher = LeftClickableItem("Dark theme", VaadinIcon.MOON_O.create()) {
            ui?.page?.executeJs("document.documentElement.setAttribute($0, $1)", "theme", if (isDark) "light" else "dark")
            themeSwitcher?.setCaption((if (isDark) "Light" else "Dark") + " theme")
            themeSwitcher?.icon = (if (isDark) VaadinIcon.SUN_O.create() else VaadinIcon.MOON_O.create())
            isDark = !isDark
        }`

![icons2](https://user-images.githubusercontent.com/43517653/64904143-04515180-d6df-11e9-95a6-338754abebab.png)
![icons](https://user-images.githubusercontent.com/43517653/64904070-a6703a00-d6dd-11e9-9010-40ed0ce8f7c2.png)

**Comment by appreciated** [comment]
If this is a bug then it is not one of this addon, Vaadin in generally will behave every like this. 
Instead the api of the "*Item" Components should be extended to support icon switch at run time, which is a legitimate request.

**Comment by appreciated** [comment]
Can be already done by using set Caption:
```
public abstract class MyAppLayout extends AppLayoutRouterLayout {

    private final LeftNavigationItem home;

    public MyAppLayout() {
        home = new LeftNavigationItem("View1", VaadinIcon.HOME.create(), getViewForI(1));
        AppLayoutBuilder builder = AppLayoutBuilder.get(...) ...
    }

    @Override
    protected void onAttach(AttachEvent attachEvent) {
        getUI().ifPresent(ui -> ui.access(() ->
                home.setCaption("test")
        ));
    }
}
```
