### ISSUE TITLE
Set the icons size of menu navigation items

### ISSUE THREAD

**Issue by pbaris** [appreciated/vaadin-app-layout#294]
**Describe the current way to archive your requirement**
Set the icons size of menu navigation items
![Screenshot-20190918124749-218x133](https://user-images.githubusercontent.com/242612/65138410-9cb74100-da13-11e9-9eee-a3ac19f33905.png)

**Describe the solution you'd like**
add variables like
    --app-layout-menu-button-left-icon-size
    --app-layout-menu-button-right-icon-size

**Additional context**
Now i can archive this by adding the following css
    .app-layout [slot="drawer-content"] iron-icon { width:18px; }
    .app-layout [slot="drawer-content"] iron-icon[icon="vaadin:chevron-down-small"] { width:12px; }

**Target Version**
4.0.0

**Comment by appreciated** [comment]
@pbaris can this issue be closed?
