### ISSUE TITLE
Components transparency issue with LeftOverlay Layout when scrolling 

### ISSUE THREAD

**Issue by mschoeffel** [appreciated/vaadin-app-layout#298]
# Summary
When using the `LeftOverlay` Layout  and scrolling, components are still visible and clickable from underneath or on top of the AppLayoutBar. Normal text disappears underneath.

# Definitions
AppLayoutBar: The top bar part of the Layout containing the Title `App Layout`, bell and Menu Icon.

# Steps to reproduce the behavior:
1. I downloaded the example Project and used the `app-layout-spring-example`.
2. Changed the Layout in the `MainAppLayout` class to `LeftLayouts.LeftOverlay` in the extends part of the class and also in the AppLayoutBuilder.get Method. 
3. Executed the project with `spring-boot:run`.
3. Opened the browser with `localhost:8080`.
4. Made the browser window smaller so I could scroll the components to top.
5. The component (button) is still visible and clickable underneath/on top of the AppLayoutBar.

# Expected
I think normally the component button should disappear underneath the AppLayoutBar like normal text does.

# Here some screenshots:
See the `Click me` button and text underneath.
## Normal(right) behavior with other Layouts(here e.g. LeftResponsive):
![Normal](https://user-images.githubusercontent.com/26282694/67369520-6e300700-f579-11e9-9cb3-e057bf19472e.png)

## Wrong component behavior with the LeftOverlay Layout:
![Components Wrong](https://user-images.githubusercontent.com/26282694/67369620-a5061d00-f579-11e9-8b82-44ae680697c6.png)

## Also wrong behavior with components but right with text using LeftOverlay Layout:
![Text Right Component Wrong](https://user-images.githubusercontent.com/26282694/67369836-03330000-f57a-11e9-88d5-5a124c6aaee4.png)

# Also worth mentioning
- The scrollbar also get's displayed wrong. The AppLayoutBar gets displayed on top of the scrollbar. Normally the scrollbar should be on top of the AppLayoutBar or starting at the bottom of it.

# Additional Information
 - OS: Windows 10 Pro Version 1809 Build 17763.737 64bit
 - Browser: Google Chrome Build 77.0.3865.120 64bit

**Comment by appreciated** [comment]
Seems more like a build issue to me. Will take a look at it in the afternoon

**Comment by appreciated** [comment]
Issue confirmed!

**Comment by appreciated** [comment]
> Also worth mentioning
The scrollbar also get's displayed wrong. The AppLayoutBar gets displayed on top of the scrollbar. Normally the scrollbar should be on top of the AppLayoutBar or starting at the bottom of it.

This is a iOS "optimization". It's not easy to explain, but both solutions have their drawbacks

**Comment by mschoeffel** [comment]
Thanks for your quick reply and fix! Appreciate it a lot!

**Comment by appreciated** [comment]
Thanks for checking, [rc3](https://vaadin.com/directory/component/app-layout-add-on/4.0.0.rc3) should now finally fixed it.
