### ISSUE TITLE
SideMenu is gone after an error occurred

### ISSUE THREAD

**Issue by kamuffe** [appreciated/vaadin-app-layout#299]
**Describe the bug**
Currently I migrate a app from Vaadin 8 to Vaadin 14. I used the App Layout in  the old app and now as well in the new app. When any unexpected exception occurs the left responsive menu is hidden after navigating to another existing view. After app restart the menu is visible again.

**To Reproduce**
1. App with two views, add a button to one one view which throws an exception
2. click it (exception is shown)
3. and then navigate manually to the second view, or back to the first.

**Expected behavior**

**Screenshots**
Screenshot before exception:
![AppLayout-LeftMenuOK-ResponsiveHybrid](https://user-images.githubusercontent.com/5285367/67544355-6301e600-f6f5-11e9-8111-06c19f720a48.PNG)
Screenshot at exception:
![AppLayout-LeftMenuException-ResponsiveHybrid](https://user-images.githubusercontent.com/5285367/67544360-672e0380-f6f5-11e9-9885-01e93c34afff.PNG)
Screenshot after exception occurred and navigate manually to a view:
![AppLayout-LeftMenuGone-ResponsiveHybrid](https://user-images.githubusercontent.com/5285367/67544428-baa05180-f6f5-11e9-937b-209e1da34bdd.PNG)

** Additional Information (please complete the following information):**
 - OS: Windows 10 Desktop
 - Browser Chrome 78.0.3904.70
 - Vaadin 14.0.9

**Comment by appreciated** [comment]
@kamuffe thanks for reporting, but I really need the Exception otherwise this will be much more complicated to fix.

**Comment by appreciated** [comment]
closed by fcf8214afdcaabdac1f1732770c70bd35757fb67
