### ISSUE TITLE
Add method execution

### ISSUE THREAD

**Issue by frangelh** [appreciated/vaadin-app-layout#3]
New Feature: 
Being able to execute a method instead of navigate by this way can navigate to a external link or add Windows to the UI by code.

**Comment by appreciated** [comment]
I have added the request feature usage as follwows: 
````
 AbstractNavigationDrawer drawer = NavigationDrawerBuilder.get()
  ...
  .withClickableElement("Custom Action", VaadinIcons.EDIT, clickEvent -> Notification.show("Yay!"))
  ...  
  .build();
````
