### ISSUE TITLE
Programatically Closable Hybrid Menu

### ISSUE THREAD

**Issue by webnazar** [appreciated/vaadin-app-layout#30]
Excellent Work. Can you add Hidden Menu Drawer Option By Default If Required (As it auto hides in Mobile Version)

**Comment by appreciated** [comment]
Have you tried using the [Left](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/java/com/github/appreciated/app/layout/behaviour/Behaviour.java#L6) Behaviour?

**Comment by webnazar** [comment]
Sir,

When we see App Layout Drawer in Desktop Version, The Drawer is Appeared in LEFT Behavior. What i need is IF i set appLayout.withHiddenByDefault(true) e.g. then in Desktop View The Drawer should be hidden. When click on Menu Then it Toggle.

**Comment by appreciated** [comment]
Have you tried [these Methods](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/java/com/github/appreciated/app/layout/behaviour/AbstractLeftAppLayout.java#L62)?

**Comment by webnazar** [comment]
Yes, It Helps and solved the problem. Thanks
