### ISSUE TITLE
Add support for IronIcon

### ISSUE THREAD

**Issue by MojoManagement** [appreciated/vaadin-app-layout#301]
**Is your feature request related to a problem? Please describe.**
We are not able to use IronIcon for icons for navigation or clickable items in the app

**Describe alternatives you've considered**
API does not allow any other class than component although it seems to use the element of the Icon class.

**Comment by appreciated** [comment]
> API does not allow any other class than component although it seems to use the element of the Icon class.

Well "any other class than component" sounds a bit like a understatement, since it can be pretty much anything. How about making a pull request and [including this addon](https://vaadin.com/directory/component/iron-icons)?

**Comment by MojoManagement** [comment]
Ouh, I mixed up the sentences I just wanted to simplify last night.
I will try to allow IronIcons usage for icons in general.
