### ISSUE TITLE
Tabs do not render correctly

### ISSUE THREAD

**Issue by markhm** [appreciated/vaadin-app-layout#304]
It seems - or so I am experiencing - the Tabs component does not render correctly when used with vaadin-app-layout. 

Following the example called 'Tabs with pages' [here](https://vaadin.com/components/vaadin-tabs/java-examples), under the regular MainLayout (from the Vaadin Starter that has the menu on top), the tabs correctly look like this:

<img width="449" alt="tabs_correct" src="https://user-images.githubusercontent.com/1430451/69482602-c62e8780-0e1d-11ea-8d02-2a875d96d4af.png">

In an application that uses AppLayoutRouterLayout<LeftLayouts.LeftResponsiveHybrid>, the rendered Tabs component looks like this:

<img width="362" alt="tabs_problem" src="https://user-images.githubusercontent.com/1430451/69482600-c62e8780-0e1d-11ea-8354-3483317ab1e3.png">

The tab names are too close to each other and there are no links. 

Tested with Brave, Safari latest on macOS 10.15.1 with Vaadin 14.0.13 and app-layout-addon 4.0.0.rc4.

Thanks...!

**Comment by appreciated** [comment]
Tested against master and Vaadin 14.1.4. I was not able to reproduce this issue.

**Comment by lipisak** [comment]
Hi appreciated,
I have the very same issue here. 
Vaadin: 14.1.19. 
Used layout: LeftResponsiveSmallNoAppBar
Running on: Spring Boot 2.1
