### ISSUE TITLE
How to handle DefaultBadgeHolder & DefaultNotificationHolder

### ISSUE THREAD

**Issue by jetdario** [appreciated/vaadin-app-layout#308]
How do we handle increase/decrease of badge and notification from a view class? I have this main layout with menu that routes with my view (SPA). I want to link the notification and badge in the menu from my view class. How do we achieve this? 

`@Push
public class MainAppRouterLayout extends AppLayoutRouterLayout<LeftLayouts.LeftHybrid> {

    WebexSessionService ts = new WebexSessionServiceImpl();
    
    public MainAppRouterLayout() {
        WebexSessionView view = new WebexSessionView();
        LeftNavigationItem menuEntry = new LeftNavigationItem("Webex Notification", VaadinIcon.MENU.create(), view);
        menuEntry.getElement().setProperty("title", "menu");
        
        View2 view2 = new View2(); 

        init(AppLayoutBuilder.get(LeftLayouts.LeftHybrid.class)
                .withTitle("Video Asset Management")
                .withAppBar(AppBarBuilder.get()
                        .add(new NotificationButton<>(VaadinIcon.BELL, view2.notification()))
                        .build())
                .withAppMenu(LeftAppMenuBuilder.get()
                        .addToSection(HEADER, 
                                userProfilePhoto(), 
                                new LeftHeaderItem("MENU", null, null),
                                new LeftClickableItem("Edit Profile", VaadinIcon.COG_O.create(), clickEvent -> {
                                    Notification.show("EDIT PROFILE!", 3000, Notification.Position.MIDDLE);
                                })
                        )
                        .add(view2.getLeftNavigationItem(),
                                LeftSubMenuBuilder.get("Event Management", VaadinIcon.GLOBE_WIRE.create())
                                        .add(new LeftNavigationItem("Webex Event", VaadinIcon.LIST_OL.create(), WebexEventList.class),
                                                new LeftNavigationItem("New Event", VaadinIcon.PAPERPLANE.create(), WebexNewEventSchedule.class),
                                                new LeftNavigationItem("Event Calendar", VaadinIcon.CALENDAR.create(), WebexEventCalendar.class))
                                        .build(),
                                menuEntry, 
                                new LeftNavigationItem("Settings", VaadinIcon.COG.create(), SettingsUI.class), 
                                new LeftNavigationItem("Logout", VaadinIcon.CLOSE_SMALL.create(), LogoutView.class))
                        .build())
                .build());
    }

    Div userProfilePhoto(){
        Div div = new Div();
        div.setWidthFull();
        div.setHeight("50px");
        div.getStyle().set("padding", "0");
        div.getStyle().set("margin-top", "10px");
        div.getStyle().set("text-align", "center");
        
        Image image = new Image("frontend/images/user-logo.png", "");
        image.setWidth("50px");
        div.add(image);
        return div;
    }

}` 

`@Route(value = "view2", layout = MainAppRouterLayout.class)
public class View2 extends VerticalLayout implements BeforeEnterObserver {
    
    WebexSessionService ts = new WebexSessionServiceImpl();
    
    private DefaultNotificationHolder notifications;
    private DefaultBadgeHolder badge;
    private LeftNavigationItem leftNavigationItem;
  
    public View2() {
        badgeHolder();
        
        add(new Label("View 2"), new Button("Decrease Badge", event -> {
            System.out.println("badge: "+getBadge().getCount());
            AsyncManager.register(this, asyncTask -> {
                asyncTask.push(() -> {
                    decrease();
                });
            });
        }));
    }

    public DefaultNotificationHolder notification(){
        notifications = new DefaultNotificationHolder(newStatus -> {
            Notification.show(newStatus.getTitle()+" "+newStatus.getPriority().getValue()); 
            System.out.println(newStatus.getTitle().split(":")[0]);
        });
        
        for(WebexSession ws : ts.findAllTrainingWithNoFilter()){
            notifications.add(new DefaultNotification(ws.getWebexSessionId()+": "+ws.getConfName(), ws.getDescription(), Priority.HIGH));
        }
        
        return notifications;
    }
    
    public void badgeHolder(){
        badge = new DefaultBadgeHolder(ts.findAllTrainingWithNoFilter().size());
    }

    public DefaultBadgeHolder getBadge() {
        return badge;
    }

    public LeftNavigationItem getLeftNavigationItem() {
        return leftNavigationItem;
    }

    public void decrease(){
        getBadge().decrease();
    }
    
}`

**Comment by jetdario** [comment]
![Screen Shot 2020-01-04 at 1 43 12 PM](https://user-images.githubusercontent.com/6972381/71760410-38ec5180-2ef8-11ea-86ce-2f53d9f4a8bb.png)

**Comment by jetdario** [comment]
![Screen Shot 2020-01-04 at 1 45 13 PM](https://user-images.githubusercontent.com/6972381/71760427-79e46600-2ef8-11ea-84c9-5d6ea7618c68.png)

**Comment by jetdario** [comment]
![Screen Shot 2020-01-04 at 1 46 00 PM](https://user-images.githubusercontent.com/6972381/71760430-92548080-2ef8-11ea-859c-ecc198b2728e.png)

**Comment by jetdario** [comment]
![Screen Shot 2020-01-04 at 1 46 00 PM](https://user-images.githubusercontent.com/6972381/71760436-a4362380-2ef8-11ea-844b-6291ce29d791.png)

**Comment by jetdario** [comment]
problem solved. you need to call super.onAttach(attachEvent) inside onAttach method then implement broadcaster.

**Comment by jetdario** [comment]
Im reopening the issue since there is a bug in my code or something.. maybe there are other solutions to this problem.

**Comment by jetdario** [comment]
`@Push
public class MainLayout extends AppLayoutRouterLayout<LeftLayouts.LeftHybrid> {
     /** Do not initialize here. This will lead to NPEs
     */
    private DefaultNotificationHolder notifications;
    private DefaultBadgeHolder badge;
    
    Registration broadcasterRegistration;
    
    public MainLayout() {
        notifications = new DefaultNotificationHolder(newStatus -> {
        });
        
        badge = new DefaultBadgeHolder(5);
        
        for (int i = 1; i < 6; i++) {
            notifications.add(new DefaultNotification("Test title" + i, "A rather long test description ..............." + i));
        }
        
        LeftNavigationItem menuEntry = new LeftNavigationItem("Menu", VaadinIcon.MENU.create(), View6.class);
        badge.bind(menuEntry.getBadge());
        
        init(AppLayoutBuilder.get(LeftLayouts.LeftHybrid.class)
                .withTitle("App Layout")
                .withAppBar(AppBarBuilder.get()
                        .add(new NotificationButton<>(VaadinIcon.BELL, notifications))
                        .build())
                .withAppMenu(LeftAppMenuBuilder.get()
                        .addToSection(HEADER, 
                                new LeftClickableItem("Clickable Entry", VaadinIcon.COG.create(), clickEvent -> Notification.show("onClick ..."))
                        ) 
                        .add(new LeftNavigationItem("Home", VaadinIcon.HOME.create(), View1.class),
                                LeftSubMenuBuilder.get("My Submenu", VaadinIcon.PLUS.create())
                                        .add(LeftSubMenuBuilder.get("My Submenu", VaadinIcon.PLUS.create())
                                                        .add(new LeftNavigationItem("Charts", VaadinIcon.SPLINE_CHART.create(), View2.class),
                                                                new LeftNavigationItem("Contact", VaadinIcon.CONNECT.create(), View3.class),
                                                                new LeftNavigationItem("More", VaadinIcon.COG.create(), View4.class))
                                                        .build(),
                                                new LeftNavigationItem("Contact1", VaadinIcon.CONNECT.create(), View3.class),
                                                new LeftNavigationItem("More1", VaadinIcon.COG.create(), View5.class))
                                        .build(),
                                menuEntry)
                        .addToSection(FOOTER, new LeftClickableItem("Clickable Entry", VaadinIcon.COG.create(), clickEvent -> Notification.show("onClick ...")))
                        .build())
                .build());
    }
    
    @Override
    protected void onAttach(AttachEvent attachEvent){
        super.onAttach(attachEvent);
        UI ui = attachEvent.getUI();
        broadcasterRegistration = Broadcaster.register(newMessage -> {
            ui.access(() -> 
                badge.decrease()
            );
        });
    }
    
    @Override
    protected void onDetach(DetachEvent detachEvent){
        broadcasterRegistration.remove();
        broadcasterRegistration = null;
    }
}` 

`@Route(value = "view6", layout = MainLayout.class)
public class View6 extends VerticalLayout {

    public View6() {
        setSizeFull();
        add(new Label("View 6"), new Button("DECREASE BADGE", event -> {
            Broadcaster.broadcast("TEST");
        }));
    }
    
}`

`public class Broadcaster {
    
    static Executor executor = Executors.newSingleThreadExecutor();

    static LinkedList<Consumer<String>> listeners = new LinkedList<>();

    public static synchronized Registration register(
            Consumer<String> listener) {
        listeners.add(listener);

        return () -> {
            synchronized (Broadcaster.class) {
                listeners.remove(listener);
            }
        };
    }

    public static synchronized void broadcast(String message) {
        for (Consumer<String> listener : listeners) {
            executor.execute(() -> listener.accept(message));
        }
    }
}`

**Comment by jetdario** [comment]
I dont know if this is a bug but you need to have some changes with your component from the sender class to be able to have a fluid functionality with what UI needed to be update from the receiver. 

`add(new Label("View 6"), new Button("DECREASE BADGE", event -> {
        Broadcaster.broadcast("TEST");
        Notification.show("NOTIFY USER!"); //<--- need to add after the broadcast. this can be any other component. I cannot explain further as to why it is necessary. 

closing this issue.
    }));`

**Comment by appreciated** [comment]
@jetdario This is in Best Case a workaround but not a Bugfix. This all sounds to me like similar issues I had with the `@Push` Annotation. Which Servlet Container are you using? Also have you tried using the different transport mechanisms?

**Comment by jetdario** [comment]
> `@Push
> public class MainLayout extends AppLayoutRouterLayout<LeftLayouts.LeftHybrid> {
> private DefaultNotificationHolder notifications;
> private DefaultBadgeHolder badge;
> 
> ```
> Registration broadcasterRegistration;
> 
> public MainLayout() {
>     notifications = new DefaultNotificationHolder(newStatus -> {
>     });
>     
>     badge = new DefaultBadgeHolder(5);
>     
>     for (int i = 1; i < 6; i++) {
>         notifications.add(new DefaultNotification("Test title" + i, "A rather long test description ..............." + i));
>     }
>     
>     LeftNavigationItem menuEntry = new LeftNavigationItem("Menu", VaadinIcon.MENU.create(), View6.class);
>     badge.bind(menuEntry.getBadge());
>     
>     init(AppLayoutBuilder.get(LeftLayouts.LeftHybrid.class)
>             .withTitle("App Layout")
>             .withAppBar(AppBarBuilder.get()
>                     .add(new NotificationButton<>(VaadinIcon.BELL, notifications))
>                     .build())
>             .withAppMenu(LeftAppMenuBuilder.get()
>                     .addToSection(HEADER, 
>                             new LeftClickableItem("Clickable Entry", VaadinIcon.COG.create(), clickEvent -> Notification.show("onClick ..."))
>                     ) 
>                     .add(new LeftNavigationItem("Home", VaadinIcon.HOME.create(), View1.class),
>                             LeftSubMenuBuilder.get("My Submenu", VaadinIcon.PLUS.create())
>                                     .add(LeftSubMenuBuilder.get("My Submenu", VaadinIcon.PLUS.create())
>                                                     .add(new LeftNavigationItem("Charts", VaadinIcon.SPLINE_CHART.create(), View2.class),
>                                                             new LeftNavigationItem("Contact", VaadinIcon.CONNECT.create(), View3.class),
>                                                             new LeftNavigationItem("More", VaadinIcon.COG.create(), View4.class))
>                                                     .build(),
>                                             new LeftNavigationItem("Contact1", VaadinIcon.CONNECT.create(), View3.class),
>                                             new LeftNavigationItem("More1", VaadinIcon.COG.create(), View5.class))
>                                     .build(),
>                             menuEntry)
>                     .addToSection(FOOTER, new LeftClickableItem("Clickable Entry", VaadinIcon.COG.create(), clickEvent -> Notification.show("onClick ...")))
>                     .build())
>             .build());
> }
> 
> @Override
> protected void onAttach(AttachEvent attachEvent){
>     super.onAttach(attachEvent);
>     UI ui = attachEvent.getUI();
>     broadcasterRegistration = Broadcaster.register(newMessage -> {
>         ui.access(() -> 
>             badge.decrease()
>         );
>     });
> }
> 
> @Override
> protected void onDetach(DetachEvent detachEvent){
>     broadcasterRegistration.remove();
>     broadcasterRegistration = null;
> }
> ```
> 
> }`
> 
> `@Route(value = "view6", layout = MainLayout.class)
> public class View6 extends VerticalLayout {
> 
> ```
> public View6() {
>     setSizeFull();
>     add(new Label("View 6"), new Button("DECREASE BADGE", event -> {
>         Broadcaster.broadcast("TEST");
>     }));
> }
> ```
> 
> }`
> 
> `public class Broadcaster {
> 
> ```
> static Executor executor = Executors.newSingleThreadExecutor();
> 
> static LinkedList<Consumer<String>> listeners = new LinkedList<>();
> 
> public static synchronized Registration register(
>         Consumer<String> listener) {
>     listeners.add(listener);
> 
>     return () -> {
>         synchronized (Broadcaster.class) {
>             listeners.remove(listener);
>         }
>     };
> }
> 
> public static synchronized void broadcast(String message) {
>     for (Consumer<String> listener : listeners) {
>         executor.execute(() -> listener.accept(message));
>     }
> }
> ```
> 
> }`

This my whole source code built in SpringBoot. I havent tried any other transport mechanism.
