### ISSUE TITLE
Packages are missing after Upgrade from v3 to v4

### ISSUE THREAD

**Issue by realulim** [appreciated/vaadin-app-layout#311]
While upgrading Vaadin from bower to npm mode I also upgraded this library from 3.0.0.beta5 to 4.0.0.rc4. However, many packages are now missing, such as:
com.github.appreciated.app.layout.behaviour
com.github.appreciated.app.layout.builder
com.github.appreciated.app.layout.notification
com.github.appreciated.app.layout.router
Apparently there were backwards-incompatible changes from v3 to v4? Are there any release notes or other docs on how to deal with that?

**Comment by appreciated** [comment]
[The release notes are on the directory page](https://vaadin.com/directory/component/app-layout-add-on/4.0.0.rc1)

> Apparently there were backwards-incompatible changes from v3 to v4? 
Yes there were. 
> Are there any release notes or other docs on how to deal with that?
You could remove the packages manually and use your IDE autocompletion. 

[Another option would be to checkout the demo](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-examples/app-layout-plain-example/src/main/java/com/github/appreciated/example/plain/MainAppLayout.java)s.

**Comment by realulim** [comment]
Yes, autocompletion only got me so far, because some packages have no replacement and methods are missing / have different signatures. Looks like I'll have to reimplement this from scratch according to the demo. Thanks for your help.

**Comment by appreciated** [comment]
Yes there were some naming inconsistencies, sorry for the inconvenience. 
If I remember correctly every class has a replacement, but the name, the package, or the parameters might have changed slightly.
There should be no need for a "reimplementation".

**Comment by realulim** [comment]
Ok, I'll get it done. Just needed the info what I'll have to do and wanted to make sure I'm not barking up the wrong tree (such as having included the wrong dependencies or such).
