### ISSUE TITLE
Simplify Search Feature

### ISSUE THREAD

**Issue by kamuffe** [appreciated/vaadin-app-layout#312]
The current search feature is baked by ConfigurableFilterDataProvider and some SerializablePredicate in Query. For some usecases this approach is bit to complex e.g. when we need to pass the exact search phrase to the search backend like Elastic Search. In that case there is no need to implement the actual filtering in a predicate. The methods for building a SearchOverlayButton requesting a ConfigurableFilterDataProvider where a more generic DataProvider is sufficient because ConfigurableFilterDataProvider methods are never called and construction of a ordinary DataProvider is much simpler.

**Describe the solution you'd like**
- pass DataProvider to the builder instead of ConfigurableFilterDataProvider to be more generic
- Use Generics to let the user pass the actual filtering to the buttons

**Comment by appreciated** [comment]
Closed by #313
