### ISSUE TITLE
VaadinCdiView Support

### ISSUE THREAD

**Issue by bishwajitcse** [appreciated/vaadin-app-layout#32]
can have any option to back navigation with navigationbar..

**Comment by appreciated** [comment]
For two features / problems please always open 2 issues, so that we can discuss them separately (and that I can manage them separately).

> VaadinCdiView Support
1. VaadinCDI should work out of the box it is really similar to the Spring solution:


```
@CDIUI("")
@Theme("mytheme")
public class MyUI extends UI {

    @Inject
    CDIViewProvider viewProvider;

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        AppLayout layout = AppLayoutBuilder.get()
                ...
                .withNavigationElementInfoProvider(aClass ->
                        new NavigationElementInfo(
                                Optional.ofNullable(aClass.getAnnotation(MenuCaption.class)) // Caption
                                        .map(menuElement -> menuElement.value())
                                        .orElse(aClass.getAnnotation(CDIView.class).value()),
                                Optional.ofNullable(aClass.getAnnotation(MenuIcon.class))  // Icon
                                        .map(menuElement -> menuElement.value())
                                        .orElse(null),
                                aClass.getAnnotation(CDIView.class).value())  // ViewName
                )
                .add( ... )
                ...
                .withNavigatorConsumer(navigator -> navigator.addProvider(viewProvider))
                .build();
        setContent(layout);
    }

    @WebServlet(value = "/*", asyncSupported = true)
    @VaadinServletConfiguration(productionMode = false, ui = MyUI.class)
    public static class Servlet extends VaadinServlet {
    }
}

@CDIView("")
@MenuCaption("Chart")
@MenuIcon(VaadinIcons.ABACUS)
public class FirstView extends VerticalLayout implements View {
   ...
}

@CDIView("cart")
@MenuCaption("Chart")
@MenuIcon(VaadinIcons.ABACUS)
public class SecondView extends VerticalLayout implements View {
   ...
}
```

> can have any option to back navigation with navigationbar
2. Would be a really nice feature to have, but it will wait for [until Vaadin 8.2 because since the Navigator will be revamped](https://github.com/vaadin/framework/pull/10042)

**Comment by appreciated** [comment]
Reopen the issue please if there are any problems.

**Comment by bishwajitcse** [comment]
Thanks for your answer. :) Hopefully you will be add back navigation feature when v8.2 release. :)

**Comment by appreciated** [comment]
Did the example above work?

**Comment by bishwajitcse** [comment]
Yes. I have done. I am doing like that...
AppLayout layout = AppLayoutBuilder.get()
				.withBehaviour(Behaviour.LEFT)
				.withDesign(AppBarDesign.MATERIAL)
				.addToAppBar(rightLayout)
				.withNavigationElementInfoProvider(aClass ->
				new NavigationElementInfo("caption",null,
						aClass.getAnnotation(CDIView.class).value())  // ViewName
						)
				.add("Inspection", VaadinIcons.HOME, badge, MobileInspectionView.class)
				.add("Issue", VaadinIcons.HOME, badge, MobileIssueView.class)
				
				.withNavigatorConsumer(navigator -> navigator.addProvider(viewProvider))
				.build();

But ugly waiting for back navigation option...

**Comment by appreciated** [comment]
Good to know that it worked
> But ugly waiting for back navigation option...
If you need it urgently you are welcome to make a pull request. 
I don't want to program it twice so as being said I will wait for vaadin 8.2, the new api might make implementing it much easier.

**Comment by bishwajitcse** [comment]
Hi again..
I am trying to support i18 text support on Menu. But can't get Button component when language changes.. How can I change the Menu Item caption...?

**Comment by appreciated** [comment]
Stick to the rules please and open another issue.
