### ISSUE TITLE
can I ask a question using the Brazilian Portuguese language?

### ISSUE THREAD

**Issue by csilva2001** [appreciated/vaadin-app-layout#328]
Johannes, please, can I ask a question using the Brazilian Portuguese language?
Thanks

**Comment by appreciated** [comment]
Sure, what would you like to know?

**Comment by csilva2001** [comment]
(trying in English ...)
Thanks for the chance.
I use AppLayoutRouterLayout and I need to put in a simple login form.
I created a method before init () and put it inside a modal Dialog with a login form.

I ask:
1 - how can I navigate to a welcome view, after authentication?
2 - is it possible to load an empty view as a default?

Thank you for your help and attention.
Hugs

--------------------------

Obrigado pela chance.
Uso AppLayoutRouterLayout e preciso colocar um formulario simples de login.
Criei um method antes do init() e coloquei dentro de um Dialog modal com um form login.

Pergunto:
1 - como posso navegar para uma view de boas vindas, depois da autenticação?
2 - é possível carregar uma view vazia como default?

Obrigado pela ajuda e pela atenção.
Abraços

**Comment by appreciated** [comment]
@csilva2001 Access control is not being managed by this addon. This addon is only about the View Side of things. [The following blog gives a good overview about this.](https://vaadin.com/blog/the-dangers-of-using-the-wrong-abstraction-for-vaadin-access-control).

Also read some documentation about Vaadin Routes in general:

- [Router Layouts and Nested Router Targets](https://vaadin.com/docs/v14/flow/routing/tutorial-router-layout.html)

- [Navigating Between Routes](https://vaadin.com/docs/v14/flow/routing/tutorial-routing-navigation.htmll)

**Comment by csilva2001** [comment]
ok, I got it.
I'll see that link.
Thanks, hugs
