### ISSUE TITLE
[4.0.0] Is there any way to have the drawer toggle button visable at any of width

### ISSUE THREAD

**Issue by natezhengbne** [appreciated/vaadin-app-layout#348]
Hi,
Is there any way to have the button in the red circle visible all the time as below picture

![image](https://user-images.githubusercontent.com/34373238/98324290-9761ef00-2037-11eb-9870-5772778c1618.png)

**Comment by appreciated** [comment]
Sure, try out any Behaviour without "RESPONSIVE" in it.

**Comment by appreciated** [comment]
@natezhengbne could you be more specific about the desired UI behaviour?

**Comment by natezhengbne** [comment]
Hi @appreciated , sorry for the late reply.
I want the toggle button is visible when the screen width greater than 800px also.
I think I want the drawer behaviour was running as same as any of screen width.

**Comment by appreciated** [comment]
@natezhengbne That is the case for all `LeftLayouts.*` that don't contain the keyword `Responsive`.
