### ISSUE TITLE
Support for FontAwesome Iron Iconset

### ISSUE THREAD

**Issue by oliveryasuna** [appreciated/vaadin-app-layout#352]
It would be nice if this addon natively supported https://vaadin.com/directory/component/fontawesome-iron-iconset/overview, such that additional styling was not necessary. For example, you cannot use a `FontAwesome.Solid.BELL` with a `NotificationButton` without wrapping it in a `Component`.

**Comment by appreciated** [comment]
[The NotificationButton supports using a different Component as an Icon](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/java/com/github/appreciated/app/layout/addons/notification/component/NotificationButton.java#L34-38). In my opinion this is already convenient enough. Adding Fontawesome as a dependency might add up for the bundle size of every user (not sure though) even if it's not used.

**Comment by oliveryasuna** [comment]
Can you add the `NotificationHolder` after the constructor?

**Comment by appreciated** [comment]
I've got to correct myself on this one, while the Icon can be set manually in the `NotificationButton`, the `NotificationHolder` cannot, which makes this quite unusable. I will fix this in the next version.

**Comment by oliveryasuna** [comment]
Yes, that was my concern. It may be smart to add a constructor that accepts a `Component` and `NotificationHolder`, so one does not have to perform the function of the `VaadinIcon` and `NotificationHolder` constructor manually.
