### ISSUE TITLE
calc() function causing height to be cropped

### ISSUE THREAD

**Issue by deyaeddin** [appreciated/vaadin-app-layout#36]
I found the solution :
https://stackoverflow.com/questions/17982111/sass-variable-in-css-calc-function

**Comment by appreciated** [comment]
I haven't had any problems with the current code, can you describe in which cases the previous code was a problem? Thanks for the Pull Request by the way!

**Comment by appreciated** [comment]
Just closing the issue because the related code is already merged.

**Comment by deyaeddin** [comment]
it caused a sass error when $app-bar-height set to be in % and not px. I was trying some height variations for testing only. I think you might also consider changing: #{$app-bar-height} everywhere
