### ISSUE TITLE
Hide the left nav & message popup automatically after user click one item

### ISSUE THREAD

**Issue by yurili8** [appreciated/vaadin-app-layout#39]
After user click the item on the left nav or the alarm popup message, Is there any way to close the left nav and the popup layout automatically.

Because I am trying to use it in the mobile Application. every time when user click the menu item, he has to hide the nav manually.

Thank you very much.

**Comment by appreciated** [comment]
Have you tried one of the following [Methods](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/java/com/github/appreciated/app/layout/behaviour/AbstractLeftAppLayout.java#L62)?

toggleDrawer( )
openDrawer( )
closeDrawerIfNotPersistent( )
closeDrawer( )

**Comment by appreciated** [comment]
Reopen if you still have problems
