### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by oliveryasuna** [appreciated/vaadin-app-layout#396]
Is there a way to manually add a drawer toggle? If so, how does one add it to the app bar on the left, before the title?

Is there a way to set the title after initialization?

Can you disable paper ripple?

Can you fix the footer of the app menu to the bottom?

If I apply my own Vaadin theme, the colors get messed up. For example, the entire drawer becomes white with no drop shadow. I even tried it with a blank theme.

<br/>

Thanks,

Oliver

**Comment by appreciated** [comment]
> Is there a way to manually add a drawer toggle? If so, how does one add it to the app bar on the left, before the title?
        
You can toggle the drawer via API. But there is no good way to add it before the title. I might update the UI for this use case. You could overwrite the icon component like this (If you still need the Icon, wrap it together with the Button in a HorizontalLayout):

```
Button button = new Button("test");

AppLayout appLayout = AppLayoutBuilder
        .withIconComponent(button)
        ...
        .build();
button.addClickListener(event -> appLayout.toggleDrawer());
```

**Comment by appreciated** [comment]
> Is there a way to set the title after initialization?

You can pass a Component instead of a String which you can update later on.

```
Span title = new Span("test");

AppLayout appLayout = AppLayoutBuilder
        .get(this.variant)
        .withTitle(title)
        ...
```

**Comment by appreciated** [comment]
> Can you disable paper ripple?

There is no supported way to do this

**Comment by appreciated** [comment]
Can you fix the footer of the app menu to the bottom?

Yes!

```
AppLayout appLayout = AppLayoutBuilder
        .get(this.variant)
        .withAppMenu(LeftAppMenuBuilder
                .get()
              ...
                .withStickyFooter()
                .build())
        .build();
```

**Comment by appreciated** [comment]
> If I apply my own Vaadin theme, the colors get messed up. For example, the entire drawer becomes white with no drop shadow. I even tried it with a blank theme.

[You can simply provide your own theme with custom values.](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/resources/META-INF/resources/frontend/com/github/appreciated/app-layout/app-layout-styles-lumo.css)
