### ISSUE TITLE
Menu Item I18N caption support

### ISSUE THREAD

**Issue by bishwajitcse** [appreciated/vaadin-app-layout#43]
How change the caption of menu item if need. Cause some time needs to change the I18N language caption. so it menu item name will bey dynamically change.

**Comment by appreciated** [comment]
Currently only possible by doing a full reinitalize. I will take a look into that to make it possible. 


From Version 0.9.10 on you can now do this:

```
.withNavigationElementInfoProvider(aClass ->
        new NavigationElementInfo(
                Optional.ofNullable(aClass.getAnnotation(MenuCaption.class)) // Caption
                        .map(menuElement -> menuElement.value())
                        .map(key -> I18N.getString(key))
                        .orElse(aClass.getAnnotation(SpringView.class).name()),
                Optional.ofNullable(aClass.getAnnotation(MenuIcon.class))  // Icon
                        .map(menuElement -> menuElement.value())
                        .orElse(null),
                aClass.getAnnotation(SpringView.class).name())  // ViewName
)
```

```
@SpringView(name = "")
@MenuCaption("Test")
@MenuIcon(VaadinIcons.ABACUS)
public class FirstView extends VerticalLayout implements View {
  ...
}
```

I will add a method that allows to refresh the Button Captions

**Comment by bishwajitcse** [comment]
That is not working for one more item. please give with 2 items..

**Comment by bishwajitcse** [comment]
Also Defaultnavigationview not working... It should to navigate default?

.withDefaultNavigationView(MobileInspectionView.class)

**Comment by appreciated** [comment]
`.withDefaultNavigationView(MobileInspectionView.class)` never works with cdi or spring since they do the whole Navigator configuration on their own. The only thing I can do is to navigate to specific views.

**Comment by appreciated** [comment]
> That is not working for one more item. please give with 2 items..

@bishwajitcse for the complete example check the [3rd code example on the Addon page](https://vaadin.com/directory/component/app-layout-add-on)
