### ISSUE TITLE
Why does the drawer not shows up?

### ISSUE THREAD

**Issue by DanielMartensson** [appreciated/vaadin-app-layout#448]
First of all: I'm using version 4.0.0 with Vaadin 14.6.8 with latest NodeJS installation. Installed yesterday.

I tried this example:
https://github.com/appreciated/vaadin-app-layout/tree/master/app-layout-examples/app-layout-plain-example

So here is the drawer?

![image](https://user-images.githubusercontent.com/28505229/150139324-4b736567-d52a-4b42-98ed-c9fc0e869ee5.png)

And this example https://github.com/appreciated/vaadin-app-layout/tree/master/app-layout-examples/app-layout-spring-example
Gave me this view. Where is the drawer here?

![image](https://user-images.githubusercontent.com/28505229/150140604-db604008-759b-4030-b34a-97d87b1894a9.png)

Here is the drawer that I'm missing

![image](https://user-images.githubusercontent.com/28505229/150140900-3c98e990-0575-4e0f-9c33-aab0e0ee4b40.png)

**Comment by appreciated** [comment]
@DanielMartensson Because the demo uses the LeftResponsive Variant. 
If you want the drawer Icon to be present, another variant needs to be used.

**Comment by DanielMartensson** [comment]
> @DanielMartensson Because the demo uses the LeftResponsive Variant. If you want the drawer Icon to be present, another variant needs to be used.

I understand. Perhaps you should update your examples then. They show the same results as above.
