### ISSUE TITLE
Missing Styles

### ISSUE THREAD

**Issue by kamuffe** [appreciated/vaadin-app-layout#54]
Hi

We added the AppLayout as described in our pom. 
All styles are missing. We had to add them manually in our theme. We have an own theme which imports the Vaadin standard theme "Valo". Did we miss something?

Thanks very much

**Comment by appreciated** [comment]
Hello this usually only happens when there is no entry in the addons.scss
![addons scss](https://user-images.githubusercontent.com/1729845/32600922-645b6fa4-c541-11e7-9684-5354ff648cee.PNG)
The entry will be added as soon as you run an maven `install` goal on you project.
