### ISSUE TITLE
Problem with prettytime dependencie

### ISSUE THREAD

**Issue by Daguinos** [appreciated/vaadin-app-layout#56]
Hi,

I want to use vaadin-app-layout addon with eclipse and Ivy but Ivy can't resolve the version RELEASE of prettytime.

Have you an idea ?

Thanks,

Thierry

**Comment by appreciated** [comment]
🤦‍♂️  this is a remain from development.

**Comment by appreciated** [comment]
fixed in #bfcea7a

**Comment by Daguinos** [comment]
Thanks,

Thierry

**Comment by appreciated** [comment]
0.9.14 should fix the problem now 🙂
