### ISSUE TITLE
Nav looks broken on Chrome

### ISSUE THREAD

**Issue by migonzap** [appreciated/vaadin-app-layout#6]
I've got installed the 0.7.2 version because the latest version gives me a NullPointerException when I call the build() method (it's because an AppBarIcon is not required on previous versions). The problem is that when I run my app on Google Chrome now the Toolbar looks broken, but if I run it on explorer it looks perfect.

![chrome](https://user-images.githubusercontent.com/3605023/30724863-2c188cc6-9f17-11e7-9c65-e96069d7e219.PNG)
![explorer](https://user-images.githubusercontent.com/3605023/30724862-2c187092-9f17-11e7-82fe-87d986901c58.PNG)

**Comment by appreciated** [comment]
I never meant to require any function, my fault, every function this builder is supposed to be optional. I will fix this asap.

**Comment by appreciated** [comment]
Unfortunatly the Upload does not seem to work currently I'll try tomorrow again

**Comment by migonzap** [comment]
No problem. Thanks!

**Comment by appreciated** [comment]
Fix is in!

**Comment by appreciated** [comment]
[Sorry but uploading Updates and making them available currenty does not seem to be possible](https://vaadin.com/forum/#!/thread/16824127)
