### ISSUE TITLE
View name interceptor on NavigatorNavigationElement not working as expected?

### ISSUE THREAD

**Issue by loefflefarn** [appreciated/vaadin-app-layout#60]
Hello,
I will use your addon in addition to Vaadin-Spring-Boot, but there is a problem with your `NavigatorNavigationElement`. It always return as viewName the caption. I have set the real viewName with `NavigatorNavigationElement.setViewNameInterceptor`, but this has no effect.

The value will be set in the NavigatorNavigationElement, but not in the Navigation.

```java
NavigatorNavigationElement element = new NavigatorNavigationElement("Caption", VaadinIcons.HOME, AnyOfMySpringView.class);
element.setViewNameInterceptor(info ->
{
    log.info("View name interceptor with info={}", info);
    return AnyOfMySpringView.class)).getAnnotation(SpringView.class).name();
});
log.info("ViewName: {}", element.getViewName());
appLayoutBuilder.add(element);
```

Can you help me out?

**Comment by appreciated** [comment]
Try to use the recently added method [Method](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/java/com/github/appreciated/app/layout/builder/AppLayoutBuilder.java#L182) (Path = viewname)

**Comment by loefflefarn** [comment]
Thanks for your replay, with this workaround it now working for me!

**Comment by appreciated** [comment]
@loefflefarn Are you using VaadinCDI or SpringCDI for any chance?
