### ISSUE TITLE
IllegalStateException in multi level submenus

### ISSUE THREAD

**Issue by pbaris** [appreciated/vaadin-app-layout#61]
Having the following struct

    AppLayoutBuilder drawer = AppLayoutBuilder.get(Behaviour.LEFT_RESPONSIVE_HYBRID)
        ...
        .add("Dashboard", VaadinIcons.DASHBOARD, DashboardView.class)
        .add(SubmenuBuilder.get("Submenu 1")
            .add("First", FirstView.class)
            .add(SubmenuBuilder.get("Submenu 2")
                .add("Second", SecondView.class)
                .add("Second", ThirdView.class).build()).build())
    .build();

In version `0.9.11` it worked. But in version `0.9.14` i get an 

`java.lang.IllegalStateException: Provider must not be null`

What i figure out is that in method

`com.github.appreciated.app.layout.builder.AppLayoutConfiguration#setComponentProviders`

if we set the provider in the `SubmenuNavigationElement`, as it was in `0.9.11`, it works.

    private void setComponentProviders(AbstractNavigationElement element) {
        if (element instanceof NavigatorNavigationElement) {
           ..
        } else if (element instanceof ClickableNavigationElement) {
            ...
        } else if (element instanceof SubmenuNavigationElement) {
            SubmenuNavigationElement selement = (SubmenuNavigationElement) element;
            ...
            selement.setProvider(submenuProvider); // add this line
            ...
        } else if (element instanceof SectionNavigationElement) {
            ...
        }
    }

**Comment by appreciated** [comment]
Thank you for the finding I will have a look into it later in the evening.

**Comment by deyaeddin** [comment]
I have faced the same issue, it occurred when I removed the BehaviourSelector from the main UI. 
I sorted out by removing AppLayoutSessionHelper Completely (because my implementation has a session management)
then in the AppLayoutConfiguration I commented out the following:
```
//        AppLayoutSessionHelper.setActiveVariant(variant);

        setTitle(title);
        if (true) {
            navigator = navigatorProducer.apply(instance.getContentHolder());
//            navigator.addViewChangeListener(viewChangeEvent -> {
//                AppLayoutSessionHelper.removeStyleFromCurrentlyActiveNavigationElement();
//                findNextNavigationElement(viewChangeEvent.getViewName()).ifPresent(element -> AppLayoutSessionHelper.setActiveNavigationElement(element));
//                return true;
//            });

....

```

Also
```
...
            nelement.setNavigationElementInfoProvider(navigationElementInfoProvider);
//            if (nelement.getViewClassName() == defaultNavigationElement.getViewClassName()) {
//                AppLayoutSessionHelper.updateActiveElementSessionData(nelement);
//            }
            navigatorElements.add(nelement);
...

```


Then it worked.
