### ISSUE TITLE
Regarding to the hamburger button for menu expand/collapse

### ISSUE THREAD

**Issue by mscho88** [appreciated/vaadin-app-layout#64]
Am I able to change its shape to custom one?

**Comment by appreciated** [comment]
Currently there isn't. But you probably can via JavaScript / CSS. The Button is the `paper-icon-button` Webcomponent if you want to check their documentation first.

**Comment by appreciated** [comment]
Updated the answer and added some examples how it could be solved.

**Comment by mscho88** [comment]
I just checked your updated answer.
Thank you again  :)

**Comment by mscho88** [comment]
I just checked and your implementation working fine.

One last question ..
I wanted to change the image icon to 'left-arrow' icon.

Is it possible to change the 'left-arrow' icon to 'right-arrow' when the menu is collapsing and 'right-arrow' to 'left-arrow' when the menu is expanding.

**Comment by appreciated** [comment]
I recommand waiting for #59

**Comment by mscho88** [comment]
has it been updated ? 

Could you please how to implement the shape or the icon of the navigation button?
