### ISSUE TITLE
Hide the app bar with some API provided

### ISSUE THREAD

**Issue by yurili8** [appreciated/vaadin-app-layout#65]
I am using this great app layout in the mobile client. it is really wonderful.

Here is one enhancement actually.

When I in the login screen, I found there is no way to hide the appbar. what I want to is maximize the content area without any menu and the app bar. This page is for login.

By the way, I am using "Behaviour.LEFT_HYBRID".

I also try to use some other behavior, which there is no app bar, but this is not want I want. I just want to hide the app bar during the login view.

any help will be appreciated.

**Comment by appreciated** [comment]
Can already be done via sass:
```
$al-bar-height: 0px;
```

Use two themes let one inherit from the other to avoid copying styles, in one overwrite the height in the simply other don't. [Switch the theme](https://vaadin.com/api/8.1.0/com/vaadin/ui/UI.html#setTheme-java.lang.String-) to reveal the app bar (It won't be animated though).

**Comment by RadoJoker** [comment]
Hello,
how are you integrating the login page without showing the menu?
Can you please provide some example code?

Thank you
Radostin

**Comment by appreciated** [comment]
@RadoJoker this issue is a feature request to enhance the API to allow removing the [AppBar](https://material-ui-next.com/demos/app-bar/) in the App-Layout. 
So it has not really something to do with a login page. 

The scss needed to remove the AppBar is actually given above. 
> $al-bar-height: 0px;

**Comment by appreciated** [comment]
Feel free to reopen this issue if you plan to make an addition
