### ISSUE TITLE
Collapse subMenu when click other menu

### ISSUE THREAD

**Issue by bladem** [appreciated/vaadin-app-layout#69]
If user expand a subMenu and after click in other menu item, all menu appears expanded, when you have too much items in menu are difficult to found other item menu.

**Comment by appreciated** [comment]
Probably a bug

**Comment by appreciated** [comment]
I cannot reproduce the problem you described can you please add some code and explain how the user needs to behave to reproduce the problem.

**Comment by bladem** [comment]
You can see the problem in the next picture. 
[https://ibb.co/epHKsw](url)

How I created the menu:
`private void setDrawerVariant(Behaviour variant) {
        holder.removeAllComponents();
        AppLayout drawer = AppLayoutBuilder.get(variant)
                .withTitle("Qualitas Educativa")
                .addToAppBar(new NotificationAppBarButton(notifications))
                .withViewNameInterceptor(new DefaultViewNameInterceptor())
                .withDefaultNavigationView(Vista.class)
                .withDesign(AppBarDesign.DEFAULT)
                .withNavigatorConsumer(navigator -> {/* Do someting with it */})
                .add(new MenuHeaderD(buildUserMenu()))
                .add("Home", VaadinIcons.HOME, badge, new Vista())
                .add(SubmenuBuilder.get("My Submenu", VaadinIcons.PLUS)
                        .add("Charts", VaadinIcons.SPLINE_CHART, View2.class).add(SubmenuBuilder.get("Subcategoria", VaadinIcons.ABACUS).add("Subcategoria 1",VaadinIcons.ACADEMY_CAP, View4.class).build())
                        .add("Contact", VaadinIcons.CONNECT, View3.class)
                        .add("More", VaadinIcons.COG, View4.class)                        
                        .build())         
                .add("Menu", VaadinIcons.MENU, View5.class)
                .add("Elements", VaadinIcons.LIST, View6.class)
                .addClickable("Set Behaviour", VaadinIcons.COG, clickEvent -> openModeSelector(variant))
                .build();
        holder.addComponent(drawer);
        getNavigator().navigateTo("");
    }`

**Comment by appreciated** [comment]
Ahh now I get it 😅

**Comment by appreciated** [comment]
Will now be done by default can be disabled via AppLayoutBuilder::withCloseSubmenusOnNavigate(false)
