### ISSUE TITLE
Update the sidebar selectors on navigator

### ISSUE THREAD

**Issue by blaluc** [appreciated/vaadin-app-layout#7]
After navigating to a view through the invocation of the navigator.navigateTo() method (or after a direct navigation through the browser url), the corresponding navigation item in the sidebar drawer should be marked as selected.

**Comment by appreciated** [comment]
Will investigate this one aswell before next release. Fix should be in today.

**Comment by appreciated** [comment]
It should now work with any modifications necessarcy

**Comment by appreciated** [comment]
Unfortunately the Upload does not seem to work currently I'll try tomorrow again

**Comment by appreciated** [comment]
Fix is in!

**Comment by appreciated** [comment]
[Sorry but uploading Updates and making them available currenty does not seem to be possible](https://vaadin.com/forum/#!/thread/16824127)
