### ISSUE TITLE
Hybrid Behavior: Margin does not reset on small devices

### ISSUE THREAD

**Issue by DinuMihnea** [appreciated/vaadin-app-layout#72]
How I can create an LeftHybrid app-layout with default small menu?

![app layout demo - google chrome](https://user-images.githubusercontent.com/20513656/33714346-4d6e776a-db57-11e7-8352-9325876c357f.png)

Thanks for great addon!

**Comment by appreciated** [comment]
Hello Dinu 😉 
Simply by making some [JS Calls](https://github.com/appreciated/vaadin-app-layout/blob/1e92147fe5ccea31cc814aea93f3bce20e51c394/app-layout-addon/src/main/resources/com/github/appreciated/app/layout/behaviour/left/left-hybrid.html#L54-L59):
````
layoutWrapper.classList.remove("small");
```

**Comment by DinuMihnea** [comment]
Thanks!

**Comment by appreciated** [comment]
Did it work?

**Comment by DinuMihnea** [comment]
Yes, but have a problem on small devices

**Comment by DinuMihnea** [comment]
![aquarius - google chrome_2](https://user-images.githubusercontent.com/20513656/33723005-1e55707e-db74-11e7-9591-28d3b4e0d4d7.png)

left margin does not reset on small devices

**Comment by appreciated** [comment]
Would have been too easy if it worked right away 😄

**Comment by DinuMihnea** [comment]
Ok, I wait an LeftHy
bridSmall in new version.
I think it will be a good addition.
Thanks!

**Comment by appreciated** [comment]
You will have to provide me with some to reproduce the issue.

**Comment by DinuMihnea** [comment]
Great,
Thanks for that!
