### ISSUE TITLE
start at the top of the view

### ISSUE THREAD

**Issue by Sergio70** [appreciated/vaadin-app-layout#75]
Hello, good morning, I need my point of view to start at the top.
every time the change of view starts from the part of the previous view.
Is there any way that when you change your point of view, start at the top?

this is in this way
[URL](https://drive.google.com/open?id=1aGs_rhGu2Cu6IzTOouwc5BhO2-RbVNjX)

as I explained
[Url](https://drive.google.com/open?id=1GEIWbGQfQdC8kzrLlz2ojPzvYGUnVxn4)

sorry for my English.

**Comment by appreciated** [comment]
Sorry but I cannot understand what you mean. Can you please provide some more detailed graphics to explain it?

**Comment by Sergio70** [comment]
Ok, I attached a video of what I explained.
[https://drive.google.com/file/d/1OZxkz5crlhPYEV3423awWeJ2MqK--PyL/view?usp=sharing](url)

When you change the view, you must start from above and not from the part of when you switch to the view

**Comment by appreciated** [comment]
Now I get it. To scroll to the top of the panel on navigating, just do the following:
```
@Override
protected void init(VaadinRequest request) {
    drawer = AppLayoutBuilder.get(Behaviour.LEFT_OVERLAY)
            .withNavigatorConsumer(navigator -> navigator.addViewChangeListener(viewChangeEvent -> onNavigate()))
            .build();
    drawer.addStyleName("left");
    holder.addComponent(drawer);
    getNavigator().navigateTo("");
}

private boolean onNavigate() {
    if (drawer != null) {
        drawer.getContentHolder().setScrollTop(0);
    }
    return true;
}
```

**Comment by Sergio70** [comment]
Wooo,  
Excellent, thanks for the help. Keep going. 👍 👍

**Comment by appreciated** [comment]
Will now be done be default can be disabled via `AppLayoutBuilder::withScrollToTopOnNavigate(false)`
