### ISSUE TITLE
Missing Files when switching to Mobile

### ISSUE THREAD

**Issue by dangllucas** [appreciated/vaadin-app-layout#77]
Hey there :)
At first Awesome Work 👍 👍 
It ist not really a Issue, but when I change my Browser window size to mobile size, log tells me following:

`Dez 13, 2017 11:45:02 PM com.vaadin.server.VaadinServlet serveStaticResourcesInVAADIN
INFORMATION: Requested resource [/VAADIN/bower_components/webcomponentsjs/webcomponents-lite.js.map] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.`
`Dez 13, 2017 11:45:02 PM com.vaadin.server.VaadinServlet serveStaticResourcesInVAADIN
INFORMATION: Requested resource [/VAADIN/bower_components/shadycss/apply-shim.min.js.map] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.`
`Dez 13, 2017 11:45:02 PM com.vaadin.server.VaadinServlet serveStaticResourcesInVAADIN
INFORMATION: Requested resource [/VAADIN/bower_components/shadycss/custom-style-interface.min.js.map] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.`

As I said, all works fine, but it gives this bad taste in my Log that something is wrong.

**Comment by appreciated** [comment]
This error comes from missing source map files. [This error only seems to occur if you have your chrome developer console open and source map enabled.](https://stackoverflow.com/questions/18425841/angular-min-js-map-not-found-what-is-it-exactly#comment40815261_18431438)

**Comment by appreciated** [comment]
Can you confirm it?

**Comment by dangllucas** [comment]
Sorry,
Gonna Check it when I'm at home

Am 14.12.2017 2:06 nachm. schrieb "appreciated" <notifications@github.com>:

**Comment by appreciated** [comment]
No need to apologise 😉. I just wanted to point out that I'm waiting for a response, which my previous comment didn't state clearly.

**Comment by dangllucas** [comment]
yep u were right. Only happens, when I'm on the developer console of chrome.

Next time ill google first ;)

Thx for your help

**Comment by appreciated** [comment]
You are welcome have a nice day!
