### ISSUE TITLE
Drawer width in edge & IE11 browser

### ISSUE THREAD

**Issue by DinuMihnea** [appreciated/vaadin-app-layout#78]
I have a problem with drawer width in edge browser.
If I change the scss variable **$al-drawer-width**,  in edge & IE11 browsers the width doesn't change (is always 256px), but the right margin is true, so if the  **$al-drawer-width** is smaller than 256px the right part of content is lost.

I have some attachments to demonstrate differents both _edge_ and _chrome_, with same css settings.
![edge sick brrowser](https://user-images.githubusercontent.com/20513656/34079439-5e795700-e336-11e7-8e41-abed945510a9.png)
![chrome](https://user-images.githubusercontent.com/20513656/34079440-5e950c5c-e336-11e7-986e-5f0bf43fc400.png)

**Comment by appreciated** [comment]
Bug is confirmed and fixed

**Comment by DinuMihnea** [comment]
I am sorry, but is doesn't work

**Comment by DinuMihnea** [comment]
Try this:
 [persistent].app-drawer-1 {
    width: $al-drawer-width;
  }
  .app-bar-application-content {
    left: $al-drawer-width;
  }

**Comment by DinuMihnea** [comment]
And this, for responsivity
@media only screen and (max-width : 641px) {
    .app-bar-application-content {
      left: 0 !important
    }
  }

**Comment by appreciated** [comment]
😞

**Comment by appreciated** [comment]
What did I miss?

**Comment by appreciated** [comment]
The bug was actually much more complicated to fix since in IE the code you mentioned caused even more bugs 😞

**Comment by DinuMihnea** [comment]
Code mentioned is work for LeftHybrid behavoir on version 0.9.17
For current version 0.9.19 I used this:
`  [persistent].app-drawer-1 {
    width: $al-drawer-width;
  }
  .app-bar-application-content {
    left: $al-drawer-width;
    transition: all .3s;
  }
  .small .app-bar-application-content {
    left: $al-drawer-small-width;
  }`

with a mixin for media query in _styles.scss_ excluded of main style class:
`@media only screen and (max-width : 640px) {
    .app-bar-application-content {
      left: 0 !important
    }
  }`

**Comment by appreciated** [comment]
I just wanted to let you know why I didn't add the fix right away since there were some additional problems (on IE only). The `[persistent].app-drawer-1 { width: $al-drawer-width; }` f.e. caused the div with the class `app-drawer` to be too small. This made also necessary to fix it by setting it directly` .drawer-content {width: $al-drawer-small-width !important; }`. Debugging under IE is so aweful 😑 it takes years.
