### ISSUE TITLE
Don't display View

### ISSUE THREAD

**Issue by luisrafaelinf** [appreciated/vaadin-app-layout#8]
when I try to display a view from the menu does not show it.

I test with the example you have and it does not work either.

**Comment by tocotest** [comment]
I am experiencing the same issue using following configuration:
AppLayout version 0.8.6
Vaadin 8.1.3
GWT 2.8.1
Tomcat 9
I have recompiled widgetsets, tried different browsers etc. 
No errors thrown.
Enter method of selected view is never called.
Otherwise excellent plugin.

**Comment by appreciated** [comment]
Do you use the Jar?

**Comment by luisrafaelinf** [comment]
I use the JAR and I clone the repository. I try with the example on demo section.

**Comment by appreciated** [comment]
Never mind I think I found the bug

**Comment by appreciated** [comment]
Fix is in checkout 0.8.7

**Comment by luisrafaelinf** [comment]
Can you test the design with chrome browser and firefox? there are some issues with the style.

LEFT_OVERLAY : i think that is fine!
LEFT_RESPONSIVE : i think that is fine!

LEFT_RESPONSIVE_OVERLAY : 
                          CHROME > no show the hamburguer button. 
                          FIREFOX > always show the  hamburguer button.

LEFT_RESPONSIVE_OVERLAY_NO_APP_BAR :
                          CHROME > no show the top bar (APP BAR). 
                          FIREFOX > always show the top bar (APP BAR).

LEFT_RESPONSIVE_SMALL : don't reduce the width of HEADER component.

LEFT_RESPONSIVE_SMALL_NO_APP_BAR: 
                          CHROME > no show the top bar (APP BAR) and don't reduce the width of HEADER component. 
                          FIREFOX > always show the top bar (APP BAR), don't reduce the width of HEADER component and always show the  hamburguer button.

**Comment by appreciated** [comment]
@luisrafaelinf Please add another Issue since it has nothing to do with the previous one. I will fix it as soon as I can.

**Comment by luisrafaelinf** [comment]
Ok, sorry.

**Comment by appreciated** [comment]
Thank you 🙂
