### ISSUE TITLE
MenuButton REclick for update view

### ISSUE THREAD

**Issue by utrucceh** [appreciated/vaadin-app-layout#82]
For example:
When clicked first menu button, it's putting view, but sometimes we want to update view via click to same button
Currently, we are clicking another menuButton then clicking old button
There is addClickable() rather than add(***) method but after click to it, it is not selecting
We can do via add(Component), and listen via onClick but the built in is better

**Comment by appreciated** [comment]
I do not recommend using a second click on the same button as a refresh since it is simply because no uninformed user will understand it intuitively. 
Instead I recommend using an additional action button inside the View for that. The recommended component for this in the Material Theme would be a [Floating action button](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-behavior). Another option is that since you are using Vaadin to develop a Webapplication (not a Website) you could simply push UI Updates to the client.

**Comment by appreciated** [comment]
Appart from that I will mark this as a enhancement, since there might be some usecases where having a feature to react to Click Events could come in handy.

**Comment by utrucceh** [comment]
If view on page, update is easly, but think about this example (now I have like this :) ):
There is ui and have 2 button
First button viewing a page (added via applayoutBuilder.add(**))
Second button is clickable (added via applayoutBuilder.addClickable(**)) and using 
`appLayout.contentHolder.content=newContent` method
if you click first button, then click second button, firstButton staying as clicked, but content is new content
When you want to click firstButton it is not working, you need to click another button and return to old first button
If there is selectMenuButton(**) or unSelectAllButton(**), it can solve problem, but there no method currently

**Comment by appreciated** [comment]
> appLayout.contentHolder.content=newContent
The Problem is that the Button will only be updated on ` Navigator::navigateTo(...)`. Have you tried doing it the following way?

```
public class DemoUI extends UI {
   private Navigator navigator;
   @Override
   protected void init(VaadinRequest request) {
      setContent(AppLayoutBuilder.get(Behaviour.LEFT_OVERLAY)
      .addClickable("MyCustomElementEntry", VaadinIcons.COG, clickEvent -> {
         navigator.navigateTo("MyCustomView");
       })
       .withNavigatorConsumer(navigator -> {
          this.navigator = navigator;
          navigator.addView("MyCustomView", MyCustomView.class);
       })
       .build());
   }
}
```

**Comment by utrucceh** [comment]
It's working, and clearing all selecteds, but have some issues, 
for example second click for MyCustomElementEntry is when try to add new View, clickListen working, but UI not changing because of UI navigator text is same,

we can hack via `navigator.navigateTo($randomStringEveryTime)` ,but also this will have some problems 
(for example when new View putted to UI, user press back there will show error like not found)

View replacement or unselectAllButton must work without navigator, think about this, via navigator page is when loaded it is registering somethink for edit (for example new car), when user navigate to new page and press back button, new Car registering

Currently best way (for now) all buttons will add via `addClickable(**)`
Thanks for your replys

**Comment by appreciated** [comment]
Don't even try to do some stuff like this `Navigator::navigateTo($randomStringEveryTime)`. I heavily recommend you to inform yourself about what the Navigator is and how it works. It would save you a lot of time. 

You can do what you aim for like this:
```
public class DemoUI extends UI {
   private Navigator navigator;
   @Override
   protected void init(VaadinRequest request) {
        setContent(AppLayoutBuilder.get(Behaviour.LEFT_OVERLAY)
                .addClickable("MyCustomElementEntry", VaadinIcons.COG, clickEvent -> {
                    if (navigator.getState().equals("MyCustomElementEntry")) { //  or if (navigator.getCurrentView() instanceof View2)
                        View2 view = (View2) navigator.getCurrentView();
                        view.invokeViewUpdate();
                    } else {
                        navigator.navigateTo("MyCustomView");
                    }
                })
                .withNavigatorConsumer(navigator -> {
                    this.navigator = navigator;
                    navigator.addView("MyCustomView", View2.class);
                })
                .build());
    }
}
```

**Comment by utrucceh** [comment]
I merged something with your last comment, temp views staying on  state of "-" with variable, via this components can load to page directly, without pass class.
Thanks

`{

    // --------------------------------------- ForNavigator --------------------------------------- \\
    var nav: Navigator? = null
    var lastTempView: Component? = null

    val viewNavigator: (Component) -> Unit = { comp ->
        lastTempView = comp
        nav?.let {
            if (it.state == "_") appLay?.contentHolder?.content = comp
            else it.navigateTo("_")
        }
    }

    // -------------------------------------- View & Others --------------------------------------- \\
    val appLay: AppLayout? = AppLayoutBuilder.get(Behaviour.LEFT_RESPONSIVE_HYBRID_OVERLAY_NO_APP_BAR)
            .withTitle("Title")
            .withDefaultNavigationView(Navigator.EmptyView())
            .withDesign(AppBarDesign.MATERIAL)
            .withNavigatorConsumer {
                nav = it.also {
                    it.addView("_", object : View {
                        override fun getViewComponent() = lastTempView
                    })
                }
            }
            .also { MenuButtonsLoader(merkez, viewNavigator, kAdiBosmuFunc, it).load() }
            .build()


    fun getRootView() = appLay!!

}
`
