### ISSUE TITLE
Warnings on SCSS compilation

### ISSUE THREAD

**Issue by luisrafaelinf** [appreciated/vaadin-app-layout#89]
Updating theme VAADIN/themes/mytheme
Jan 14, 2018 12:07:38 PM com.vaadin.sass.internal.ScssStylesheet warning
_ADVERTENCIA: Base-level rule contains the parent-selector-referencing character '&'; the character will be removed:
BlockNode [&.v-app, &.v-app-loading {
		Mixin node [name: valo-app-style args: Actual argument list [ArgumentList []]]
	}]
Jan 14, 2018 12:07:38 PM com.vaadin.sass.internal.ScssStylesheet warning
ADVERTENCIA: Base-level rule contains the parent-selector-referencing character '&'; the character will be removed:
BlockNode [.v-ff & .v-tree-node-drag-top:before, .v-ff & .v-tree-node-drag-bottom:after {
		Rule node [line-height: 1px;]
	}]_

Is necessary that you fix this property?

**Comment by appreciated** [comment]
I will take a look into this in the next few days

**Comment by appreciated** [comment]
When executing a `mvn vaadin:compile-theme` I won't get any warnings.
```
C:\Users\Johannes\IdeaProjects\vaadin-app-layout\app-layout-examples\no-navigator>mvn vaadin:compile-theme
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building App Layout Add-on No Navigator Example 0.9.20
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- vaadin-maven-plugin:8.2.1:compile-theme (default-cli) @ app-layout-example-no-navigator ---
[INFO] Updating theme VAADIN\themes\demo
[INFO] Theme "VAADIN\themes\demo" compiled
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.287 s
[INFO] Finished at: 2018-01-19T15:35:19+01:00
[INFO] Final Memory: 17M/220M
[INFO] ------------------------------------------------------------------------
```
Can you explain how I can reproduce it?

**Comment by luisrafaelinf** [comment]
i only upgrade the vaadin version and the app-layout

**Comment by appreciated** [comment]
You you give me an example project and tell me what steps I have to do to reproduce the issue?

**Comment by luisrafaelinf** [comment]
I have multi .SCSS files making imports and compiling the project with NetBeans, only that.
When i upgrade the version of vaadin and app layout and i compile the project the console show me that message. i'll test with `mvn vaadin:compile-theme`

**Comment by appreciated** [comment]
This issue does not occur in any of my projects so you will need to give me something to work with otherwise I can't do anything.
