### ISSUE TITLE
Internet Explorer not working at all

### ISSUE THREAD

**Issue by luisrafaelinf** [appreciated/vaadin-app-layout#9]
Can you test the design with chrome browser and firefox? there are some issues with the style.

LEFT_OVERLAY : i think that is fine!
LEFT_RESPONSIVE : i think that is fine!

LEFT_RESPONSIVE_OVERLAY :
CHROME > no show the hamburguer button.
FIREFOX > always show the hamburguer button.

LEFT_RESPONSIVE_OVERLAY_NO_APP_BAR :
CHROME > no show the top bar (APP BAR).
FIREFOX > always show the top bar (APP BAR).

LEFT_RESPONSIVE_SMALL : don't reduce the width of HEADER component.

LEFT_RESPONSIVE_SMALL_NO_APP_BAR:
CHROME > no show the top bar (APP BAR) and don't reduce the width of HEADER component.
FIREFOX > always show the top bar (APP BAR), don't reduce the width of HEADER component and always show the hamburguer button.

**Comment by appreciated** [comment]
So I have fixed it, It seems that the polymer component gives Firefix a different DOM that chrome, which leads to some css Selectors being ignored. 

But can

 you explain what you mean exactly by this? 

> don't reduce the width of HEADER component.

If you mean this in the demo, this is not a bug If a User inserts elements that are way to big it's more a bug in the demo -> It's the users fault. 
![Overflow](https://user-images.githubusercontent.com/1729845/30867970-aeec8cb4-a2dd-11e7-9df1-3789195a9f95.PNG)

**Comment by luisrafaelinf** [comment]
> This is not a bug but the Users fault. The user should not insert elements that are too big.

Yes, is that. Remember that you addons is for dummy developers :-)
which by the way is a great help and is excellent.


I hope to soon be able to use it and a few changes to my style in the design :1st_place_medal:

**Comment by appreciated** [comment]
[It is released try it out 😉 ](https://vaadin.com/directory/component/app-layout-add-on)

**Comment by luisrafaelinf** [comment]
in firefox continue all the details previously measured.

Internet Explorer all is broken (in my work they use IE unfortunately), it seems that **polymer** is not compatible.

**Comment by luisrafaelinf** [comment]
![4](https://user-images.githubusercontent.com/19829574/30870728-9cd6071a-a2b2-11e7-84ae-32dad93abf09.PNG)


Internet Explorer

**Comment by appreciated** [comment]
[Polymer 2 does support IE 11+](https://www.polymer-project.org/2.0/docs/browsers) I need to take a look at this

**Comment by appreciated** [comment]
Have you tried to recompile the Theme and cleaning the Browser cache for FF?

**Comment by luisrafaelinf** [comment]
> Have you tried to recompile the Theme and cleaning the Browser cache for FF?

Yes, all that.

**Comment by appreciated** [comment]
If you are interested you can [join me in Slack](https://join.slack.com/t/vaadin-app-layout/shared_invite/enQtMjQ0NDk0MTIyNjMwLTg3N2YxMzc3NDBhODY4ZGZhNDZlOTRmNzk3MjZhYzE3Nzg1YzQ3MGY0MDEyZTY2ZWRmMzlmOWM2MGE1OGRlZTM) so we can fix this straight 😅

**Comment by appreciated** [comment]
Unfortunately I am not able to fix the bug in Internet Explorer 11. 

But I added a workaround for it as a consequence IE 11 is not behaving responsive. But I think this is actually no problem since the devices requiring the responsive behavior will never use IE 11 😉.

**Comment by luisrafaelinf** [comment]
then it is only recommended for mobile interfaces?

**Comment by appreciated** [comment]
You can use it for both, no problem, the drawback of my described solution is that if you decrease the width of a IE11 Window the Menu will never slide in. Only in IE 11.

**Comment by appreciated** [comment]
Fixed!
