### ISSUE TITLE
Update example in how to use CDI builder

### ISSUE THREAD

**Issue by rodrifmed** [appreciated/vaadin-app-layout#93]
I'm trying to do this: AppLayout.getCDIBuilder(Behaviour.LEFT_HYBRID)
				.withDesign(AppBarDesign.MATERIAL)

But is not working. 

Could you release the older version, until update the new doc?

**Comment by appreciated** [comment]
Checkout the code samples in the vaadin dir

**Comment by rodrifmed** [comment]
Thanks!

**Comment by appreciated** [comment]
[I now also updated the examples in the Wiki.](https://github.com/appreciated/vaadin-app-layout/wiki#examples)
