### ISSUE TITLE
Use app-layout more than once

### ISSUE THREAD

**Issue by rodrifmed** [appreciated/vaadin-app-layout#95]
Hi, first thanks for the new release.

I wonder to know if is possible use the AppLayout.getNoNavigatorBuilder inside others contents.

I tried here, but the css is putting the position of the menu items out of screen.

Am I doing something wrong?

**Comment by appreciated** [comment]
You are welcom!

> I wonder to know if is possible use the AppLayout.getNoNavigatorBuilder inside others contents.
> I tried here, but the css is putting the position of the menu items out of screen.
[The App Layout is not meant to be used in any nested](https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-behavior) form and not optimized for it (I won't add support for it). 
The App Layout is meant to be used as a navigation drawer for a single application, if you need to nest multiple instance of the AppLayout you are trying to use a application inside another application, which isn't a good solution (also it will be pretty unusable on mobile devices). Instead you should create a simple list menu beforehand for the user to select a specific application. 
If you still want to use it for this checkout this old issue where [I once made the AppLayout purely visually work for the usage inside other components](https://github.com/appreciated/vaadin-app-layout/issues/11).

**Comment by rodrifmed** [comment]
Thanks! 

In my case the application will not run in a mobile application and because of the style of your menu is very good and everything is prepare to use the menu with subitems and etc...

I think I will not be the only one who wants to use your addon in nested components.

**Comment by appreciated** [comment]
Feel free to reopen this issue if you plan to make an addition
