### ISSUE TITLE
Spring Boot - Vaadin Session - AppLayout

### ISSUE THREAD

**Issue by dangllucas** [appreciated/vaadin-app-layout#99]
I am working on a webapp with vaadin based on spring boot.
To authenticate the user I have a Login Page to create a Custom Token for the Spring Security Context.
After a successfull Login the user gets into my Application.
Here is a littel step by step guide what I do:

1.  Login 'Test User 1'
2. "App Layout shows up on test user 1's device, with a header with its user Name 'Test User 1"
3. Login 'Test User 2' from another device
4. "App Layout ashows up on test user 2's device, with a header with its user Name 'Test User 2'
5. On Test User 1 Account I Click on a  Navigation Point and content of AppLayout gets cleared and in the header the Name of 'Test User 2' appears.

BUT Log tells me, that on each device each Security Token for each user is in the Vaadin Session.
So every user is still logged in to its account, only appLayout header shows the Username of the last logged in user.

Strange: After a reload of the Page, every device shows the correct username again...

P.S.: If you want I can Attach a Video to show you the behaviour.

AppLayout-Building:
`AppLayoutComponent appLayout = AppLayout.getCDIBuilder(Behaviour.LEFT_HYBRID)
                .withViewProvider(() -> viewProvider)
                .withNavigationElementInfoProvider(new DefaultSpringNavigationElementInfoProvider())
                .withTitle("DSA")
                .addToAppBar(buildSettings())
                .withDesign(AppBarDesign.MATERIAL)
                .add(new CustomMenuHeader("Test", "Logged in as: " + user.getFirstName() + " " + user.getLastName(), new ThemeResource("img/logo.png")), AppLayoutConfiguration.Position.HEADER)
                .add(VaadinSessionScopedView1.class)
                .add(VaadinSessionScopedView2.class)
                .add(VaadinSessionScopedView3.class)
                .build();`

**Comment by appreciated** [comment]
Can you please refine this issue so we can close it? (we discussed it on slack)

**Comment by henriquemeira** [comment]
@dangllucas Did you get a solution?

**Comment by dangllucas** [comment]
@henriquemeira yeah we solved that issue on slack
It actually was not a Problem with the app layout itself, it was just my thought of the closest solution.
Actually the problem was the google guava event bus that sent event through all sessions and made the whole vaadin and spring boot session stack completely behaving strange.

@appreciated Sorry for not answering, didnt get an email notification on this.
